src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>Client</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field to employer - in accounts</description>
        <label>Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employment_Type__c</fullName>
        <label>Employment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Employed FT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employed PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Training/Readiness Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Leaving_Other__c</fullName>
        <label>Reason for Leaving (Other)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Leaving__c</fullName>
        <label>Reason for Leaving</label>
        <picklist>
            <picklistValues>
                <fullName>Family Responsibilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Job</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed/Obtained Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School Conflict</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonal/Contract Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Employment</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Emp-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/employmentMethodsUnitTests.cls
@isTest
private class employmentMethodsUnitTests {

    static testMethod void testEmploymentUpdateContactRecord() {
    
        utilityIds utilIds = new utilityIds();
        
        // Stage Data
        Account accEmployer = new Account(Name='Employer', RecordTypeId = utilIds.accExternalEntities);        
        
        Account accClient = new Account(Name='Unit Tester', RecordTypeId = utilIds.accClient);
        insert new sObject[]{accClient, accEmployer};
        
        Contact newContactForInsert = new Contact();
        newContactForInsert.lastName = 'Test';
        newContactForInsert.Client_Status__c = 'Active';
        newContactForInsert.Drug_test_frequency__c = 'Bi-Weekly';
        newContactForInsert.Current_Projected_Exit_Date__c = System.Today().addDays(25);
        newContactForInsert.Client_Status__c = 'Active';
        newContactForInsert.Intake_Date__c = System.Today();
        newContactForInsert.Current_Intake_Date__c = System.Today();
        newContactForInsert.Current_Orientation_Date__c = date.newInstance(2011,1,1);
        newContactForInsert.Current_Exit_Date__c = date.newInstance(2011,7,1);
        newContactForInsert.Team_Leader__c = UserInfo.getUserId();
        newContactForInsert.RecordTypeId = utilIds.conClient;
        newContactForInsert.accountId = accClient.id;
        insert newContactForInsert;
        
        // Execute Test Cases
        
        test.startTest();
        
        Employment__c empCase1 = new Employment__c();
        empCase1.Employer__c = accEmployer.Id;
        empCase1.Client__c = newContactForInsert.Id;
        empCase1.Employment_Type__c = 'Unemployed';
        empCase1.Start_Date__c = date.newInstance(2000, 1, 1);
        //empCase1.End_Date__c = date.newInstance(2010, 12, 31);
        empCase1.Job_Title__c = 'Chief Yak Herder';
        insert empCase1;
        
        Employment__c empCase2 = new Employment__c();
        empCase2.Employer__c = accEmployer.Id;
        empCase2.Client__c = newContactForInsert.Id;
        empCase2.Employment_Type__c = 'Unemployed';
        empCase2.Start_Date__c = date.newInstance(2000, 1, 1);
        empCase2.End_Date__c = date.newInstance(2010, 12, 31);
        empCase2.Reason_for_Leaving__c = 'Other';
        empCase2.Reason_for_Leaving_Other__c = 'Yak shortages';
        empCase2.Job_Title__c = 'Chief Yak Herder';
        insert empCase2;
        
        test.stopTest();
        
    }
}