src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gender Non-Conforming</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nonbinary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transgender Man</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transgender Woman</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <inlineHelpText>If Multiple Programs selected, please define scope (which programs) in description.</inlineHelpText>
        <label>Program</label>
        <picklist>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All START Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Youth Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI START</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choices - All boroughs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choices - Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choices - Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRT - All Boroughs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRT - Brooklyn (CCI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRT - Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CJC/JS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple Programs</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PEAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QJC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>START</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervised Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Intake_Date__c</fullName>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Master_Intake_Docket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Intake Docket</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Client_Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Client_Account__c</valueField>
            </filterItems>
            <infoMessage>Use this field to select the primary intake case when there are multiple intake cases with a mandate, or a client is reinstated and a new case&apos;s mandate is added to the old, &quot;master&quot; docket.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Attached Dockets</relationshipLabel>
        <relationshipName>Attached_Docket</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part__c</fullName>
        <label>Part</label>
        <picklist>
            <picklistValues>
                <fullName>016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>054</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>43</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR2A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR3A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTP1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JP5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jury 9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAP-B</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Top_Plea_Charge__c</fullName>
        <label>Top Plea Charge</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Case_Court_Status_Calc__c</fullName>
        <description>pull case court status value from cae information</description>
        <formula>Docket__r.Case_Court_Status__c</formula>
        <label>Case Court Status Calc</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Contact__r.Name_and_P_C_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Relationships</relationshipLabel>
        <relationshipName>Case_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Docket_Indictment__c</fullName>
        <formula>if(Docket__r.Indictment__c = &apos;&apos;,Docket__r.Name, Docket__r.Indictment__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Docket Indictment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket_Name__c</fullName>
        <formula>Docket__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Docket Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket__c</fullName>
        <label>Docket</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NYSID__c</fullName>
        <formula>Contact__r.NYSID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NYSID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCID__c</fullName>
        <formula>Contact__r.P_C_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PCID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>substitute(Contact__r.RecordType.Name, &quot; Client&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Case Relationship</label>
    <nameField>
        <displayFormat>CR-{0}</displayFormat>
        <label>Case Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>First_Session_On__c</fullName>
        <description>A system-maintained field that displays the first session for this Class</description>
        <label>First Session On</label>
        <type>Date</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Client that will be enrolled in a Class</description>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>relContactEnrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Relationships__c.object
<CustomObject>
    <description>Details relationship between warrant | program | client</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Warrant__r.FirstName &amp; &quot; &quot; &amp;  Warrant__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly &quot;Program&quot;, Formerly Treatment Agency, changed 9/29/13 for START by MB</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Entities, Treatment Agency, CASES Programs</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Warrant Relationships</relationshipLabel>
        <relationshipName>Program_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Date__c</fullName>
        <label>Referral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Warrant__c</fullName>
        <description>previously referred to as &quot;PRP Cycle&quot;, changed by MB 9/29/13</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Relationships</relationshipLabel>
        <relationshipName>Program_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Relationships</label>
    <nameField>
        <displayFormat>PR-C{0}</displayFormat>
        <label>Program Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <recordTypes>
        <fullName>Employment</fullName>
        <active>true</active>
        <label>Employment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StartComplianceController.cls
public with sharing class StartComplianceController {
 public String getChooserender() { 
   if (ApexPages.currentPage().getParameters().get('p') != null){
      return 'pdf';}
   else
   return null;} 
    public utilityIds utilIds = new utilityIds();
    public String strContactId; 
    public String strTRPClass {get;set;}
    public String strLetterType {get;set;}   
    string conCCI = 
       Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CCI START Client').getRecordTypeId();
    string conCEO = 
       Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CEO Client').getRecordTypeId();
 
    public String strFileName {get;set;}
    public String strTRPClassDate {get;set;}
    public String strContactType {get;set;}
    public String strTrackName {get;set;}
    public Boolean bolSuccessful {get;set;}
    public String strOutcome {get;set;}
    Public String strIntakeDate {get;set;}
    Public String strCurrentExitDate {get;set;}
    Public String strComplianceDate {get;set;}
    Public String strSalutation {get;set;}
    Public String strGenderPronoun {get;set;}
    Public String strPossessiveGenderPronoun {get;set;}
    public Contact c {get;set;}
    public Event evtMostRecentCourtDate {get;set;}
    public List<Case_Information__c> lstAttachedCases {get;set;}
    public List<Event> lstProgramReporting {get;set;}
    public list<Program_Relationships__c> lstProgramRelationships {get;set;}
    
    //TRP
    public Boolean bolTRP {get;set;}
    public Boolean boolONE {get;set;}
    public list<Contact> lstTRPContacts {get;set;}

    public StartComplianceController() {
    
        strLetterType = System.currentPagereference().getParameters().get('lettertype');
        strContactId = System.currentPagereference().getParameters().get('contact');   
        strTRPClass = System.currentPagereference().getParameters().get('trpclass');
        
               c = [select id, Name, Intake_Case__c, NYSID__c, Salutation, FirstName, LastName, PRP_Status__c,accountid,
               Current_Exit_Type__c,
                        P_C_Id__c, Book_Case__c, Current_Intake_Date__c, Intake_Date__c, Current_Exit_Date__c, 
                        Intake_Case__r.Top_Plea_Charge__c, Intake_Case__r.RecordTypeId, Compliance_Date_Formula__c, 
                        Mandated_Days_Sessions__c, Days_Sessions_Completed__c, RecordTypeId, Gender_CC__c, Intake_Case__r.Name
                        from Contact
                        where Id = :strContactId];
     System.Debug('\n\n XXX strContactType: ' + strContactType);
     //   strContactId = '003f200002KdyGX';
        if (c.P_C_Id__c.left(3) == 'ONE'){
           strContactType = 'ONE';
                     selectData(c);
            boolONE = true;         
            return ;
         }else{   
        if(strTrpClass == null) {
        
            bolTRP = false;
    /*
            c = [select id, Name, Intake_Case__c, NYSID__c, Salutation, FirstName, LastName, PRP_Status__c,
                        P_C_Id__c, Book_Case__c, Current_Intake_Date__c, Intake_Date__c, Current_Exit_Date__c, 
                        Intake_Case__r.Top_Plea_Charge__c, Intake_Case__r.RecordTypeId, Compliance_Date_Formula__c, 
                        Mandated_Days_Sessions__c, Days_Sessions_Completed__c, RecordTypeId, Gender_CC__c, Intake_Case__r.Name
                        from Contact
                        where Id = :strContactId];
*/
            strIntakeDate = '';
            strComplianceDate = '';
            strCurrentExitDate = '';
            strSalutation = '';
            
            if(c.Intake_Date__c != null) {
                        
                strIntakeDate = c.Intake_Date__c.format();
            }
            
            if(c.Compliance_Date_Formula__c != null) {
            
                strComplianceDate = c.Compliance_Date_Formula__c.format();
            }
            
            if(c.Current_Exit_Date__c != null) {
            
                strCurrentExitDate = c.Current_Exit_Date__c.format();
            }
            
            if(c.Salutation != null) {
            
                strSalutation = c.Salutation;
            } 
            
            if(c.Gender_CC__c == 'Male') {
                
                if(strSalutation == null) {
                    strSalutation = 'Mr.';
                }
                strGenderPronoun = 'He';
                strPossessiveGenderPronoun = 'his';
            } else {
                
                if(strSalutation == null) {
                    strSalutation = 'Ms.';
                }
                strGenderPronoun = 'She';
                strPossessiveGenderPronoun = 'her';                
            }
            
            //Contact type            
            if(c.RecordTypeId == utilIds.conDTC) {
            
                strContactType = 'DTC';
                strTrackName = 'Daytime Custody';
           } else if(c.RecordTypeId == utilIds.conCCM) {
            
                strContactType = 'CCM';
                strTrackName = 'Community Case Management';
            } else if(c.RecordTypeId == conCCI) {
            
                strContactType = 'CCI';
                strTrackName = 'Center for Court Innovation';
           } else if(c.RecordTypeId == conCEO) {
            
                strContactType = 'CEO';
                strTrackName = 'Center for Employment Opportunities';                
            } else if(c.RecordTypeId == utilIds.conTRP) {
            
                strContactType = 'TRP';
                strTrackName = 'Treatment Readiness Program';
            }
            
            //Outcome based on letter type and contact exit type
            if(strLetterType == 'Extension') {
                
                strOutcome = 'Request for condition to be deemed satisfied Request for extension';
                strFileName = c.Name + ' ' + strContactType + ' ' + 'Extension Letter';
            } else if(c.PRP_Status__c == 'Successful Exit') {
            
                strOutcome = 'Successfully Completed Mandate';
                bolSuccessful = true;
                strFileName = c.Name + ' ' + strContactType + ' ' + 'Completion Letter';
            } else if(c.PRP_Status__c == 'Unsuccessful Exit'){
            
                strOutcome = 'Failed to complete';
                bolSuccessful = false;
                strFileName = c.Name + ' ' + strContactType + ' ' + 'Unsuccessful Exit Letter';
            }
            
            strFileName = strFileName.replace(' ', '_');
                        
                        
            list<Event> lstEventTemp = [select id, ActivityDate, Part__c 
                                            from Event
                                            where RecordTypeId = :utilIds.courtDate
                                            and whoId = :strContactId
                                            and Court_Date_Type__c = 'Compliance'
                                            order by ActivityDate desc limit 1];
                                            
            evtMostRecentCourtDate = new Event();
            
            if(lstEventTemp.size() > 0) {
            
                evtMostRecentCourtDate = lstEventTemp[0];
            }
                                            
            lstAttachedCases = [select id, Name from Case_Information__c
                                                          where Master_Intake_Docket__c = :c.Intake_Case__c];
            
            lstProgramReporting = new list<Event>();
            
            if(strContactType == 'CCM' || strContactType == 'CCI' || strContactType == 'CEO') {
    
                lstProgramReporting = [select id, ActivityDate
                                                    from Event
                                                    where Subject = 'Program Reporting'
                                                    and whoId = :strContactId
                                                    and Verification_Status__c = 'Attended'
                                                    and ActivityDate >= :c.Intake_Date__c
                                                    and ActivityDate <= :c.Current_Exit_Date__c];        
            } else if(strContactType == 'DTC') {
                                                          
                lstProgramReporting = [select id, ActivityDate
                                                    from Event
                                                    where Subject = 'Program Reporting'
                                                    and whoId = :strContactId
                                                    and Verification_Status__c = 'Attended'
                                                    and ActivityDate >= :c.Intake_Date__c
                                                    and ActivityDate <= :c.Compliance_Date_Formula__c];
            }
                                                
            lstProgramRelationships = [select id, Program__r.Name, Referral_Date__c
                                                                        from Program_Relationships__c
                                                                        where Warrant__c = :strContactId
                                                                        and Referral_Date__c >= :c.Current_Intake_Date__c];
        } else {
        
            bolTRP = true; 
            lstTRPContacts = [select id, Intake_Case__r.Name, Name, FirstName, LastName, TRP_Next_Class_Date__c
                                from Contact
                                where id in (Select Client__c From Enrollment__c Where Class__c = :strTRPClass)];
            Class__c clsTRP = [select id, First_Session_On__c from Class__c where id = :strTRPClass];
            Date d = clsTRP.First_Session_On__c;
            Datetime dt = Datetime.newInstance(d.year(), d.month(), d.day());
            strTRPClassDate = dt.format('MM/dd/yyyy');
            strFileName = dt.format('MMM_dd_yyyy') + '_TRP_Letters';
        }                                                                        
    }}
    
    public String getPrintView() {
    
        return
        '<!--[if gte mso 9]>' +
            '<xml>' +
            '<w:WordDocument>' +
            '<w:View>Print</w:View>' +
            '<w:Zoom>100</w:Zoom>' +
            '<w:DoNotOptimizeForBrowser/>' +
            '</w:WordDocument>' +
            '</xml>' +
            '<![endif]>';
    }    
    
    public String getToday() {
    
        return system.today().format();
    }
    
     public string cName{get;set;}
  //public string dsent{get;set;}
  public string Expession1{get;set;}
  public string Expession2{get;set;}
  public string docket{get;set;}
  public string letterDate{get;set;}
  public string outcome{get;set;}
    void selectData(Contact c){
      letterDate = date.today().format();
    //Contact c = [Select name,accountid,current_intake_date__c,current_exit_type__c from Contact where id =: strContactId];
    cName = c.name;
    string accId = c.AccountId;
    string exittype = c.Current_Exit_Type__c;
    string dsent = c.Current_Intake_Date__c.format();
    Account a = [Select gender__c from Account where id =: accId];
    string gender = a.Gender__c;
    
    List<Case_Relationship__c> lstDocket = [select Id, Docket__c,Client_Name__c,contact__c,pcid__c,docket_Name__c,
     docket_indictment__c,Case_Court_Status_Calc__c,case_type__c,ArrestDate__c From Case_Relationship__c 
     where contact__c =: strContactId and Case_Type__c =: 'Intake Case' order by ArrestDate__c desc limit 1];
     if (lstDocket.size() != 0)
        docket = lstDocket[0].docket_Name__c;
     else   
       docket = 'not entered';
     string g1,g2,g3;
     if (gender == 'Male'){
       g1 = 'Mr.';
       g2 = 'his';
       g3 = 'He';
     }
     else{
     g1 = 'Ms.';
       g2 = 'her';
       g3 = 'She';
     }
     if (exitType == 'Successful Exit'){
       Expession1 = 'Please be advised that the above referenced individual ' + '\'' + 's'  + ' participation in the CASES ' + 
       'Manhattan START ONE track fully satisfies the conditional discharge sentence received on ' + dsent + '.'; 
       Expession2 = g1 + cName + ' received a compehensive clinical assessment of ' + g2 + ' treatment needs. '  +
       g3 + ' has completed mandated case management sessions required by the terms of ' + g2 + ' release into the community and is ' +          
       'in full in compliance.';
       outcome = 'Successfully Completed Mandate';
     }
     else{
       Expession1 = 'Please be advised that the above referenced individual ' + '\'' + 's'  + ' participation in the CASES ' + 
       'Manhattan START ONE track does not fully satisfy the conditional discharge sentence received on ' + dsent + '.'; 
        Expession2 = g1 + cName + ' received a compehensive clinical assessment of ' + g2 + ' treatment needs '  +
       'and developed a treatment plan with our program. Despite outreach efforts, ' + 
       g1 + cname + ' did not complete mandated case management sessions which were required under ' + 
       'the conditions of ' + g2 + ' plea agreement.';
       outcome = 'Failed to complete';
     }
  }
}