src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indictment__c</fullName>
        <inlineHelpText>Two format:s are permitted  
  12345-2006   and  
  SCI12345-YYYY   where YYYY is the year</inlineHelpText>
        <label>Indictment #</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Plans</relationshipLabel>
        <relationshipName>Program_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <description>Activity date from Event</description>
        <inlineHelpText>Scheduled date of event</inlineHelpText>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Escort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis Intervention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Empowerment and Self Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Life and Social Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare Linkage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Support Facilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Judicial and Civic Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal/Recidivism Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Linkage To Services (Other)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical ER Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medication Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health Treatment Linkage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Program_Plan__r.Client_Name__r.FirstName &amp; &apos; &apos; &amp; Program_Plan__r.Client_Name__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date w/ default date created. Read-only except for System Administrators</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Plan__c</fullName>
        <label>Program Plan</label>
        <referenceTo>Program_Plan__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Progress_Note__c</fullName>
        <label>Progress Note</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>P_Note-{0000}</displayFormat>
        <label>Progress Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/viewProgressNotesController_UT.cls
@isTest(SeeAllData=true)
private class viewProgressNotesController_UT {
    static Progress_Note__c pn2 = new Progress_Note__c();
    static Progress_Note__c pn1 = new Progress_Note__c();
    static Program_Plan__c  prgPlan = new Program_Plan__c();
    static Case_Information__c Case1 =  new Case_Information__c();    
    static utilityIds utilIds = new utilityIds();
    static string contId;  
    static ID contRecType = Utility_ID__c.getValues('SRP Client').RecordType_Id__c;
    static Id  ppRecType  = Utility_ID__c.getValues('SRP Program Plan').RecordType_Id__c;
    static Id accRecType  = Utility_ID__c.getValues('Client').RecordType_Id__c;
    static void createEventsTestData() {
        
        Account a1 = new Account();
        a1.name = 'Thelonius Monk';
        a1.RecordTypeId = accRecType;
        a1.NYSID_Number__c = '64989923Q';
        a1.DOB__c = Date.newInstance(1970,1,1); 
        insert a1;  
 
        Contact c1 = new Contact();
        c1.FirstName = 'Thelonius';
        c1.LastName = 'Monk';
        c1.Client_Status__c = 'Active';
        c1.AccountID = a1.id;
        c1.RecordtypeId = contRecType;
        insert c1;
        contId = c1.id;
    
        Case1 = new Case_Information__c();
        case1.Client_Account__c =  a1.id;
        case1.RecordTypeId = utilIds.caseInfoSupremeCourt;
        case1.Name = '2014BG456011';
        case1.Indictment__c = '1235648794';
        case1.Borough__c = 'Bronx';
        insert case1; 
        Id caseid1 = case1.id;  
        
        Event evtCourtDate = new Event();
        evtCourtDate.RecordTypeId = utilIds.courtDate;
        evtCourtDate.WhoId = contId;
        evtCourtDate.StartDateTime = System.Today().addDays(20);
        evtCourtDate.Court_Report_Required__c = false;
        evtCourtDate.WhatId = caseid1;
        evtCourtDate.Area__c = 'Court Date';
        evtCourtDate.Outcome__c = 'Pending';
        evtCourtDate.Subject = 'Court Date';
        evtCourtDate.DurationInMinutes = 60;
        evtCourtDate.ActivityDate = Date.today();
        insert evtCourtDate;
                
   
    //    Program_Plan__c pp1 = [select id from Program_Plan__c where Client_Name__c = :contId];
        prgPlan = new Program_Plan__c();
        prgPlan.Client_Name__c = contId;
        prgPlan.RecordTypeId = ppRecType;
        insert prgPlan;
     
        List<Program_Plan__c> ppTest = [select id from Program_Plan__c where Client_Name__c = :contId ];
        
        ID ppId = ppTest[0].id;
        
        pn1 = new Progress_Note__c();
        pn1.Program_Plan__c = ppid;   
        pn1.Activity_Date__c = system.today() - 1;
        pn1.Date__c = system.today();
        pn1.Progress_Note__c = 'Better get it in your soul';
        pn1.Area__c = 'Case Coordination';
        pn1.RecordTypeId = utilIds.progressNoteCCCRS;
        insert pn1;
      
        pn2 = new Progress_Note__c();
       pn2.Program_Plan__c = ppid;   
        pn2.Date__c = system.today().addDays(-15);
       pn2.Activity_Date__c = system.today().addDays(-17);     
        pn2.Progress_Note__c = 'Five Spot Blues';
        pn2.Area__c = 'Case Coordination';
        pn2.RecordTypeId = utilIds.progressNoteCCPN;
                        
        insert pn2;
     
    }   
      static testMethod void testPage(){
      	createEventsTestData();
        PageReference pageRef = Page.viewProgressNotes;
        string cid = contId.substring(0,15);
        pageRef.getParameters().put('clientId',cid);
        Test.setCurrentPage(pageRef);
        viewProgressNotesController v = new viewProgressNotesController();          
       	test.startTest();
           
       v.noteValue = 'All';
       v.areaValue = 'All';
       v.shownotes();
        test.stopTest();
     /*   
        ApexPages.currentPage().getParameters().put('clientId',string.valueOf(c1.id).substring(0,15)); 
        ctrl = new viewProgressNotesController();
        system.assertEquals(ctrl.lstPN.size(), 2);
        
        ApexPages.currentPage().getParameters().put('clientId',string.valueOf(c2.id).substring(0,15)); 
        ctrl = new viewProgressNotesController();
        system.assertEquals(ctrl.lstPN.size(), 0);              
*/
    }
}