src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address_Information__c.object
<CustomObject>
    <label>Address Information</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Add-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Charges__c.object
<CustomObject>
    <description>To enter all charges for a case - arrest, plea, indictment and court related</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Arrest Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indictment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plea/ Finding Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Charges</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Case Charges ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Judge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Judge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Judge</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Judge)</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Client_Diagnosis__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Client_Diagnosises</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Client_Diagnosises</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Plan</label>
        <referenceTo>Program_Plan__c</referenceTo>
        <relationshipName>Client_Diagnosises</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Client Diagnosis</label>
    <nameField>
        <displayFormat>CD-{00000000}</displayFormat>
        <label>Client_Diagnosis Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Diagnoses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DSM4_code__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DSM4_code</label>
    <nameField>
        <label>DSM4_code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DSM4_codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Penal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Penal Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Penal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>Case_Coordinator__c</fullName>
        <formula>Client_Name__r.Case_Coordinator__r.FirstName &amp; &apos; &apos; &amp;Client_Name__r.Case_Coordinator__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Coordinator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Plans</relationshipLabel>
        <relationshipName>Program_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/DSM_4_UnitTest.cls
@isTest (SeeAllData=true)
private with sharing class DSM_4_UnitTest {
    //  static Id cepClient = Utility_ID__c.getValues('CEP Client').RecordType_Id__c;
    static reportQuery rq = new reportQuery();
   static utilityIds utilIds = new utilityIds();
    static Case_Information__c newCaseInfo = new Case_Information__c();
//    static Event eventTest = new Event();
     static Contact newContactForInsert = new Contact();
     static Contact newJudge = new Contact();
    static Client_Diagnosis__c  newDiagnosisForInsert = new Client_Diagnosis__c();
    static Client_Diagnosis__c  newDiagnosisForInsert1 = new Client_Diagnosis__c();
//    static Case_Charges__c chgTest = new Case_Charges__c();
    static Program_Plan__c PPforInsert = new Program_Plan__c();
    static Program_Plan__c PPforInsert1 = new Program_Plan__c();
    static DSM4_code__c dsmcodes = new  DSM4_code__c();
 
 //   static Penal_Code__c ppcode = new Penal_Code__c();
    static Account newAccountForInsert = new Account();
 //   static Address_Information__c addressTest = new Address_Information__c(); 
    static Id caseRecTypeId = Utility_ID__c.getValues('Case - Criminal Court').RecordType_Id__c;
    static Id EventRecTypeId = Utility_ID__c.getValues('Court Date').RecordType_Id__c;
    static Id conCRT = Utility_ID__c.getValues('CIRT Client').RecordType_Id__c; 
    static Id judge  =  Utility_ID__c.getValues('Judge').RecordType_Id__c; 
 //   static Id accCIRT = Utility_ID__c.getValues('CIRT Account').RecordType_Id__c;
      static void createTestData()
  {   
      
        newJudge = new Contact();
        newJudge.FirstName = 'judgeFirst';
        newJudge.lastName = 'JudgeLast';
        newJudge.RecordTypeId = utilIds.conJudge; 
        insert newJudge;

        newAccountForInsert = new Account();
        newAccountForInsert.name = 'Dusty Bottoms';
        newAccountForInsert.RecordTypeId = utilIds.accClient;
        newAccountForInsert.NYSID_Number__c = '90978021U';
        newAccountForInsert.DOB__c = Date.newInstance(1970,1,1);
        insert newAccountForInsert;
        
        newCaseInfo = new Case_Information__c();
        newCaseInfo.Client_Account__c = newAccountforInsert.Id;
        newCaseInfo.RecordTypeId = utilIds.caseInfoCriminalCourt;
        newCaseInfo.Name = '2011BV144590';
        newCaseInfo.Borough__c = 'Bronx';
        newCaseInfo.judge__c = newjudge.id; 
        insert newCaseInfo;
  
        newContactForInsert = new Contact();
        newContactForInsert.FirstName = 'Dusty';
        newContactForInsert.lastName = 'Bottoms';
        newContactForInsert.Client_Status__c = 'Screened';
        newContactForInsert.Case_Coordinator__c = utilIds.defaultTaskAssignedTo;
        newContactForInsert.Team_Leader__c = utilIds.defaultTaskAssignedTo;
        newContactForInsert.AccountId = newAccountForInsert.id;
        newContactForInsert.Intake_Case__c = newCaseInfo.id;
        newContactForInsert.Referral_Date__c = date.today();
        newContactForInsert.RecordTypeId = utilIds.conDTC;
        insert newContactForInsert;

       PPforInsert = new Program_Plan__c();
       PPforInsert.client_name__c = newContactForInsert.id; 
       insert PPforInsert;
       
       PPforInsert1 = new Program_Plan__c();
       PPforInsert1.client_name__c = newContactForInsert.id; 
       insert PPforInsert1;


       dsmcodes = new  DSM4_code__c();
       dsmcodes.description__c = 'descr1';
       dsmcodes.name = '(111) descr1';
       insert dsmcodes;
 
       
       newDiagnosisForInsert = new Client_Diagnosis__c();
       newDiagnosisForInsert.contact__c = newContactForInsert.id;
       newDiagnosisForInsert.Account__c = newContactForInsert.AccountId;
       newDiagnosisForInsert.Program_Plan__c = PPforInsert.id;
       newDiagnosisForInsert.Type__c = 'Jail';
       newDiagnosisForInsert.description__c = dsmcodes.name;
       insert newDiagnosisForInsert;
       
       newDiagnosisForInsert = new Client_Diagnosis__c();
       newDiagnosisForInsert.contact__c = newContactForInsert.id;
       newDiagnosisForInsert.Account__c = newContactForInsert.AccountId;
       newDiagnosisForInsert.Program_Plan__c = PPforInsert.id;
       newDiagnosisForInsert.Type__c = 'Current';
       newDiagnosisForInsert.description__c = dsmcodes.name;
       insert newDiagnosisForInsert;
  
  
       dsmcodes = new  DSM4_code__c();
       dsmcodes.description__c = 'descr2';
       dsmcodes.name = '(222) descr1';
       insert dsmcodes;
  
       newDiagnosisForInsert = new Client_Diagnosis__c();
       newDiagnosisForInsert.contact__c = newContactForInsert.id;
       newDiagnosisForInsert.Account__c = newContactForInsert.AccountId;
       newDiagnosisForInsert.Program_Plan__c = PPforInsert.id;
       newDiagnosisForInsert.Type__c = 'Current';
       newDiagnosisForInsert.description__c = dsmcodes.name;
       insert newDiagnosisForInsert;
       
       newDiagnosisForInsert1 = new Client_Diagnosis__c();
       newDiagnosisForInsert1.contact__c = newContactForInsert.id;
       newDiagnosisForInsert1.Account__c = newContactForInsert.AccountId;
       newDiagnosisForInsert.Program_Plan__c = PPforInsert.id;
       newDiagnosisForInsert1.Type__c = 'Jail';
       newDiagnosisForInsert1.description__c = dsmcodes.name;
       insert newDiagnosisForInsert1;
    }
       static testMethod void testDSM4()
      {
           createTestData();
           test.startTest();
           DSM_4_Controller dsm = new DSM_4_Controller(); 
           dsm.progPlanPassed = PPforInsert.id;
           dsm.buildDiagnosisInfo();
           test.stopTest();
     }
        static testMethod void testSave()
      {
           createTestData();
           test.startTest();
           DSM_4_Controller dsm = new DSM_4_Controller(); 
           dsm.progPlanPassed = PPforInsert.id;
           dsm.pl1 = '(222) descr1';
           dsm.pl2 = '(333) descr2)';
           dsm.pl3 = '(333) descr3)';
           dsm.pl4 = '(333) descr3)';
           dsm.pl5 = '(333) descr4)';
           dsm.diagType = 'Jail';
           dsm.clientPassed = rq.progInfo(dsm.progPlanPassed);
           dsm.SaveSelectedDiag();

           dsm.diagType = 'Current';
           dsm.progPlanPassed = PPforInsert1.id;
           dsm.clientPassed = rq.progInfo(dsm.progPlanPassed);
           dsm.SaveSelectedDiag();
           test.stopTest();
     }

        static testMethod void testCODES()
      {
           createTestData();
           test.startTest();
           DSM_4_Controller dsm = new DSM_4_Controller(); 
           dsm.progPlanPassed = PPforInsert.id;
           dsm.id2delete = newDiagnosisForInsert.id;
           dsm.deleteDiag();
           List<SelectOption> lst1 = dsm.CodesItems1;
           List<SelectOption> lst2 = dsm.CodesItems2;
           List<SelectOption> lst3 = dsm.CodesItems3;
           List<SelectOption> lst4 = dsm.CodesItems4;
           List<SelectOption> lst5 = dsm.CodesItems5;
           
           dsm.closePopUp();
           dsm.showPopup();
           test.stopTest();
    
}}