src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address_Information__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Information</relationshipLabel>
        <relationshipName>Secondary_Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Address Information</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Add-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Medication__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Medications</relationshipLabel>
        <relationshipName>Medications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Medication</label>
    <nameField>
        <displayFormat>M-{0}</displayFormat>
        <label>Medication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Plans</relationshipLabel>
        <relationshipName>Program_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Relationships__c.object
<CustomObject>
    <description>Details relationship between warrant | program | client</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Warrant__r.FirstName &amp; &quot; &quot; &amp;  Warrant__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <label>Program Relationships</label>
    <nameField>
        <displayFormat>PR-C{0}</displayFormat>
        <label>Program Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Test</label>
    <nameField>
        <displayFormat>Test-{0000}</displayFormat>
        <label>Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tier Changes</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jobDeleteIncompleteScreenings.cls
global class jobDeleteIncompleteScreenings {
    
    
    global utilityIds utilIds = new utilityIds();
    
    global void deleteIncompleteScreenings(integer intDaysOld) {
        
        list<Id> lstAllAccountIds = new list<Id>();
        set<Id> setIntakeCaseIds = new set<Id>();
        list<Account> lstAccountstoDelete = new list<Account>();
        
        map<Id, Contact> mapContacts = new map<Id, Contact>([select id, AccountId, Intake_Case__c from Contact 
                                     where RecordtypeId in(:utilIds.conDTC, :utilIds.conCCM, 
                                     :utilIds.conBXChoices, :utilIds.conMNChoices) 
                                     and (Not Screening_Stage__c Like '%Complete')
                                     and CreatedDate <= :system.today().addDays(-1*intDaysOld)]);
        
        set<Id> setContactIds = mapContacts.keySet();   
        
        for(Contact c: mapContacts.values()) {
            
            lstAllAccountIds.add(c.AccountId);
            if(c.Intake_Case__c != null) {
                setIntakeCaseIDs.add(c.Intake_Case__c);
            }
        }                
        
        list<Program_Cycle__c> lstCycles = [select id from Program_Cycle__c where Client__c in :setContactIds];
        
        list<Tier__c> lstTiers = [select id from Tier__c where Contact__c in :setContactIds];
        
        list<Test__c> lstTests = [select id from Test__c where Contact__c in :setContactIds];
        
        list<Address_Information__c> lstAddresses = [select id from Address_Information__c where Client__c in :setContactIds];
        
        list<Medication__c> lstMeds = [select id from Medication__c where Contact__c in :setContactIDs];
        
        list<Case_Information__c> lstDockets = [select id from Case_Information__c where Client_Account__c in :setIntakeCaseIds];
        
        list<Event> lstEvents = [select id from Event where whoId in :setContactIds and isRecurrence = false and isDeleted = false];
        
        list<Event> lstRecurringEvents = [select id from Event where whoId in :setContactIds and isRecurrence = true];                
        
        list<Program_Plan__c> lstPPs = [select id from Program_Plan__c where Client_Name__c in :setContactIds];  
        
        list<Program_Relationships__c> lstProgRels = [select id from Program_Relationships__c 
                                                      where Client_Name__c in :setContactIds];
        
        //only delete accounts if there are no other contacts attached                                                                                                            
        for(Account a: [select id, (select id from contacts) from Account where id in :lstAllAccountIds]) {
            
            if(a.Contacts.size() == 1) {
                
                lstAccountstoDelete.add(a);
            }
        }
        
        //dml
        delete lstProgRels; 
        delete lstPPs; 
        delete lstEvents;
        
        for(Event e: lstRecurringEvents) {
                
            delete e;
        }
                
        delete lstDockets;
        delete lstMeds; 
        delete lstAddresses; 
        delete lstTests;
        delete lstTiers;
        delete lstCycles;
        delete mapContacts.values();
        delete lstAccountstoDelete;                                                   
        
    }
}