src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <inlineHelpText>Select the organization to which this  Defense Attorney or Law Guardian belongs or select  &quot;none&quot;.</inlineHelpText>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>18 B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn Defenders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Defenders of Harlem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York County Defenders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens Law Associates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The Bronx Defenders</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Defense_Attorney_Law_Guardian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Defense Attorney/ Law Guardian</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Attorney/ Law Guardian</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Defense Attorney/ Law Guardian)</relationshipLabel>
        <relationshipName>Case_Information2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Judge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Judge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Judge</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Judge)</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSI_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSI Officer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Case_Information1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probation_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Probation Officer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Probation Officer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Probation Officer)</relationshipLabel>
        <relationshipName>Case_Information3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prosecutor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prosecutor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Attorney/ Law Guardian</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Prosecutor)</relationshipLabel>
        <relationshipName>Case_Information4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/attorneyInfoCEPController_UnitTest.cls
@isTest (SeeAllData=true)
private class attorneyInfoCEPController_UnitTest {
  
    static utilityIds utilIds = new utilityIds();
    static Account accountTest = new Account();
    static Account accountAtt = new Account();
   static Account accountJudge = new Account();
    static Case_Information__c caseTest = new Case_Information__c();
    static Contact contactTest = new Contact();
    static Contact contactJudge = new Contact();
    static Contact ContactDefAtt = new Contact();
    static contact Affiliation = new Contact();
    static void createTestData()
  {     
        accountTest = new Account();
        accountTest.name = 'Pavel Bure';
        accountTest.RecordTypeId = utilIds.accClient;
        accountTest.NYSID_Number__c = '90978021U';
        accountTest.DOB__c = Date.newInstance(1970,1,1);
        insert accountTest;

        accountAtt = new Account();
        accountAtt.name = 'Bill Oh';
        accountAtt.RecordTypeId = utilIds.accExternalEntities;
        insert accountAtt;        
        
        accountJudge = new Account();
        accountJudge.name = 'Bill Oh';
        accountJudge.RecordTypeId = utilIds.accExternalEntities;
        insert accountJudge;        



       contactJudge = new Contact();
       contactJudge.RecordTypeId = utilIds.conJudge  ;
       contactJudge.FirstName = 'Bill';
       contactJudge.lastName = 'Oh';
       contactJudge.RecordTypeId = utilIds.conAttorney;
       contactJudge.AccountId = accountJudge.id;
       insert contactJudge;
        
       ContactDefAtt = new Contact();
       ContactDefAtt.FirstName = 'Bill';
       ContactDefAtt.lastName = 'Oh';
       ContactDefAtt.RecordTypeId = utilIds.conAttorney;
       ContactDefAtt.AccountId = accountAtt.id;
       insert ContactDefAtt;
        
        caseTest = new Case_Information__c();
        caseTest.Client_Account__c = accountTest.Id;
        caseTest.RecordTypeId = utilIds.caseInfoCriminalCourt;
        caseTest.Name = '2011BV144590';
        caseTest.Borough__c = 'Bronx';
        caseTest.Defense_Attorney_Law_Guardian__c = ContactDefAtt.id;
        caseTest.Affiliation__c = ContactDefAtt.id;
        caseTest.Prosecutor__c = ContactDefAtt.id; 
        caseTest.Judge__c = ContactJudge.id; 
        caseTest.Probation_Officer__c = ContactDefAtt.id; 
        caseTest.Prosecutor__c = ContactDefAtt.id; 
        caseTest.PSI_Officer__c = ContactDefAtt.id;
        caseTest.Probation_Officer__c = ContactDefAtt.id;
        caseTest.PSI_Officer__c = ContactDefAtt.id;
        insert caseTest;


       ContactTest = new Contact();
       ContactTest.FirstName = 'Pavel';
       ContactTest.lastName = 'Bure';
       ContactTest.Client_Status__c = 'Incomplete Screening';
       ContactTest.PRP_Status__c = 'Successful Exit';
       ContactTest.Case_Coordinator__c = utilIds.defaultTaskAssignedTo;
       ContactTest.Team_Leader__c = utilIds.defaultTaskAssignedTo;
       ContactTest.AccountId = accountTest.id;
       ContactTest.Intake_Case__c = caseTest.id;
       ContactTest.Referral_Date__c = date.newInstance(2011,2,1);
       ContactTest.RecordTypeId = utilIds.conDTC; 
       insert ContactTest;
  
  }
     static testMethod void test_1()
      {
        createTestData();
 
           test.startTest();
          attorneyInfoCEPController att = new attorneyInfoCEPController(); 
          att.strCase = caseTest.id;
          att.thisContact = ContactTest; 
          att.thisCase = CaseTest;
          att.thisContact.id = ContactTest.id;
          att.thisCase.id = CaseTest.Id;
          PageReference pr = att.goAttorneyConsent(); 
          pr = att.goPortal();
          test.stopTest();
      }
      static testMethod void test_2() {
        createTestData();
        test.startTest();
        PageReference ref = new PageReference('/apex/allcourtsPage');
        Test.setCurrentPage(ref); 
        test.stopTest();
     }
     
     static testMethod void test_3() {
        createTestData();
         PageReference pageRef = Page.attorneyInfo_CEP;
        pageRef.getParameters().put('case',CaseTest.id);
        pageRef.getParameters().put('contact',ContactTest.id);
        Test.setCurrentPageReference(pageRef);
        attorneyInfoCEPController att = new attorneyInfoCEPController(); 
        test.startTest();
        // att.goPortal();
         att.doNothing();
         att.updateAttorneyInfo();
         test.stopTest();
           }
}