src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Arrest_Date__c</fullName>
        <label>Arrest Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Arrest_Number__c</fullName>
        <label>Arrest #</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Criminal_and_Legal_History__c.object
<CustomObject>
    <description>To record a client&apos;s criminal and legal history</description>
    <label>Criminal and Legal History</label>
    <nameField>
        <displayFormat>CLH-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Criminal and Legal Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Penal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Penal Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Penal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Referral to SRP program, before Candidate status before conversion to Contact record. Equivalent to Lead</description>
    <fields>
        <fullName>Arrest_Date__c</fullName>
        <label>Arrest Date (1)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Arrest_Number__c</fullName>
        <label>Arrest #1</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attorney_Consent__c</fullName>
        <label>Attorney Consent</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Charge_A1__c</fullName>
        <label>Charge A1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_B1__c</fullName>
        <label>Charge B1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_C1__c</fullName>
        <label>Charge C1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_D1__c</fullName>
        <label>Charge D1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Consent_to_Screening__c</fullName>
        <label>Client Consent to Screening</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Docket2__c</fullName>
        <label>Docket #2</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket3__c</fullName>
        <label>Docket #3</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket4__c</fullName>
        <label>Docket #4</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket__c</fullName>
        <label>Docket #1</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firstname__c</fullName>
        <label>Firstname</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lastname__c</fullName>
        <label>Lastname</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NYSID__c</fullName>
        <label>NYSID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/referralExtensionTest.cls
@isTest (seeAllData=true)
private class referralExtensionTest 
{
    static referralExtension refEx;
    static Referral__c referral;
    static Penal_Code__c penalCode;
    static PageReference pageRef;
    static Account accnt;
    static Contact contct;
    static Criminal_and_Legal_History__c legalHist;
    static Case_Information__c caseInfo;
    static Date dob1 = Date.newInstance(1976,11,20);

    private static void init()
    {
        penalCode = new Penal_Code__c();
        penalCode.Name = '100.00';
        penalCode.Degree__c = '5';
        penalCode.Level__c = 'V';
        insert penalCode;
        
        referral = new Referral__c();
        referral.FirstName__c = 'Fname';
        referral.LastName__c = 'Lname';
        referral.DOB__c = dob1;
        referral.NYSID__c = '12345678Z';
        referral.Attorney_Consent__c = 'Yes';
        Referral.Client_Consent_to_Screening__c = 'Yes';
        referral.Docket__c = '2012NY123456';
        referral.Arrest_Date__c = Date.newInstance(2016, 06, 10);
        referral.Arrest_Number__c = 'h143576543';
        referral.Charge_A1__c = penalCode.Id;
        referral.Docket2__c = '2013NY123456';       
        referral.Charge_B1__c = penalCode.Id;
        referral.Docket3__c = '2014NY123456';
        referral.Charge_C1__c = penalCode.Id;
        referral.Docket4__c = '2015NY123456';
        referral.Charge_D1__c = penalCode.Id;       
        insert referral;
        pageRef = Page.srp_referralV2_edit;

        ApexPages.StandardController stdcon = new ApexPages.StandardController(referral);
        refEx = new referralExtension(stdCon);
    }

    static testMethod void testRefExt()
    {
        init();
        Test.startTest();
        pageRef = refEx.reloadPage();
        refEx.ClientConsented();
        Test.stopTest();
    } 


}