src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Administrative_Actions__c.object
<CustomObject>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Administrative_Actions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <label>Approved?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Administrative Action</relationshipLabel>
        <relationshipName>Administrative_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Projected_Exit_Date__c</fullName>
        <formula>Client__r.Current_Projected_Exit_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Projected Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Reason__c</fullName>
        <label>Exit Reason</label>
        <picklist>
            <controllingField>Exit_Type__c</controllingField>
            <picklistValues>
                <fullName>Successfully completed program, without modification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to residential drug treatment on or after projected exit date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred to residential, non drug treatment on or after projected exit date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intake case dismissed or defendant acquitted after trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intake judge relieved participant of supervision (includes early graduation due to imposition of a reduced sentence)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never reported for orientation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped reporting to CEP altogether</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unacceptably sporadic attendance (for counseling and/or program plan activities)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed to follow up on case manager referrals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Committed serious violation of CEP rules and regulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged in on-going criminal activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remanded by intake judge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Violated by Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indicted on rearrest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exited for pending unindicted felony rearrest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exited for multiple rearrests</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed to appear for a court date; bench warrant ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participant seriously incapacitated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participant died</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Void intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer to drug treatment program before projected exit date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer to non-drug treatment program before projected exit date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Exit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exit_Type__c</fullName>
        <label>Exit Type</label>
        <picklist>
            <picklistValues>
                <fullName>(S) Successful Exit/ Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(U) Unsuccessful Exit/ Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(T) Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(Z) Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(V) Void</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Date_Back_in_the_Program__c</fullName>
        <label>First Date Back in the Program</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Projected_Exit_Date__c</fullName>
        <label>New Projected Exit Date</label>
        <type>Date</type>
    </fields>
    <label>Administrative Actions</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>Admin Actions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Administrative Actions</pluralLabel>
    <recordTypes>
        <fullName>Extension</fullName>
        <active>true</active>
        <description>Extension Form for a Client</description>
        <label>Extension</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intake_Date__c</fullName>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client_Class_Status_Field__c</fullName>
        <label>Client Class Status Field</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Client that will be enrolled in a Class</description>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>relContactEnrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dummy_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, create session logic is not run on the schedule. This is used for schedules where the sessions will be added via a nightly process, such as for the DTC Groups.</description>
        <label>Dummy Schedule?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The End Date of this schedule</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/administrativeActionMethodsUnitTests.cls
@isTest (SeeAllData=True)
private class administrativeActionMethodsUnitTests {
    
    static utilityIds utilIds = new utilityIds();
    
    static Account accClient = new Account();
    static Contact con = new Contact();
    static Case_Information__c newCaseInfo =  new Case_Information__c();
    
    private static void establishCoreData(String strClientStatus) {
        
        accClient = new Account(Name='Unit Tester', RecordTypeId = utilIds.accClient);
        insert accClient;
        
        newCaseInfo = new Case_Information__c();
        newCaseInfo.Client_Account__c = accClient.Id;
        newCaseInfo.RecordTypeId = utilIds.caseInfoSupremeCourt;
        newCaseInfo.Name = '2013TN456011';
        newCaseInfo.Borough__c = 'Bronx';
        insert newCaseInfo;        
        
        con = new Contact();
        con.firstName = 'Unit';
        con.lastName = 'Tester';
        con.Drug_test_frequency__c = 'Bi-Weekly';
        con.Referral_Date__c = system.today().addDays(-5);
        con.Eligible__c = 'Yes';
        con.Interview_Acceptance_Date__c = system.today().addDays(-3);
        con.Interview_Outcome__c = 'CEP Accepts';
        con.Intake_Approved_By__c = userInfo.getUserId();
        con.Intake_Date__c = System.Today();
        con.Intake_Case__c = newCaseInfo.id;
        con.RecordTypeId = utilIds.conClient;
        con.Case_Coordinator__c = UserInfo.getUserId();
        con.accountId = accClient.id;       
        
        insert con;
        

        Event thisEvent = new Event();
        thisEvent.RecordTypeId = utilIds.orientationAppointment;
        thisEvent.whoId = con.Id;
        thisEvent.DurationInMinutes = 60;
        thisEvent.ActivityDate = System.Today();
        thisEvent.ActivityDateTime = System.now();
        thisEvent.Verification_Status__c = 'Attended';
        insert thisEvent;                                  
        
        if(strClientStatus == 'Exited') {
            
            doExitNotification();       
        }
        
    }
    
    private static void doExitNotification() {
            
        Administrative_Actions__c aaExit = new Administrative_Actions__c();
        aaExit.Client__c = con.id;
        aaExit.RecordTypeId = utilIds.aaExitNotification;
        aaExit.Action_Date__c = System.Today();
        aaExit.Exit_Type__c = '(S) Successful Exit/ Graduation';
        aaExit.Exit_Reason__c = 'Successfully completed program, without modification';
        
        insert aaExit;
        
        aaExit.Approved__c = 'Yes';
        aaExit.Approved_By__c = UserInfo.getUserId();
        
        update aaExit;
        
        //delete aaExit;
        
    }
    
    private static void doExitNotificationUnsuccessful() {
            
        Administrative_Actions__c aaExit = new Administrative_Actions__c();
        aaExit.Client__c = con.id;
        aaExit.RecordTypeId = utilIds.aaExitNotification;
        aaExit.Action_Date__c = System.Today();
        aaExit.Exit_Type__c = '(U) Unsuccessful Exit/ Discharge';
        aaExit.Exit_Reason__c = 'Never reported for orientation';
        
        insert aaExit;
        
        aaExit.Approved__c = 'Yes';
        aaExit.Approved_By__c = UserInfo.getUserId();
        
        update aaExit;
        
    }

    private static Task createExitDrugTask() {
        
        Task tsk = new Task();
        tsk.whoId = con.id;
        tsk.ActivityDate = System.Today().addDays(-1);
        tsk.RecordTypeId = utilIds.exitDrugTestTask;
        tsk.SkipRestrictions__c = true;
        tsk.Automatically_Generated__c = true;
        insert tsk;
        
        return tsk;
        
    }

    ///////////////////////////////////
    // Test Methods
    ///////////////////////////////////
    
    static testMethod void testAdministrativeActionUnsuccessfulExit() {
        
        // Setup core data
        establishCoreData('Active');
        
        test.startTest();
        
        // Do Exit Notification
        doExitNotificationUnsuccessful();
        
        test.stopTest();
        
    }




    static testMethod void testAdministrativeActionReintake() {
        
        // Setup core data
        establishCoreData('Exited');
        
        test.startTest();       
        // Do Reinstake Notification
        Administrative_Actions__c aaReintake = new Administrative_Actions__c();
        aaReintake.Client__c = con.id;
        aaReintake.RecordTypeId = utilIds.aaReintake;
        aaReintake.Action_Date__c = System.Today();
        aaReintake.New_Projected_Exit_Date__c = System.Today().addDays(15);
        insert aaReintake;

        
        aaReintake.Approved__c = 'Yes';
        update aaReintake;
  
        Test.stopTest();        
    }


    static testMethod void testAdministrativeActionReinstatement() {
        
        // Setup core data
        establishCoreData('Exited');
        
        test.startTest();
        
        // Do Re-instatement Notification
        Administrative_Actions__c aaExt = new Administrative_Actions__c();
        aaExt.Client__c = con.id;
        aaExt.RecordTypeId = utilIds.aaReinstatement;
        aaExt.Action_Date__c = system.today();
        aaExt.First_Date_Back_in_the_Program__c  = System.Today();
        aaExt.New_Projected_Exit_Date__c = System.Today().addDays(15);
        aaExt.Approved__c = 'No';
        aaExt.Exit_Type__c = '(S) Successful Exit/ Graduation';
        insert aaExt;
  
        aaExt.Approved__c = 'Yes';         
        update aaExt;
  
        Test.stopTest();
        
    }
    
    static testMethod void testAdministrativeActionExtension() {
        
        // Setup core data
        establishCoreData('Active');
        
        //before exit
        Task exitDrugTestTask = new Task();
        exitDrugTestTask.whoId = con.id;
        exitDrugTestTask.ActivityDate = System.Today().addDays(-5);
        exitDrugTestTask.RecordTypeId = utilIds.exitDrugTestTask;
        //this line added by MB 9/17/12 because this task can no longer be manually generated 
        exitDrugTestTask.Automatically_Generated__c = true;
        exitDrugTestTask.Status = 'Done on Time';
        exitDrugTestTask.Closing_Date__c = System.Today().addDays(-5);
        
        //after exit
        Task exitDrugTestTask2 = new Task();
        exitDrugTestTask2.whoId = con.id;
        exitDrugTestTask2.ActivityDate = System.Today().addDays(16);
        exitDrugTestTask2.RecordTypeId = utilIds.exitDrugTestTask;
        //this line added by MB 9/17/12 because this task can no longer be manually generated 
        exitDrugTestTask2.Automatically_Generated__c = true;
        exitDrugTestTask2.Status = 'Done on Time';
        exitDrugTestTask2.Closing_Date__c = System.Today().addDays(16);
        insert new Task[] {exitDrugTestTask, exitDrugTestTask2};  
        
        //delete all enrollments to avoid going over sql limits when classEnrollment is run many times
        List<Enrollment__c> lstEnrollments = [select id from enrollment__c where client__c = :con.id];     
        delete lstEnrollments;
        
        Schedule__c sched = [select id, class__c from Schedule__c where recordtypeid != :utilIds.scheduleSingle
                             and Dummy_Schedule__c != true order by end_date__c desc limit 1 ];
                                          
        
        // Create enrollment
        Enrollment__c enr = new Enrollment__c();
        enr.Client__c = con.id;    
        enr.Class__c = sched.class__c;
        enr.Client_Class_Status_Field__c = 'Active';
        insert enr;
                                
        test.startTest();
                
        // Extension
        Administrative_Actions__c aaExt = new Administrative_Actions__c();
        aaExt.Client__c = con.id;
        aaExt.RecordTypeId = utilIds.aaExtension;
        aaExt.Action_Date__c = system.today();
        aaExt.New_Projected_Exit_Date__c = System.Today().addDays(180);
        aaExt.Approved__c = 'No';
        insert aaExt;
  
        aaExt.Approved__c = 'Yes';
        
    //    update aaExt;
        
        test.Stoptest();
        
        Contact c = [select id, Current_Projected_Exit_Date__c from Contact where id = :aaExt.Client__c limit 1];
        
        system.assertEquals(c.Current_Projected_Exit_Date__c, aaExt.New_Projected_Exit_Date__c);
    }
}