src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CIRT_Download__c.object
<CustomObject>
    <fields>
        <fullName>Client_Consent__c</fullName>
        <label>Client Consent</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DOCKET__c</fullName>
        <label>DOCKET</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Firstname__c</fullName>
        <label>Firstname</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lastname__c</fullName>
        <label>Lastname</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NYSID__c</fullName>
        <label>NYSID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>CIRT Download</label>
    <nameField>
        <displayFormat>CIRT-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIRT Downloads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/cirtNonDocExtensionTest.cls
@isTest (seeAllData=true)
private class cirtNonDocExtensionTest 
{
    static cirtNonDocExtension cnd;
    static CIRT_Download__c cirtDownload;
    static PageReference pageRef;
    static Account accnt;
    static Contact contct;
    static Case_Information__c caseInfo;
    static Date dob1 = Date.newInstance(1976,11,20);

    private static void init()
    {
        cirtDownload = new CIRT_Download__c();
        cirtDownload.FirstName__c = 'Fname';
        cirtDownload.LastName__c = 'Lname';
        cirtDownload.DOB__c = dob1;
        cirtDownload.NYSID__c = '12345678Z';
        cirtDownload.Client_Consent__c = 'Yes';
        cirtDownload.Docket__c = '2012NY123456';
     

      
        insert cirtDownload;
        pageRef = Page.CIRTnonDOC;

        ApexPages.StandardController stdcon = new ApexPages.StandardController(cirtDownload);
        cnd = new cirtNonDocExtension(stdCon);
    }

    static testMethod void testRefExt()
    {
        init();
        Test.startTest();
        cnd.ClientConsented();
        Test.stopTest();
    } 


}