src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Charges__c.object
<CustomObject>
    <description>To enter all charges for a case - arrest, plea, indictment and court related</description>
    <fields>
        <fullName>Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Charge</label>
        <referenceTo>Penal_Code__c</referenceTo>
        <relationshipLabel>Case Charges (Arrest Charge)</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Docket_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Docket #</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Charges</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Arrest Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indictment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plea/ Finding Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Charges</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Case Charges ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Arrest_Date__c</fullName>
        <label>Arrest Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Arrest_Number__c</fullName>
        <label>Arrest #</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Defense_Attorney_Law_Guardian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Defense Attorney/ Law Guardian</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Attorney/ Law Guardian</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Defense Attorney/ Law Guardian)</relationshipLabel>
        <relationshipName>Case_Information2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Detention_Status_at_SC_Arraignment__c</fullName>
        <label>Detention Status at SC Arraignment</label>
        <picklist>
            <picklistValues>
                <fullName>ROR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Made Bail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In On Bail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Indictment__c</fullName>
        <inlineHelpText>Two format:s are permitted  
  12345-2006   and  
  SCI12345-YYYY   where YYYY is the year</inlineHelpText>
        <label>Indictment #</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Penal_Code__c.object
<CustomObject>
    <label>Penal Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Penal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/legalHistoryController_UnitTest.cls
@isTest (SeeAllData=true)
public class legalHistoryController_UnitTest {

    static Case_Information__c caseTest = new Case_Information__c();
    static Case_Information__c caseTest1 = new Case_Information__c();
    static Event eventTest = new Event();
    static Contact contactTest = new Contact();
    static Case_Charges__c chgTest = new Case_Charges__c();
    static Account accountTest = new Account();
    
    static Id suprRecTypeId = Utility_ID__c.getValues('Case - Supreme Court').RecordType_Id__c;
    static Id EventRecTypeId = Utility_ID__c.getValues('Court Date').RecordType_Id__c;
    static Id conCRT = Utility_ID__c.getValues('CIRT Client').RecordType_Id__c;  
    static Id accClient = Utility_Id__c.getValues('Client').RecordType_Id__c;
    
    static void createTestData() {
    
        date ddate =  date.parse('11/11/2013');
        date ddate1 =  date.parse('03/11/2014');
        date manddate = date.parse('04/01/2014');
        User adminUser = [Select Id from User Where isActive = true and Profile.Name = 'System Administrator' Limit 1];
    
        accountTest = new Account();
        accountTest.nysid_number__c = '04221673Y';  
        accountTest.Name = 'CIRT';
        accounttest.DOB__c = date.parse('11/11/1950');
        accountTest.recordtypeId =  accClient;
        insert accountTest;

        casetest.Client_Account__c = accountTest.id;
        caseTest.Name = '2014NY023083';
        caseTest.Borough__c = 'Bronx';
        caseTest.Indictment__c = 'indictment';
        caseTest.Detention_Status_at_SC_Arraignment__c = 'ROR';
        caseTest.RecordTypeId = suprRecTypeId;
        caseTest.Arrest_Date__c = date.today();
        caseTest.Arrest_Number__c = '11114444';
        caseTest.Defense_Attorney_Law_Guardian__c = contactTest.id;
        insert caseTest;

        ID Accountid = accountTest.id; 
        contactTest = new Contact();
        contactTest.accountId = accountTest.id;
        contactTest.lastName = 'Lasttest';
        contactTest.firstName = 'firsttest';
        contactTest.recordtypeid = conCRT; 
        contactTest.Client_Status__c = 'Active';
        contactTest.Criminal_Justice_Involvement__c = 'Probation';
        contactTest.Mandate_Decision_Date__c = manddate;
        contactTest.aka_1__c = 'aka1';
        contactTest.aka_2__c = 'aka2';
        contactTest.aka_3__c = 'aka3';
        contactTest.Resource_Coordinator_s_Comments__c = 'comments';
        contactTest.Criminal_Justice_Involvement__c = 'Parole';
        contactTest.Prior_Violent_Conviction_Date__c = date.today() -100;
        contactTest.Prior_Violent_Conviction__c = 'Yes'; 
        contactTest.Inmate_Location__c = 'brooklyn';
        contactTest.Prior_Felony_Convictions__c = 5;
        contactTest.Prior_Misdemeanor_Convictions__c = 2;
        contactTest.Interview_Notes__c = 'int notes';    
        contactTest.Intake_Case__c = caseTest.id;    
        insert contactTest;
    
        casetest1.Client_Account__c = accountTest.id;
        caseTest1.Name = '2010NY023075';
        caseTest1.Borough__c = 'Bronx';
        caseTest1.Indictment__c = 'indictment1';
        caseTest1.Arrest_Date__c = date.today() - 10;
        caseTest1.Arrest_Number__c = '11113666';
        caseTest1.RecordTypeId = suprRecTypeId;
        insert caseTest1;

        List<Event> lstEvents = new List<Event>();
        eventTest = new Event();
        eventTest.recordTypeId = EventRecTypeId;
        eventTest.whoid = contactTest.id;
        eventTest.whatid = casetest.id;
        datetime dtime =  datetime.parse('11/11/2013 12:00 AM');
        eventTest.ActivityDateTime = dtime;
        eventTest.ActivityDate = ddate;
        eventTest.DurationInMinutes = 30;
        eventTest.verification_status__c = 'Not Verified';
        lstEvents.add(eventTest);
 
        eventTest.recordTypeId = EventRecTypeId;
        eventTest.whoid = contactTest.id;
        eventTest.whatid = casetest.id;
        datetime dtime1 =  datetime.parse('05/11/2014 12:00 AM');
        eventTest.ActivityDateTime = dtime1;
        eventTest.ActivityDate = ddate1;
        eventTest.DurationInMinutes = 30;
        eventTest.verification_status__c = 'Not Verified';
        lstEvents.add(eventTest);
 
        chgTest.Docket_No__c = caseTest.id;
        chgTest.Type__c = 'Arrest Charges';
        
        Case_Charges__c chg1 = new Case_Charges__c();
        for (Penal_Code__c lstcodes : [select id from Penal_Code__c Limit 1 ]) {

          chgTest.Charge__c = lstcodes.id;
        }
        
        insert chgTest; 
     }
 
    static testMethod void test1(){
    
        createTestData();
        PageReference pageRef = Page.legalHistory;
        Test.setCurrentPage(pageRef);
        legalHistoryController lc = new legalHistoryController();        
        ApexPages.currentPage().getParameters().put('case',caseTest.id);
        ApexPages.currentPage().getParameters().put('contact',contactTest.id);
         
        lc = new legalHistoryController(); 
        
        test.starttest();
        pageReference pg = lc.saveLegalInfo();
        test.stoptest();
    }
    
}