src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address_Information__c.object
<CustomObject>
    <label>Address Information</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Add-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Charges__c.object
<CustomObject>
    <description>To enter all charges for a case - arrest, plea, indictment and court related</description>
    <fields>
        <fullName>Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Charge</label>
        <referenceTo>Penal_Code__c</referenceTo>
        <relationshipLabel>Case Charges (Arrest Charge)</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Docket_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Docket #</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Charges</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Arrest Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indictment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plea/ Finding Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Charges</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Case Charges ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intake_Date__c</fullName>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Judge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Judge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Judge</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Judge)</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Contact__r.Name_and_P_C_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <label>Case Relationship</label>
    <nameField>
        <displayFormat>CR-{0}</displayFormat>
        <label>Case Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Holidays__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Holidays</label>
    <nameField>
        <label>Holiday Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Penal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Numeric_Charge_Value__c</fullName>
        <inlineHelpText>Please enter the numeric portion of the charge value. Ex. &quot;VTL 1192-1&quot; would equal 1192.1   You can enter up to three decimal places.</inlineHelpText>
        <label>Numeric Charge Value</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Penal Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Penal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Plans</relationshipLabel>
        <relationshipName>Program_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>P_C_ID__c</fullName>
        <description>get P/C ID from contact</description>
        <formula>Client_Name__r.P_C_ID__c</formula>
        <label>P/C ID</label>
        <type>Text</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/reportQueryUnitTest.cls
@isTest (seeAlldata = true)
private class reportQueryUnitTest 
{
    static Id accClient = Utility_ID__c.getValues('CEP Client').RecordType_Id__c;

    static utilityIds utilIds = new utilityIds();
    static Case_Information__c newCaseInfo = new Case_Information__c();
    static Event evt1 = new Event();    
    static Event evt2 = new Event();    
    static Event evt3 = new Event(); 
    static Event eventTest = new Event();
    static Contact con1 = new Contact();
    static Contact newJudge = new Contact();
    static Case_Charges__c chgTest = new Case_Charges__c();
    static Program_Plan__c PPforInsert = new Program_Plan__c();
    static Penal_Code__c ppcode = new Penal_Code__c();
    static Account newAccountForInsert = new Account();
    static Account newAccountForJudge = new Account();
    static Address_Information__c addressTest = new Address_Information__c(); 
    static Id caseRecTypeId = Utility_ID__c.getValues('Case - Criminal Court').RecordType_Id__c;
    static Id EventRecTypeId = Utility_ID__c.getValues('Court Date').RecordType_Id__c;
    static Id conCRT = Utility_ID__c.getValues('CIRT Client').RecordType_Id__c; 
    static Id judge  =  Utility_ID__c.getValues('Judge').RecordType_Id__c; 
    static Id caseid,progid,accountid,casetype,clientid,docket; 
    static string clientString,Supervision,IntakeNeedsAssessment,courtRecType,pcid,username,caseString; 
    static void createTestData()
    {  
    	username = userInfo.getUserId(); userInfo.getUserId(); 
    	List<RecordType> lstRecType = [Select id,developername,name from RecordType
         where developername =: 'Court_Ordered_Supervision' or 
         developername =: 'Intake_Needs_Assessment' or developername =: 'CourtDate'];
      for (integer i = 0;i < lstRecType.Size();i++){
         if (lstRecType[i].developername == 'Court_Ordered_Supervision')
            Supervision = lstRecType[i].id;
         if (lstRecType[i].developername == 'Intake_Needs_Assessment')
            IntakeNeedsAssessment = lstRecType[i].id; 
         if (lstRecType[i].developername == 'CourtDate')
            courtRecType = lstRecType[i].id;     
      }          
        newAccountForInsert = new Account();
        newAccountForInsert.name = 'Dusty Bottoms';
        newAccountForInsert.RecordTypeId = '012600000005Nk2AAE';
        newAccountForInsert.NYSID_Number__c = '90978021U';
        newAccountForInsert.DOB__c = Date.newInstance(1970,1,1);
        insert newAccountForInsert;
        accountid = newAccountForInsert.id; 
            
        newAccountForJudge = new Account();
        newAccountForJudge.name = 'Judge Dredd';
        newAccountForJudge.RecordTypeId = '012600000004yhRAAQ';
        insert newAccountForJudge;
        
        newJudge = new Contact();
        newJudge.AccountId = newAccountForJudge.id;            
        newJudge.FirstName = 'judgeFirst';
        newJudge.lastName = 'JudgeLast';
        newJudge.RecordTypeId = '012600000004zCFAAY'; 
        insert newJudge;            
            
        newCaseInfo = new Case_Information__c();
        newCaseInfo.Client_Account__c = newAccountforInsert.Id;
        newCaseInfo.RecordTypeId = utilIds.caseInfoSupremeCourt;   
        newCaseInfo.Name = '2011BV144590';
        newCaseInfo.Borough__c = 'Bronx';
        newCaseInfo.judge__c = newjudge.id;
        insert newCaseInfo;  
        caseid = newCaseInfo.id;
    //    docket = newCaseInfo.Name;       
                  
         
     
        con1 = new Contact();
        con1.FirstName = 'Dusty';
        con1.lastName = 'Bottoms';
        con1.Client_Status__c = 'Active';  
        con1.Referral_Date__c = date.today().addDays(-20);
        con1.Current_Intake_Date__c = date.today().addDays(-20);
        con1.Intake_Date__c = date.today().addDays(-20);
        con1.RecordTypeId = utilIds.conClient;
        con1.Reporting_Borough__c = 'Brooklyn';   
        con1.Intake_Approved_By__c = userInfo.getUserId();  
        con1.Interview_Outcome__c = 'CEP Accepts';
        con1.AccountId = newAccountForInsert.id;
        con1.Intake_Case__c = caseString;
        con1.RecordTypeId = accClient; 
        insert con1;
        clientid = con1.id;
        pcid = con1.P_C_ID__c;
        clientString = con1.id;
        ppcode = new Penal_Code__c();
        ppcode.name = '325.25';
        ppcode.Numeric_Charge_Value__c = 325.25;
        ppcode.Level__c = 'F';
        ppcode.Degree__c = '1';
        ppcode.class__c = '1';
        insert ppcode;
        
        PPforInsert = new Program_Plan__c();
        PPforInsert.client_name__c = con1.id; 
        insert PPforInsert;        
        progid = PPforInsert.id;
        
        chgTest = new Case_Charges__c();
        chgTest.Docket_No__c = newCaseInfo.id;
        chgTest.Charge__c = ppcode.id;
        chgTest.Type__c = 'Criminal Court Arraignment Charges';
        insert chgTest;
 
 
        evt1 = new Event();
        evt1.ActivityDateTime = System.Now().addHours(-48);
        evt1.ActivityDate = date.today().addDays(-2);
        evt1.DurationInMinutes = 30;
        evt1.WhoId = clientid;
        evt1.WhatId = caseid;
        evt1.Subject = 'Call';
        evt1.DurationInMinutes = 30;
        evt1.Verification_Status__c = 'Unexused';
        evt1.RecordTypeId = Supervision;        
        evt1.P_C_ID__c = pcid;
        evt1.Verified_By__c = userName; 
        evt1.Verification_Date__c = date.today();
        insert evt1;
 
        evt2 = new Event();
        evt2.ActivityDateTime = System.Now().addHours(48);
        evt2.ActivityDate = date.today().addDays(2);
        evt2.DurationInMinutes = 30;
        evt2.WhoId = clientid;
        evt2.WhatId = caseid;
        evt2.Subject = 'Court Date';
        evt2.DurationInMinutes = 30;
        evt2.Verification_Status__c = 'Unexused';
        evt2.RecordTypeId = courtRecType;        
        evt2.P_C_ID__c = pcid;
        evt2.Verified_By__c = userName; 
        evt2.Verification_Date__c = date.today();
        insert evt2;
    }
   
    static testMethod void testReportQuery()
    {
        createTestData();
        reportQuery rq = new reportQuery();
        test.startTest();
        Map<Id, Contact> mapContact = rq.contactQuery(con1.id);
        Map<Id, Contact> mapContact1 = rq.contactQueryByStringId(clientString);
        Map<Id, Contact> mapCaseContact = rq.contactQueryContCase(con1.id,con1.Intake_Case__c);
        Map<Id, Account> mapCasecount = rq.accountQuery(newAccountForInsert.id);
        List<Case_Information__c> lstCase = rq.caseInfoQuery(con1.id);
     //   List<Event> lstEvent = rq.eventQuery(caseid);
       Map<id,Case_Information__c> mapCase = rq.caseQuery(caseid);
        Map<id,Program_Plan__c> mapProg = rq.PP_Query(progId);
        List<Address_Information__c> lstAddress = rq.addressQuery(con1.id);
        List<Contact> lstContactByAct = rq.listContactByAccountId(newAccountForInsert.id);
        string chg = rq.Charges(caseid, 'Criminal Court Arraignment Charges');
        string chgDescr = rq.ChargesDescription(caseid, 'Criminal Court Arraignment Charges');
        string m = rq.mostResentChargesType(caseid);
        string caseJudge = rq.mapNames(newCaseInfo.judge__c);
        string att = rq.attInfo(newCaseInfo.id);
  /*
        date d = date.today();
         Map<Date, ID> mapHolidays = new Map<Date, ID>();
         List<Holidays__c>lstHolidays = [SELECT Id, Date__c FROM Holidays__c];
        for(Holidays__c h: lstHolidays) {
            mapHolidays.put(h.Date__c, h.Id);}
            date dt = rq.countDueDate_1(mapHolidays,d, 10);
            date dt1 = rq.countDueDateBefore_1(mapHolidays,d, 10);
  
            date d2 = rq.countDueDateBefore(d, 10);
            date dt3 = rq.countDueDate(d, 10);

            string appSubject = 'Court Date';
            date dStart = date.today().addDays(-3);
            date dEnd = date.today().addDays(10);
            List<Event> e = rq.appointments(dstart, dend, clientid, appSubject);
            List<Case_Information__c> ci = rq.caseInfoQueryByCaseId(accountId, caseid);  
            string casename = rq.caseName(newCaseInfo.Id);             
  
          ID userId = userInfo.getUserId();
        rq.userNamesById(userId);
        string cId = string.ValueOf(userId);
        rq.userNames(userId);
        rq.findUserName(userId);
        rq.contactQueryByStringId(clientId);    
        */        
        test.stopTest();
     }
     
   static testMethod void testReportQuery_1()
    {
        createTestData();
        reportQuery rq = new reportQuery();
        test.startTest();
        List<Event> lstEvent = rq.eventQuery(caseid);
        ID userId = userInfo.getUserId();
        rq.userNamesById(userId);
        string cId = string.ValueOf(userId);
        rq.userNames(userId);
        rq.findUserName(userId);
        rq.contactQueryByStringId(clientId);   
  date d = date.today();
         Map<Date, ID> mapHolidays = new Map<Date, ID>();
         List<Holidays__c>lstHolidays = [SELECT Id, Date__c FROM Holidays__c];
        for(Holidays__c h: lstHolidays) {
            mapHolidays.put(h.Date__c, h.Id);}
            date dt = rq.countDueDate_1(mapHolidays,d, 10);
            date dt1 = rq.countDueDateBefore_1(mapHolidays,d, 10);
  
            date d2 = rq.countDueDateBefore(d, 10);
            date dt3 = rq.countDueDate(d, 10);

            string appSubject = 'Court Date';
            date dStart = date.today().addDays(-3);
            date dEnd = date.today().addDays(10);
            List<Event> e = rq.appointments(dstart, dend, clientid, appSubject);
            List<Case_Information__c> ci = rq.caseInfoQueryByCaseId(accountId, caseid);  
            string casename = rq.caseName(newCaseInfo.Id);                  
        test.stopTest();
     }

     static testMethod void testCharges()
     {  
         reportQuery rq = new reportQuery();
         test.startTest();
         chgTest.Docket_No__c = newCaseInfo.id; 
         Id pcodeId;
         for (Penal_Code__c lstcodes : [select id from Penal_Code__c Limit 1 ])
         {
             pcodeId = lstcodes.id;
         }
         string cname = rq.mapCodes(pcodeId);
         test.stopTest();
     } 

     static testMethod void testProgInfo()
     {
         reportQuery rq = new reportQuery();
         test.startTest();
         progId = rq.progInfo(newCaseInfo.Id);
         string checkName = 'Docket';
         string checkValue = '2011BV144590';
         boolean retcheck = rq.checkformat(checkName,checkValue);
         string dow = rq.dayOfWeek(date.today());
         List<Case_Relationship__c> cr = rq.findClient(checkName,checkValue,'','');
         test.stopTest();
     }
}