src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mandatory_Sessions_Required__c</fullName>
        <label>Mandated Days/Sessions</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/STRT_ProgramRepController_UT.cls
@isTest
(seeAllData=true)
public class STRT_ProgramRepController_UT
{
    static Id acct_client = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
    static Id dtc_client = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('DTC Client').getRecordTypeId();
    static Id dtc_progCycle = Schema.SObjectType.Program_Cycle__c.getRecordTypeInfosByName().get('DTC Program Cycle').getRecordTypeId();
    static Id caseCoordination = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Case Coordination').getRecordTypeId();

    static testMethod void STRT_ProgramRepController_UT()
    {
        Account clientAccount = new Account(
                Name = 'DTC Test',
                NYSID_Number__c = '43215678A',
                RecordTypeId = acct_client);
        insert clientAccount;
        
        Contact conDTC = new Contact(
                AccountId = clientAccount.Id,
                FirstName = 'DTC',
                LastName = 'TEST',
                RecordTypeId = dtc_client,
                Client_Status__c = 'Active');
        insert conDTC;
        
        Program_Cycle__c progCycle = new Program_Cycle__c(
                Client__c = conDTC.Id,
                RecordTypeId = dtc_progCycle,
                Start_Date__c = Date.Today() - 5,
                Mandatory_Sessions_Required__c = 5);
        insert progCycle;
                
        PageReference pageRef = Page.STRTProgramReporting;
        Test.setCurrentPage(pageRef);
        STRT_ProgramRepController controller = new STRT_ProgramRepController();
        controller.selectedDate = Date.Today()-1;
        controller.proxyObject.ActivityDate = Date.Today()-1;
        controller.getDateDOW();
        controller.getStatusItems();
        controller.selectProgs = 'DTC';
        controller.buildContacts();
        controller.doNothing();
        controller.appstatus = 'Attended';
        controller.contId = conDTC.Id;
        controller.createApp();
//        controller.setMandatorySessionsCounter();
        controller.getGroupsItems();
        controller.createGroupAtt();
    }
}