src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intake Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Relationships</relationshipLabel>
        <relationshipName>Case_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Docket__c</fullName>
        <label>Docket</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Relationship</label>
    <nameField>
        <displayFormat>CR-{0}</displayFormat>
        <label>Case Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cycle_Type__c</fullName>
        <label>Cycle Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstatement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Tier</label>
        <referenceTo>Tier__c</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tier Changes</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Most Recent Tier?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/srp_ExitClientConExtTest.cls
@isTest(seeAllData=true)
private class srp_ExitClientConExtTest 
{

    Private Static testmethod void srp_ExitClientConExtTest()
    {    
        Date referDate1 = Date.newInstance(2006,11,20);

        Account account = new Account();
        account.Name = 'Fname Lname';
        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        insert account;

        Case_Information__c caseInfo = new Case_Information__c();
        caseInfo.Name = '2000QN234567';
        caseInfo.RecordTypeId = Schema.SObjectType.Case_Information__c.getRecordTypeInfosByName().get('Criminal Court').getRecordTypeId();
        caseInfo.Client_Account__c = account.id;
        insert caseInfo;
                
        Contact contact = new Contact();
        contact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('SRP Client').getRecordTypeId();
        contact.FirstName = 'Test Fname';
        contact.LastName = 'Test Lname';
        contact.Screening_Outcome_srp__c = 'Eligible';
        contact.Arraignment_Outcome__c = 'Released into Supervised Release';        
        contact.AccountId = account.id;
        contact.Intake_Case__c = caseInfo.Id;
        insert contact;
       
        Case_Relationship__c caseRel = new Case_Relationship__c();
        caseRel.Docket__c = CaseInfo.Id;
        caseRel.Case_Type__c = 'Intake';
        caseRel.Contact__c = contact.id;
        insert caseRel;

        Program_Cycle__c progCycle = new Program_Cycle__c();
        progCycle.Client__c = contact.id;
        progCycle.Cycle_Type__c = 'Intake';
        progCycle.Start_Date__c = Date.parse('09/15/2016');
        progCycle.End_Date__c = Date.parse('10/15/2016');
        progCycle.RecordTypeId = Schema.SObjectType.Program_Cycle__c.getRecordTypeInfosByName().get('SRP Program Cycle').getRecordTypeId();
        insert progCycle;

        contact.Most_Recent_Program_Cycle__c = progCycle.Id;
        contact.Intake_Case__c = caseInfo.Id;
        update contact;
        
        Tier__c tier = new Tier__c();
        tier.Start_Date__c = Date.Today();
        tier.Most_Recent_Tier__c = True;
        tier.Program_Cycle__c = progCycle.Id;
        insert tier;            
        
        PageReference pageRef = Page.SRP_Exit_Client;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('Id', contact.Id);
        srp_ExitClientConExt controller = new srp_ExitClientConExt();
        controller.saveThis();         
    
    }
    
}