src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address_Information__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Former Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Information</relationshipLabel>
        <relationshipName>Secondary_Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zip Code</label>
        <referenceTo>Zip_Code_Mapping__c</referenceTo>
        <relationshipLabel>Address Information</relationshipLabel>
        <relationshipName>Address_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address Information</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Add-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SR_Intake_Needs_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Former Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Highest_Level_of_Education__c</fullName>
        <label>Highest Level of Education</label>
        <picklist>
            <picklistValues>
                <fullName>No schooling completed, or less than 1 year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursery, Kindergarten and Elementary (Grades 1-8)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School (Grades 9-12, no degree)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School graduate or equivalent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Some college (1-4 years, no degree)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associate&apos;s Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelor&apos;s Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master&apos;s Degree (MA, MS, MENG, MSW, etc.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional School degree (MD, DDC, JD, etc.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctorate degree (PhD, EdD, etc.)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level_of_Social_Support__c</fullName>
        <description>How is your level of social support right now</description>
        <label>Level of social support</label>
        <picklist>
            <picklistValues>
                <fullName>I have the social support I need</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I wish I had more social support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I don&apos;t have any social support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Specific assessments have two master-detail relationships (Assessment and Contact)</description>
        <label>Participant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SR Intake Needs Assessments</relationshipLabel>
        <relationshipName>SR_Intake_Needs_Assessments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>SR Intake Needs Assessment</label>
    <nameField>
        <displayFormat>SR-NA{0000}</displayFormat>
        <label>SR Intake Needs Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Intake Needs Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SrNeedsAssessExt.cls
public class SrNeedsAssessExt
{

    public Address_Information__c addressInfo {get;set;}
    public String contactID {get; set;}
    public String contactName {get; set;}
    public Id assBJMHSRecTypeId = Schema.SObjectType.Assessment__c.getRecordTypeInfosByName().get('BJMHS').getRecordTypeId();
    public Id assPHQ9RecTypeId = Schema.SObjectType.Assessment__c.getRecordTypeInfosByName().get('PHQ-9').getRecordTypeId();
    public Id assPHQ9RORecTypeId = Schema.SObjectType.Assessment__c.getRecordTypeInfosByName().get('PHQ-9 - Read Only').getRecordTypeId();
    public Id assPHQ9TRecTypeId = Schema.SObjectType.Assessment__c.getRecordTypeInfosByName().get('PHQ-9 Teen').getRecordTypeId();
    public Id assTCURecTypeId = Schema.SObjectType.Assessment__c.getRecordTypeInfosByName().get('TCU').getRecordTypeId();
    public Id assCRAFFTRecTypeId = Schema.SObjectType.Assessment__c.getRecordTypeInfosByName().get('CRAFFT').getRecordTypeId();
    public Id assSRPNeedsIntake = Schema.SObjectType.Assessment__c.getRecordTypeInfosByName().get('SR Intake Needs Assessment').getRecordTypeId();     
    public Boolean BJMHS_Completed;
    public Boolean CRAFFT_Completed;   
    public Boolean PHQ9_Completed;
    public Boolean PHQ9T_Completed;
    public Boolean TCU_Completed;
    public String isAdult;
    public String newPageString = '/a0U/e?nooverride=1';

    private final SR_Intake_Needs_Assessment__c srNeeds;
    

    public SrNeedsAssessExt(ApexPages.StandardController stdController)
    {
        this.srNeeds = (SR_Intake_Needs_Assessment__c)stdController.getRecord();
        contactName = srNeeds.Participant__r.Name ;
        contactId = srNeeds.Participant__c;
        addressInfo = new Address_Information__c();
    }

    public void initialize()
    {
    }
    
    public List<SelectOption> getTypes()
    {
        Schema.sObjectType sobject_type = SR_Intake_Needs_Assessment__c.getSObjectType();
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();
        List<Schema.PicklistEntry> pick_list_values = field_map.get('Level_of_Social_Support__c').getDescribe().getPickListValues();
        List<selectOption> options = new List<selectOption>();
        for (Schema.PicklistEntry a : pick_list_values) 
        {
            options.add(new selectOption(a.getLabel(), a.getValue()));
        }
        return options;
    }

    public List<SelectOption> getSupportLevel()
    {
        Schema.sObjectType sobject_type = SR_Intake_Needs_Assessment__c.getSObjectType();
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();
        List<Schema.PicklistEntry> pick_list_values = field_map.get('Level_of_Social_Support__c').getDescribe().getPickListValues();
        List<selectOption> options = new List<selectOption>();
        for (Schema.PicklistEntry a : pick_list_values) 
        {
            options.add(new selectOption(a.getLabel(), a.getValue()));
        }
        return options;
    }
    

    public List<SelectOption> getEducationLevel()
    {
        Schema.sObjectType sobject_type = SR_Intake_Needs_Assessment__c.getSObjectType();
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();
        List<Schema.PicklistEntry> pick_list_values = field_map.get('Highest_Level_of_Education__c').getDescribe().getPickListValues();
        List<selectOption> options = new List<selectOption>();
        for (Schema.PicklistEntry a : pick_list_values) 
        {
            options.add(new selectOption(a.getLabel(), a.getValue()));
        }
        return options;
    }
   
    public boolean getBJMHS_Completed()
    {
        List<Assessment__c> bjmhs = [SELECT Id FROM Assessment__c WHERE RecordTypeId = :assBJMHSRecTypeId 
                    AND Contact__c = :srNeeds.Participant__c];
        if(bjmhs.size()>0)
            bjmhs_completed = false;
        else
            bjmhs_completed = true;
        return BJMHS_Completed;
    }
    
    public void setBJMHS_Completed(boolean bjmhs)
    {
        BJMHS_Completed = bjmhs;
    }

    public boolean getCRAFFT_Completed()
    {
        List<Assessment__c> crafft = [SELECT Id FROM Assessment__c WHERE RecordTypeId = :assCRAFFTRecTypeId 
                    AND Contact__c = :srNeeds.Participant__c];
        if(crafft.size()>0)
            crafft_completed = false;
        else
            crafft_completed = true;
        return CRAFFT_Completed;
    }

    public void setCRAFFT_Completed(boolean crafft)
    {
        crafft_Completed = crafft;
    }

    public boolean getPHQ9_Completed()
    {
        List<Assessment__c> PHQ9 = [SELECT Id FROM Assessment__c WHERE (RecordTypeId = :assPHQ9RecTypeId OR RecordTypeId = :assPHQ9RORecTypeId)
                    AND Contact__c = :srNeeds.Participant__c];
        if(phq9.size()>0)
            phq9_completed = false;
        else
            phq9_completed = true;
        return PHQ9_Completed;
    }

    public void setPHQ9_Completed(boolean phq9)
    {
        phq9_Completed = phq9;
    }

    public boolean getPHQ9T_Completed()
    {
        List<Assessment__c> PHQ9T = [SELECT Id FROM Assessment__c WHERE RecordTypeId = :assPHQ9TRecTypeId
                    AND Contact__c = :srNeeds.Participant__c];
        if(phq9t.size()>0)
            phq9t_completed = false;
        else
            phq9t_completed = true;
        return PHQ9T_Completed;
    }

    public void setPHQ9T_Completed(boolean phq9t)
    {
        phq9t_Completed = phq9t;
    }

    public boolean getTCU_Completed()
    {
        List<Assessment__c> TCU = [SELECT Id FROM Assessment__c WHERE RecordTypeId = :assTCURecTypeId 
                    AND Contact__c = :srNeeds.Participant__c];
        if(tcu.size()>0)
            tcu_completed = false;
        else
            tcu_completed = true;
        return TCU_Completed;
    }

    public void setTCU_Completed(boolean tcu)
    {
        tcu_Completed = tcu;
    }
    
    public String getIsAdult()
    {
        if(srNeeds.Participant__r.Current_Age__c > 18)
            isAdult = 'YES';
        else
            isAdult = 'NO';
        return isAdult;
    }
    
    public void setIsAdult(string adult)
    {
        isAdult = adult;
    }



    // action method to save the account and contact
    public PageReference save()
    {
        if(null!=addressInfo.Street__c)
        {       
            if(null==addressInfo.Zip_Code__c)
            {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Zip Code required.'));
                return null;
            }
            else
            {
                List<Address_Information__c> primaryAddress = [SELECT Id FROM Address_Information__c 
                    WHERE Client__c = :srNeeds.Participant__c AND Address_Type__c = 'Primary'];
                if (primaryAddress.size()>0)        
                {
                    primaryAddress[0].Address_Type__c = 'Former Primary';
                    update primaryAddress[0];
                }        
                addressInfo.Client__c = srNeeds.Participant__c;
                addressInfo.Address_Type__c = 'Primary';
                insert addressInfo;
            }
         }   
         upsert srNeeds;

        
        PageReference pref = new PageReference('/'+ srNeeds.Participant__c);
        pref.setRedirect(true);
        return pref;
    }

    public PageReference cancel()
    {
        PageReference pageRef = new PageReference('/'+ srNeeds.Participant__r.Id);
        pageRef.setRedirect(true);
        return pageRef;    
    }
}