src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/srpOutcomeScreenConTest.cls
@isTest (seeAllData=True)
private class srpOutcomeScreenConTest 
{
    //static utilityIds utilIds = new utilityIds();

    Private Static testmethod void srpOutcomeScreenConTest()
    {    

        Account account = new Account();
        account.Name = 'Fname Lname';
        //account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        account.RecordTypeId = Utility_ID__c.getValues('Client').RecordType_Id__c;
        insert account;
        
        Contact contact = new Contact();
        //contact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('SRP Client').getRecordTypeId();
        contact.RecordTypeID = Utility_ID__c.getValues('SRP Client').RecordType_Id__c;
        contact.FirstName = 'Test Fname';
        contact.LastName = 'Test Lname';
        contact.Screening_Outcome_srp__c = 'Eligible';
        contact.Arraignment_Outcome__c = 'Released into Supervised Release';        
        contact.accountid = account.id;
        insert contact;
        
        Case_Information__c caseInfo = new Case_Information__c();
        caseInfo.Name = '2000QN234567';
        //caseInfo.RecordTypeId = Schema.SObjectType.Case_Information__c.getRecordTypeInfosByName().get('Criminal Court').getRecordTypeId();
        caseInfo.RecordTypeId = Utility_ID__c.getValues('Case - Criminal Court').RecordType_Id__c;
        caseInfo.Client_Account__c = account.id;
        insert caseInfo;
        
        Program_Cycle__c newProgCycle = new Program_Cycle__c();
        Event nextCourtDate = new Event();
        nextCourtDate.whoId = contact.id;
        nextCourtDate.Subject = 'Court Date';
        nextCourtDate.RecordTypeId = Utility_ID__c.getValues('Court Date').RecordType_Id__c;
        nextCourtDate.WhatId = caseInfo.id;  
        nextCourtDate.DurationInMinutes = 60; 
        nextCourtDate.ActivityDate = system.today().addDays(-1);       
        nextCourtDate.ActivityDateTime = 
            DateTime.newInstance(nextCourtDate.ActivityDate, Time.newInstance(12,0,0,0));
            
        insert nextCourtDate;  
        
    
        srpOutcomeScreenCon controller = new srpOutcomeScreenCon();
        Test.startTest();
        PageReference pageRef = Page.srpOutcomeScreen;
        Test.setCurrentPage(pageRef);      
        controller.Contactid=contact.id;
        controller.Caseid=caseInfo.id;
        controller.thisContact = contact;
        controller.thisCase = caseInfo;
        controller.newProgCycle = newProgCycle;
        controller.progCycleSRP= Utility_ID__c.getValues('SRP Program Cycle').RecordType_Id__c;
        controller.doNothing();
        controller.goPortal();
        controller.nextCourtDate = nextCourtDate;
        controller.saveOutcome();
        Test.stopTest();
        
    }
    
}