src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intake_Date__c</fullName>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cycle_Type__c</fullName>
        <label>Cycle Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstatement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Type__c</fullName>
        <label>Exit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICM Step-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Tier_Change__c</fullName>
        <label>Reason for Tier Change</label>
        <picklist>
            <picklistValues>
                <fullName>Program</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Judge&apos;s request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intake Tier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120 Days in Cycle</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/programCycleTierMethods_UnitTest.cls
@isTest(SeeAllData=true)
private class programCycleTierMethods_UnitTest {


    static testMethod void tierCycleRollupValues() {
        
        utilityIds utilIds = new utilityIds();
        
        //clients- accounts
        Account accClient1 = new Account(Name = 'Test Contact 1', RecordTypeId = utilIds.accClient);   
        
        //dml
        insert new sObject[]{accClient1};      
        
        //docket
        Case_Information__c a1ci1 = new Case_Information__c(Client_Account__c = accClient1.Id, Name = 'D-47596/13');
        insert new sObject[]{a1ci1};      
        
        //clients- contacts
        Contact c1 = new Contact(LastName = 'Test Contact 1', recordtypeid = utilIds.conBXChoices, 
        Screening_Stage__c = 'Intake Complete', AccountId = accClient1.id, Intake_Case__c = a1ci1.Id);      
        
        //dml
        insert new sObject[]{c1};                   
        
        //program cycles
        Program_Cycle__c c1pc1 = new Program_Cycle__c(Client__c = c1.id, Cycle_Type__c = 'Intake', 
        Start_Date__c = system.today().addDays(-30), End_Date__c = system.today().addDays(-15), 
        Exit_Type__c = 'Unsuccessful Exit', RecordTypeId = utilIds.progCycleChoices);
        
        Program_Cycle__c c1pc2 = new Program_Cycle__c(Client__c = c1.id, Cycle_Type__c = 'Reinstatement', 
        Start_Date__c = system.today().addDays(-6), RecordTypeId = utilIds.progCycleChoices);   
        
        //dml
        insert new sObject[]{c1pc1, c1pc2};     
        
        //tiers
        Tier__c c1pc1t1 = new Tier__c(Program_Cycle__c = c1pc1.id, Tier__c = '1', Reason_for_Tier_Change__c = 'Intake Tier',
        Start_Date__c = system.today().addDays(-30), End_Date__c = system.today().addDays(-15));
        
        Tier__c c1pc2t1 = new Tier__c(Program_Cycle__c = c1pc2.id, Tier__c = '1', Reason_for_Tier_Change__c = 'Intake Tier',
        Start_Date__c = system.today().addDays(-6), End_Date__c = system.today().addDays(-4));
        
        Tier__c c1pc2t2 = new Tier__c(Program_Cycle__c = c1pc2.id, Tier__c = '2', Reason_for_Tier_Change__c = 'Program',
        Start_Date__c = system.today().addDays(-3));        
        
        //dml
        insert new sObject[]{c1pc1t1, c1pc2t1, c1pc2t2};
        
        //requery to get new values. query contact because the values will only appear correctly in roll-up fields
        // if most recent tier and most recent program cycle are properly set.
        map<Id, Contact> conResults = new map<Id, Contact>([select id, Current_Tier_Formula__c, 
        Intake_Date__c, Current_Intake_Date__c, Current_Exit_Date__c, 
        Number_of_Days_in_Program__c, Client_Status__c from contact where id = :c1.id]);
        
        //test contact page update
        system.assertEquals(conResults.get(c1.id).Current_Tier_Formula__c, '2');
        system.assertEquals(conResults.get(c1.id).Current_Intake_Date__c, system.today().addDays(-6));
        system.assertEquals(conResults.get(c1.id).Current_Exit_Date__c, null);
        system.assertEquals(conResults.get(c1.id).Client_Status__c, 'Active');

        //update c1pc1t1 values and delete other tiers/cycles
        
        delete new sObject[]{c1pc2};
        
        c1pc1t1.Tier__c = '2';
        update c1pc1t1;
        
        //requery
        map<Id, Contact> conResults2 = new map<Id, Contact>([select id, Current_Tier_Formula__c, 
        Intake_Date__c, Current_Intake_Date__c, Current_Exit_Date__c, 
        Number_of_Days_in_Program__c, Client_Status__c from contact where id = :c1.id]);        
        
        //test contact updates
        system.assertEquals(conResults2.get(c1.id).Current_Tier_Formula__c, '2');
        system.assertEquals(conResults2.get(c1.id).Current_Intake_Date__c, system.today().addDays(-30));
        system.assertEquals(conResults2.get(c1.id).Current_Exit_Date__c, system.today().addDays(-15));
        system.assertEquals(conResults2.get(c1.id).Client_Status__c, 'Exited');
        
        //test that child tiers of c1pc2 were deleted
        list<Tier__c> lstDeletedTiers = [select id from Tier__c where id = :c1pc2t1.id or id = :c1pc2t2.id];
        
        system.assertEquals(lstDeletedTiers.size(), 0);     
        
        
        //delete last program cycle, null out fields on contact
        delete c1pc1;
        
        //requery
        map<Id, Contact> conResults3 = new map<Id, Contact>([select id, Current_Tier_Formula__c, 
        Current_Intake_Date__c, Current_Exit_Date__c, 
        Number_of_Days_in_Program__c, Client_Status__c from contact where id = :c1.id]);        
        
        //test contact updates
        //9/17/13 MB: clearing all cycles (setting status to never enrolled) 
        //is only done via flow, where these fields are set manually
        /*system.assertEquals(conResults3.get(c1.id).Current_Tier_Formula__c, null);
        system.assertEquals(conResults3.get(c1.id).Current_Intake_Date__c, null);
        system.assertEquals(conResults3.get(c1.id).Current_Exit_Date__c, null);*/  
    }

}