src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address_Information__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Information</relationshipLabel>
        <relationshipName>Secondary_Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Address Information</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Add-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>No_Docket__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this field if there is no Docket Number for this case. On save, DOCKET NA will be auto filled in the Docket Number field.</inlineHelpText>
        <label>No Docket</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PEAK_Intake_Screen_Con.cls
public with sharing class PEAK_Intake_Screen_Con 
{
    public Account acc {get; set;}
    public Contact con {get; set;}
    public Case_Information__c  caseInfo {get; set;}
    public Address_Information__c addressInfo {get;set;}
    public String txtFirstName {get;set;}
    public String txtLastName {get;set;}
    public Id recTypeId;
    public Id accid;
    public Id accountId;

    public PEAK_Intake_Screen_Con() 
    {
        acc = new Account();
        con = new Contact();
        caseInfo = new Case_Information__c();
        addressInfo = new Address_Information__c();
        recTypeId = ApexPages.currentPage().getParameters().get('RecordType');
        accid = ApexPages.currentPage().getParameters().get('accid');
        system.debug('RECORD TYPE ID: ' + recTypeId);         
    }

    public PageReference Cancel() 
    {
        return null;
    }


    public PageReference Save() 
    {
        if(accid == NULL)
        {
            system.debug('NAME: ' + txtFirstName + ' ' + txtLastName);
            acc.Name = txtFirstName + ' ' + txtLastName;
            system.debug('NAME: ' + acc.Name);
            acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
            Insert acc;
            accountId = acc.Id;
        } else
        {
            accountId = accid;
        }
            
        caseInfo.RecordTypeId = Schema.SObjectType.Case_Information__c.getRecordTypeInfosByName().get('Family Court').getRecordTypeId();
        caseInfo.Client_Account__c = accountId;
        caseInfo.No_Docket__c = true;
        if ( recTypeId == Schema.SObjectType.Contact.getRecordTypeInfosByName().get('BK PEAK Client').getRecordTypeId())
            caseInfo.Borough__c = 'Brooklyn';
           
        else if(recTypeId == Schema.SObjectType.Contact.getRecordTypeInfosByName().get('BX PEAK Client').getRecordTypeId())
            caseInfo.Borough__c = 'Bronx';
        Insert caseInfo;
        
        con.AccountId = accountId;
        con.LastName = txtLastName;
        con.FirstName = txtFirstName;
        con.RecordTypeId = recTypeId;
        con.Intake_Case__c = caseInfo.Id;
        con.Client_Status__c = 'Incomplete Screening';
        Insert con;
        
        addressInfo.Client__c = con.Id;
        Insert addressInfo;     
     
        PageReference contactPage = new PageReference('/'+ con.Id);
        contactPage.setRedirect(true);
        return contactPage; 
    }

}