src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cycle_Type__c</fullName>
        <label>Cycle Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstatement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SRP_Reinstatement_UT.cls
@isTest(seealldata=true)
private class SRP_Reinstatement_UT 
{
    static SRP_ReinstatementConExt srConExt;

    Private Static testmethod void SRP_Reinstatement_UT()
    {    
        Account account = new Account();
        account.Name = 'Fname Lname';
        account.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
        insert account;
        
        Contact contact = new Contact();
        contact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('SRP Client').getRecordTypeId();
        contact.FirstName = 'Test Fname';
        contact.LastName = 'Test Lname';
        contact.Screening_Outcome_srp__c = 'Eligible';
        contact.Arraignment_Outcome__c = 'Released into Supervised Release';        
        contact.accountid = account.id;
        insert contact;
        
        Program_Cycle__c progCycle = new Program_Cycle__c();
        progCycle.Client__c = contact.id;
        progCycle.Cycle_Type__c = 'Intake';
        progCycle.Start_Date__c = Date.parse('09/15/2016');
        progCycle.End_Date__c = Date.parse('10/15/2016');
        progCycle.RecordTypeId = Schema.SObjectType.Program_Cycle__c.getRecordTypeInfosByName().get('SRP Program Cycle').getRecordTypeId();
        insert progCycle;

        contact.Most_Recent_Program_Cycle__c = progCycle.Id;
        update contact;

        Program_Cycle__c newProgCycle = new Program_Cycle__c();
        
        ApexPages.StandardController stdcon = new ApexPages.StandardController(contact);
        srConExt = new SRP_ReinstatementConExt(stdcon); 
        Test.startTest();
        PageReference pageRef = Page.SRP_Reinstatement;
        Test.setCurrentPage(pageRef);
        srConExt.cancelThis();
        srConExt.saveThis();
        contact.RecordTypeId = Schema.SobjectType.Contact.getRecordTypeInfosByName().get('DTC Client').getRecordTypeId();
        update contact;
        progCycle.End_Date__c = Date.parse('11/01/2018');
        update progCycle;
        srConExt.saveThis();
        contact.RecordTypeId = Schema.SobjectType.Contact.getRecordTypeInfosByName().get('CEO Client').getRecordTypeId();
        update contact;
        progCycle.End_Date__c = Date.parse('11/01/2018');
        update progCycle;
        srConExt.saveThis();
        contact.RecordTypeId = Schema.SobjectType.Contact.getRecordTypeInfosByName().get('CCM Client').getRecordTypeId();
        update contact;
        progCycle.End_Date__c = Date.parse('11/01/2018');
        update progCycle;
        srConExt.saveThis();
        Test.stopTest();
    }	
}