src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Detained_Dates__c.object
<CustomObject>
    <description>To record multiple detained dates and release dates for a case</description>
    <fields>
        <fullName>Contact_Detained_Dates_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Detained Dates</relationshipLabel>
        <relationshipName>Contact_Detained_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Released__c</fullName>
        <label>Date Released</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Detained_Date__c</fullName>
        <label>Detained Date</label>
        <type>Date</type>
    </fields>
    <label>Detained Dates</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Detained Dates ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detained Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cycle_Type__c</fullName>
        <label>Cycle Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstatement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Reason__c</fullName>
        <label>Exit Reason</label>
        <picklist>
            <controllingField>Exit_Type__c</controllingField>
            <picklistValues>
                <fullName>7/30 Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternative Services Found</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitalized - Long Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incarcerated - Long Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Follow-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Met Program Objectives/Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved out of area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Arrest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New VFO Re-Arrest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Warrant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recipient Requests Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Failure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss to Follow-Up/No Show for Extended Period</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_in_Program_Cycle__c</fullName>
        <label>Number of Days in Program</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Tier_Change__c</fullName>
        <label>Reason for Tier Change</label>
        <picklist>
            <picklistValues>
                <fullName>Program</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Judge&apos;s request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intake Tier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120 Days in Cycle</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jobUpdateNumberofDaysinCycle_UnitTest.cls
@isTest (SeeAllData=true)

private class jobUpdateNumberofDaysinCycle_UnitTest {

    // test manual method (scheduled method tested in scheduler)
    static testmethod void test() {
        
       utilityIds utilIds = new utilityIds();
        
        //clients- accounts
        Account accClient1 = new Account(Name = 'Test Contact 1',
            RecordTypeId = utilIds.accClient);   

        Account accClient2 = new Account(Name = 'Test Contact 2',
            RecordTypeId = utilIds.accClient);             
        
        //dml
        insert new sObject[]{accClient1, accClient2};            
        
        //clients- contacts
        Contact c1 = new Contact(LastName = 'Test Contact 1', recordtypeid = utilIds.conChoices, 
            AccountId = accClient1.id, Screening_Stage__c = 'Screening Complete'); 
            
        Contact c2 = new Contact(LastName = 'Test Contact 2', recordtypeid = utilIds.conChoices, 
            AccountId = accClient2.id, Screening_Stage__c = 'Screening Complete');                
        
        //dml
        insert new sObject[]{c1, c2};                   
        
        //program cycles
        Program_Cycle__c c1pc1 = new Program_Cycle__c(Client__c = c1.id, Cycle_Type__c = 'Intake', 
            Start_Date__c = system.today().addDays(-135), RecordTypeId = utilIds.progCycleChoices);
                    
        Program_Cycle__c c2pc1 = new Program_Cycle__c(Client__c = c2.id, Cycle_Type__c = 'Intake', 
            Start_Date__c = system.today().addDays(-130), End_Date__c = system.today().addDays(-7), 
            Exit_Reason__c = 'Mandate Successfuly Completed', RecordTypeId = utilIds.progCycleChoices);  
            
        Program_Cycle__c c2pc2 = new Program_Cycle__c(Client__c = c2.id, Cycle_Type__c = 'Reinstatement', 
            Start_Date__c = system.today().addDays(-6), RecordTypeId = utilIds.progCycleChoices);                   
        
        //dml
        insert new sObject[]{c1pc1, c2pc1, c2pc2};    
        
        //tiers
        Tier__c c1pc1t1 = new Tier__c(Program_Cycle__c = c1pc1.id, 
            Reason_for_Tier_Change__c = 'Intake Tier', Tier__c = '1', 
            Start_Date__c = system.today().addDays(-135), End_Date__c = system.today().addDays(-133));
            
        Tier__c c1pc1t2 = new Tier__c(Program_Cycle__c = c1pc1.id, 
            Reason_for_Tier_Change__c = 'Judge', Tier__c = '1', 
            Start_Date__c = system.today().addDays(-132));              
            
        Tier__c c2pc1t1 = new Tier__c(Program_Cycle__c = c2pc1.id, 
            Reason_for_Tier_Change__c = 'Intake Tier', Tier__c = '2', 
            Start_Date__c = system.today().addDays(-130));  
            
        Tier__c c2pc2t1 = new Tier__c(Program_Cycle__c = c2pc2.id, 
            Reason_for_Tier_Change__c = 'Intake Tier', Tier__c = '2', 
            Start_Date__c = system.today().addDays(-6));                                
            
        //dml
        insert new sObject[]{c1pc1t1, c1pc1t2, c2pc1t1, c2pc2t1};            
        
        //detained dates
        Detained_Dates__c c1pc1d1 = new Detained_Dates__c(Contact_Detained_Dates_Lookup__c = c1.id,
            Detained_Date__c = system.today().addDays(-98), Date_Released__c = system.today().addDays(-95));        
        
        Detained_Dates__c c1pc1d2 = new Detained_Dates__c(Contact_Detained_Dates_Lookup__c = c1.id,
            Detained_Date__c = system.today().addDays(-1), Date_Released__c = system.today());                          
            
        Detained_Dates__c c2pc1d1 = new Detained_Dates__c(Contact_Detained_Dates_Lookup__c = c2.id,
            Detained_Date__c = system.today().addDays(-90), Date_Released__c = system.today().addDays(-70));                
        
        Detained_Dates__c c2pc2d1 = new Detained_Dates__c(Contact_Detained_Dates_Lookup__c = c2.id,
            Detained_Date__c = system.today().addDays(-2));     
            
        //dml
        insert new sObject[]{c1pc1d1, c1pc1d2, c2pc1d1, c2pc2d1};           
        
        Test.startTest();

        jobUpdateNumberofDaysinCycle j = new jobUpdateNumberofDaysinCycle();
        j.UpdateDayCounts(50, null, null);
        j.UpdateDayCounts(null, System.Today().addDays(-1), System.Today().addDays(1));
    
        //get updated day count
        Program_Cycle__c c1pc1result = [select id, Number_Of_Days_in_Program_Cycle__c from Program_Cycle__c
            where id = :c1pc1.id]; 
            
        Program_Cycle__c c2pc1result = [select id, Number_Of_Days_in_Program_Cycle__c from Program_Cycle__c
            where id = :c2pc1.id];  
            
        Program_Cycle__c c2pc2result = [select id, Number_Of_Days_in_Program_Cycle__c from Program_Cycle__c
            where id = :c2pc2.id];          
            
        //get updated tiers
        Tier__c c1pc1t2result = [select id, End_Date__c from Tier__c where id = :c1pc1t2.id];       
        
        Tier__c c2pc1t1result = [select id, End_Date__c from Tier__c where id = :c2pc1t1.id];   
        
        Tier__c c2pc2t1result = [select id, End_Date__c from Tier__c where id = :c2pc2t1.id];                               
        
        //check days in cycle values    
        //system.assertEquals(c1pc1result.Number_of_Days_in_Program_Cycle__c,  130);
        system.debug('c1pc1result.Number_of_Days_in_Program_Cycle__c' +  c1pc1result.Number_of_Days_in_Program_Cycle__c );  
        //system.assertEquals(c2pc1result.Number_of_Days_in_Program_Cycle__c,  103);  
        system.debug('c2pc1result.Number_of_Days_in_Program_Cycle__c' +  c2pc1result.Number_of_Days_in_Program_Cycle__c );          
        //system.assertEquals(c2pc2result.Number_of_Days_in_Program_Cycle__c,  4);    
         system.debug('c2pc2result.Number_of_Days_in_Program_Cycle__c' +  c1pc1result.Number_of_Days_in_Program_Cycle__c );                 
        
        //check that tiers closed correctly (if the cycle was past 120 days)    
        //system.assertEquals(c1pc1t2result.End_Date__c,  system.today().addDays(-12)); 
        system.debug('c1pc1t2result.End_Date__c: '+ c1pc1t2result.End_Date__c + '   '+system.today().addDays(-12));   
        //system.assertEquals(c2pc1t1result.End_Date__c,  null); 
        system.debug('c2pc1t1result.End_Date__c: '+ c2pc1t1result.End_Date__c );        
        //system.assertEquals(c2pc2t1result.End_Date__c,  null);
        system.debug('c2pc2t1result.End_Date__c: '+ c2pc2t1result.End_Date__c );   
        Test.stopTest();
    }
}