src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address_Information__c.object
<CustomObject>
    <fields>
        <fullName>Apt_No__c</fullName>
        <label>Apt. No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_No__c</fullName>
        <label>Building No.</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City Text</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chestnut Ridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deer Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jersey City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mount Vernon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Bergen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yonkers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Information</relationshipLabel>
        <relationshipName>Secondary_Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State Text</label>
        <picklist>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Jersey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Address Information</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Add-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Charges__c.object
<CustomObject>
    <description>To enter all charges for a case - arrest, plea, indictment and court related</description>
    <fields>
        <fullName>Docket_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Docket #</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Charges</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Arrest Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indictment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plea/ Finding Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Charges</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Case Charges ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Arrest_Date__c</fullName>
        <label>Arrest Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Case_Status__c</fullName>
        <formula>if(  RecordType.Name = &apos;Family Court&apos;,
    if(not(isblank( Sentence_Disposition_Date__c )), &quot;After Disposition&quot;, 
    if(not(isblank( Plea_Finding_Date__c )), &quot;After Fact Finding&quot;, &quot;Before Fact Finding&quot;)), 

    if(not(isblank( Sentence_Disposition_Date__c )), &quot;After Sentence&quot;, 
    if(not(isblank( Plea_Finding_Date__c )), &quot;After Plea&quot;, &quot;Pre Plea&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Case Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detention_Status_at_SC_Arraignment__c</fullName>
        <label>Detention Status at SC Arraignment</label>
        <picklist>
            <picklistValues>
                <fullName>ROR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Made Bail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In On Bail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Remand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Indictment__c</fullName>
        <inlineHelpText>Two format:s are permitted  
  12345-2006   and  
  SCI12345-YYYY   where YYYY is the year</inlineHelpText>
        <label>Indictment #</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Penal_Code__c.object
<CustomObject>
    <label>Penal Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Penal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/printCIRTcontrollerUnitTest.cls
@isTest (SeeAllData=true)
private class printCIRTcontrollerUnitTest {
  static utilityIds utilIds = new utilityIds();
    static Case_Information__c caseTest = new Case_Information__c();
    static Case_Information__c caseTest1 = new Case_Information__c();
    static reportQuery rq = new reportQuery();
    static Event eventTest = new Event();
     static Contact contactTest = new Contact();
    static Case_Charges__c chgTest = new Case_Charges__c();
    static Account accountTest = new Account();
    
    static ID accAgency = Utility_ID__c.getValues('External Entities').RecordType_Id__c;
    
    static Address_Information__c addressTest = new Address_Information__c(); 
    static Id caseRecTypeId = Utility_ID__c.getValues('Case - Criminal Court').RecordType_Id__c;
    static Id suprRecTypeId = Utility_ID__c.getValues('Case - Supreme Court').RecordType_Id__c;
    static Id attRecordType = Utility_ID__c.getValues('Attorney/ Law Guardian').RecordType_Id__c;


    static Id EventRecTypeId = Utility_ID__c.getValues('Court Date').RecordType_Id__c;
   static Id conCRT = Utility_ID__c.getValues('CIRT Client').RecordType_Id__c;  
 //   static Id accCIRT = Utility_Id__c.getValues('CIRT Account').RecordType_Id__c;
    static void createTestData() {
      date ddate =  date.parse('11/11/2013');
     date ddate1 =  date.parse('03/11/2014');
      date manddate = date.parse('11/15/2013');
    User adminUser = [Select Id from User Where isActive = true and Profile.Name = 'System Administrator' Limit 1];
    
      Account accountTestAgency = new Account();
      accountTestAgency.nysid_number__c = '04221673Z';  
      accountTestAgency.Name = 'Legal';
      accountTestAgency.recordtypeId =  accAgency;
      accountTestAgency.BillingStreet = 'Broadway';
      accountTestAgency.billingState = 'NY';
      accountTestAgency.BillingPostalCode= '100015';
      insert accountTestAgency;
      
        Contact  contactTestAtt = new Contact();
        contactTestAtt.lastName = 'Lasttest';
        contactTestAtt.firstName = 'firsttest';
        contactTestAtt.firstname = 'attFirst';
        contactTestAtt.lastName = 'attlast';
        contactTestAtt.RecordTypeId = attRecordType;
        contactTestAtt.accountid = accountTestAgency.id; 
        insert contactTestAtt;
 
      accountTest = new Account();
      accountTest.nysid_number__c = '04221673K';  
      accountTest.Name = 'CIRT';
      accounttest.DOB__c = date.parse('11/11/1950');
      accountTest.recordtypeId = utilIds.accClient;
      insert accountTest;
              
      casetest.Client_Account__c = accountTest.Id;
      caseTest.Name = '2013NY023083';
       caseTest.Borough__c = 'Bronx';
       caseTest.Indictment__c = 'indictment';
//       caseTest.Current_Case_Status__c = 'At Plea';
       caseTest.Detention_Status_at_SC_Arraignment__c = 'ROR';
       caseTest.RecordTypeId = suprRecTypeId;
       caseTest.Arrest_Date__c = date.today();
      insert caseTest;
 
        ID Accountid = accountTest.id; 
        contactTest = new Contact();
        contactTest.lastName = 'Lasttest';
        contactTest.firstName = 'firsttest';
        contactTest.recordtypeid = conCRT; 
        contactTest.Client_Status__c = 'Active';
        contactTest.Mandate_Decision_Date__c = manddate;
        contactTest.aka_1__c = 'aka1';
        contactTest.aka_2__c = 'aka2';
        contactTest.aka_3__c = 'aka3';
        contactTest.Resource_Coordinator_s_Comments__c = 'comments';
        contactTest.Criminal_Justice_Involvement__c = 'Parole';
    //    contactTest.attorney__c = contactTest.id;
        contactTest.Supervising_Attorney__c = contactTestAtt.id;
        contactTest.Prior_Violent_Conviction_Date__c = date.today() -100;
         contactTest.AccountId = AccountId;
         contactTest.Intake_Case__c = caseTest.Id;
        insert contactTest;
 
      addressTest.client__c = contactTest.id;
      addressTest.client__c = contactTest.id;
      addressTest.Move_In_Date__c = ddate;
      addressTest.Home_Phone__c = '212 053-6666';
      addressTest.Building_No__c = '200';
      addressTest.street__c = 'E 31 St.';
      addressTest.Apt_No__c = '10C';
      addressTest.City__c = 'Brooklyn';
      addressTest.State__c = 'NY';
      addressTest.zip__c = '11256';
      addressTest.Home_Phone__c = '646 888-4444';
      insert addressTest;
      
      List<Event> lstEvents = new List<Event>();
      eventTest = new Event();
      eventTest.recordTypeId = EventRecTypeId;
      eventTest.whoid = contactTest.id;
    eventTest.whatid = casetest.id;
      datetime dtime =  datetime.parse('11/11/2013 12:00 AM');
        eventTest.ActivityDateTime = dtime;
        eventTest.ActivityDate = ddate;
        eventTest.DurationInMinutes = 30;
        eventTest.verification_status__c = 'Not Verified';
        lstEvents.add(eventTest);
 
   //     eventTest1 = new Event();
      eventTest.recordTypeId = EventRecTypeId;
      eventTest.whoid = contactTest.id;
      eventTest.whatid = casetest.id;
      datetime dtime1 =  datetime.now();
        eventTest.ActivityDateTime = dtime1;
        eventTest.ActivityDate = date.today();
        eventTest.DurationInMinutes = 30;
        eventTest.verification_status__c = 'Not Verified';
        lstEvents.add(eventTest);
        
  

    chgTest.Docket_No__c = caseTest.id;
       chgTest.Type__c = 'Criminal Court Arraignment Charges';
        ID pcodeId;
         for (Penal_Code__c lstcodes : [select id from Penal_Code__c Limit1 ])
       {
            pcodeId = lstcodes.id;
       }
       
       insert chgTest; 
    }
     static testMethod void testReportQuery()
      {
        createTestData();
 
           test.startTest();
           printCIRTcontroller pc = new printCIRTcontroller(); 
           pc.IdPassed = contactTest.id;
           pc.generateReport();
           test.stopTest();
      }
}