src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agency_Type__c</fullName>
        <description>CEP: What type of services are provided by the agency.</description>
        <label>Agency Type</label>
        <picklist>
            <picklistValues>
                <fullName>College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ed. Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internship Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Training/Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Development</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program_Relationships__c.object
<CustomObject>
    <description>Details relationship between warrant | program | client</description>
    <fields>
        <fullName>Active_at_Exit_Picklist__c</fullName>
        <description>1/23/15 replaces Active at Exit? formula to remove the burden of entering exact exit dates, and to provide an indication the information was consciously checked and entered.</description>
        <label>Active at Exit?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Active_at_Intake__c</fullName>
        <formula>and(not(isblank(Warrant__r.Current_Intake_Date__c )),  Program_Start_Date__c &lt;= Warrant__r.Current_Intake_Date__c, or(isblank(Discharge_Date_Phone_Visit__c ),  Discharge_Date_Phone_Visit__c &gt; Warrant__r.Current_Intake_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active at Intake?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly &quot;Program&quot;, Formerly Treatment Agency, changed 9/29/13 for START by MB</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Entities, Treatment Agency, CASES Programs</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Warrant Relationships</relationshipLabel>
        <relationshipName>Program_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>School_Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School/ Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Relationships (School/ Institution)</relationshipLabel>
        <relationshipName>Program_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warrant__c</fullName>
        <description>previously referred to as &quot;PRP Cycle&quot;, changed by MB 9/29/13</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Relationships</relationshipLabel>
        <relationshipName>Program_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Relationships</label>
    <nameField>
        <displayFormat>PR-C{0}</displayFormat>
        <label>Program Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jobCalculateInsuranceFields.cls
global class jobCalculateInsuranceFields {

    global utilityIDs utilIDs = new utilityIDs();
    
    global void main(date dteStart, date dteEnd) {
        
        //list of contact Ids to process
        list<Id> lstContactIdstoQuery = new list<Id>();
        list<Contact> lstContactstoUpdate = new list<Contact>();
        
        //contacts intaked or exited in the date range
        list<ContactHistory> lstCHistory = [select ContactId from ContactHistory 
                                            where Field in ('Current_Intake_Date__c', 'Current_Exit_Date__c')
                                            and CreatedDate >= :dteStart and CreatedDate <= :dteEnd];
        
        //PRs edited in date range                                  
        list<Program_Relationships__c> lstUpdatedPRs = [select Warrant__c from Program_Relationships__c
                                                        where LastModifiedDate >= :dteStart 
                                                        and LastModifiedDate <= :dteEnd];
                                                
        for(ContactHistory ch: lstCHistory) {
            
            lstContactIdstoQuery.add(ch.ContactId);
        }       
        
        for(Program_Relationships__c pr: lstUpdatedPRs) {
            
            lstContactIdstoQuery.add(pr.Warrant__c);
        }                                           
                                                        
        list<Contact> lstContactsToQuery = [select id, Do_you_have_Insurance__c, Insurance_Status_at_Exit__c,
                                            Health_Home_at_Intake__c, Health_Home_at_Exit__c,
                                            Current_Intake_Date__c, Current_Exit_Date__c,
                                            (select id, Active_At_Intake__c, Active_at_Exit_Picklist__c,
                                            program__r.Name, program__r.Agency_Type__c
                                            from Program_Relationships__r
                                            where program__r.Name in ('Medicaid', 'Medicare', 'Private Insurance')
                                            or program__r.Agency_Type__c includes ('Health Home'))
                                            from Contact where id in :lstContactIdstoQuery
                                            and RecordTypeId in (:utilIDs.conCRT, :utilIDs.conDTC, :utilIDs.conCCM, :utilIDs.conTRP)];
                                            
        for(Contact c: lstContactsToQuery) {
            
            //default values. Only set "no" if corresponding date is filled in, otherwise leave blank
            String strInsuranceIntake = (c.Current_Intake_Date__c!=null)?'No':null;
            String strInsuranceExit = (c.Current_Exit_Date__c!=null)?'No':null;
            String strHHIntake = (c.Current_Intake_Date__c!=null)?'No':null;
            String strHHExit = (c.Current_Exit_Date__c!=null)?'No':null;
            
            for(Program_Relationships__c pr: c.Program_Relationships__r) {
                
                //Insurance
                if(pr.program__r.Name == 'Medicaid' || pr.program__r.Name == 'Medicare'
                || pr.program__r.Name == 'Private Insurance') {
                    
                    if(pr.Active_at_Intake__c && c.Current_Intake_Date__c != null) {
                        
                        strInsuranceIntake = 'Yes';
                    }
                    
                    if(pr.Active_at_Exit_Picklist__c == 'Yes'  && c.Current_Exit_Date__c != null) {
                        
                        strInsuranceExit = 'Yes';
                    }
                } else if(pr.program__r.Agency_Type__c.contains('Health Home')) {//Health Home

                    if(pr.Active_at_Intake__c && c.Current_Intake_Date__c != null) {
                        
                        strHHIntake = 'Yes';
                    }
                    
                    if(pr.Active_at_Exit_Picklist__c == 'Yes'  && c.Current_Exit_Date__c != null) {
                        
                        strHHExit = 'Yes';
                    }                   
                }
            }
            
            if(strInsuranceIntake != c.Do_you_have_Insurance__c || strInsuranceExit != c.Insurance_Status_at_Exit__c
            || strHHIntake != c.Health_Home_at_Intake__c || strHHExit != c.Health_Home_at_Exit__c) {
            
                c.Do_you_have_Insurance__c = strInsuranceIntake;
                c.Insurance_Status_at_Exit__c = strInsuranceExit;
                c.Health_Home_at_Intake__c = strHHIntake;
                c.Health_Home_at_Exit__c = strHHExit;
                lstContactstoUpdate.add(c);
            }
        }       
        
        update lstContactsToUpdate;                          
    }
}