src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Contact Person</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Address_Information__c.object
<CustomObject>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Former Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City Text</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chestnut Ridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deer Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jersey City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mount Vernon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Bergen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yonkers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Information</relationshipLabel>
        <relationshipName>Secondary_Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Head of Household</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Move_In_Date__c</fullName>
        <label>Move In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State Text</label>
        <picklist>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Jersey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Zip Code</label>
        <referenceTo>Zip_Code_Mapping__c</referenceTo>
        <relationshipLabel>Address Information</relationshipLabel>
        <relationshipName>Address_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Address Information</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Add-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zip_Code_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Bayonne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buffalo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deer Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elizabeth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elmsford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Englewood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hempstead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jackson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jersey City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Livingston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mamaroneck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mastic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millburn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mount Vernon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paterson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secaucus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Somerville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tarrytown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenafly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tobyhanna</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federated States Of Micronesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marshall Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Zip Code Mapping</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddressInformationMethodsUnitTests.cls
@isTest
private class AddressInformationMethodsUnitTests {

    
    static testMethod void testAddressInsert() {
        
        utilityIds util = new utilityIds();
        
        // Create some sample dates for insert commands
        Date birthDate1 = Date.newInstance(1976,11,20);
        Date referDate1 = Date.newInstance(2006,11,20);
        Address_Information__c adinfo1;
        
        //Create client account
        Account accClient = new Account(Name = 'Unit Tester', RecordTypeId = util.accClient);
        insert accClient;

        //Create a Test Client
        Contact testContact = new Contact(FirstName = 'Unit', LastName = 'Tester', AccountId = accClient.Id, 
        Birthdate = birthDate1, RecordTypeID = util.conClient );  
        insert testContact;
        
        //Get a Zip Code
       Zip_Code_Mapping__c zipIn = new Zip_Code_Mapping__c(City__c='Elmsford', State__c = 'New York', Name = '10502');
       insert zipIn;
      
        Zip_Code_Mapping__c zip = [select id, Name from Zip_Code_Mapping__c limit 1 ];

        //Attempt to insert TWO Primary Addresses, only one should go through
        Address_Information__c adinfo2;
        try {
            adinfo1 = new Address_Information__c(Client__c = testContact.Id, Address_Type__c = 'Primary', 
            Street__c = 'TEST', Contact_Person__c = 'TEST', Move_In_Date__c = referDate1, Home_Phone__c = '12345', 
            Zip_Code__c = zip.id);
            insert adinfo1;
            adinfo2 = new Address_Information__c(Client__c = testContact.Id,  Address_Type__c = 'Primary', 
            Street__c = 'TEST', Contact_Person__c = 'TEST', Move_In_Date__c = referDate1, Zip_Code__c = zip.id);
            insert adinfo2;
        } catch(Exception e) {
            // We don't really need to do anything with the exception since we are doing a dup test
            System.debug('Address Info Exception = ' + e);
        }
        
        Integer i = 0;

        //Now let's check to see how many Primary addresses exist for our test client
        
        System.debug('Test Contact ID = ' + testContact.id);

        for (Address_Information__c a : [SELECT Id FROM Address_Information__c 
               WHERE (Address_Type__c = 'Primary')
               AND Client__c = :testContact.Id]) {
            i++;
        }

        //Ensure that the query returned the expected number of
        //contacts.

        System.assertEquals(1, i);
        
        //Make sure the Home Phone was populated
        testContact = [Select Id, HomePhone from Contact where Id = :testContact.Id];
        System.assertEquals('12345', testContact.HomePhone);
        
        //Delete address should delete home phone in Contact 
        delete adinfo1;
        testContact = [Select Id, HomePhone from Contact where Id = :testContact.Id];
        System.assertEquals(null, testContact.HomePhone);
        
    }       
    
}