src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AssessmentContainer__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Completed_on__c</fullName>
        <label>Assessment Completed on:</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AssessmentContainers</relationshipLabel>
        <relationshipName>AssessmentContainers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AssessmentContainer</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>assessmentContainer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AssessmentContainers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/uploadAssessment_UnitTest.cls
@isTest(SeeAllData=true)
private class uploadAssessment_UnitTest {
    static utilityIds utilIDs = new utilityIds();	
	static UtilityFileMethods uf = new UtilityFileMethods();
    static Account accCep1 = new Account();	
//	static Assessment__c assTest = new Assessment__c();
	static AssessmentContainer__c assTest = new AssessmentContainer__c();
	static Contact contactTest = new Contact();
    static Case_Information__c newCaseInfo1 =  new Case_Information__c();
    static string ccmclient = Utility_ID__c.getValues('CCM Client').RecordType_Id__c;    
    static string ccmid;
	static Blob csvFileBody;
 //   static Blob csvFileBody;
 
   static void createAssessmentTestData() {
   	    
   	    accCep1 = new Account(Name='test1', RecordTypeId = utilIds.accClient);
        insert accCep1;
 	    
        newCaseInfo1 = new Case_Information__c();
        newCaseInfo1.Client_Account__c = accCep1.Id;
        newCaseInfo1.RecordTypeId = utilIds.caseInfoSupremeCourt;
        newCaseInfo1.Name = '2015TN456011';
        newCaseInfo1.Borough__c = 'Bronx';
        insert newCaseInfo1;   
 
 	    contactTest = new Contact();
        contactTest.lastName = 'Lasttest'; 
        contactTest.firstName = 'firsttest';
        contactTest.Client_Status__c = 'Active';
        contactTest.recordtypeid = ccmclient; 
        contactTest.Current_Intake_Date__c = System.Today()- 30;
        contactTest.accountId = accCep1.id;   
        contactTest.Intake_Case__c = newCaseInfo1.id;   
        insert contactTest;
        ccmid = contactTest.id;
        
        assTest = new AssessmentContainer__c();
   	    assTest.client__c = contactTest.id;
        assTest.Assessment_Completed_on__c = date.today();
        insert assTest;}
         
   static testMethod void testLSCMI()
   {  createAssessmentTestData();
   	   uploadAssessmentController csv = new uploadAssessmentController();
  	   uf.idForTestCCM = ccmid;
  	   csv.csvFileBody = uf.generateCSV_forLSMI();
   	   csv.csvFile = 'LSCMI';
  	   test.startTest();  
   	   csv.readcsvLSCMI();
 	   csv.csvFile = 'LSCMI ABH';
   	   csv.readcsvLSCMI();
   	   test.stopTest();}
    
  static testMethod void test_LSIR()
   {   createAssessmentTestData();
   	   uploadAssessmentController csv = new uploadAssessmentController();
  	   uf.idForTestCCM = ccmid;   	   
   	   csv.csvFileBody = uf.generateCSV_forLSIR();
   	   csv.csvFile = 'LSIR';
  	   test.startTest();  
   //
   //    readcsvLSCMI();
   	//   csv.readcsvLSIR();
   	   csv.readcsvFile('LSIR');
   	   test.stopTest();}

    static testMethod void testfix()
     { 
   	   uploadAssessmentController csv = new uploadAssessmentController();
   	   test.startTest();  
   	   csv.fixString('ttt,yyyy,mmmmmmmmm') ;
   	   csv.fixString('ttt,nnnn,"yyyy,oooooo,kkk"') ;
   	   test.stopTest();}
/*   
    static testMethod void test3()
     { 
   	   uploadAssessmentController csv = new uploadAssessmentController();
   	   test.startTest();  
   	   csv.fixString('ttt,nnnn,"yyyy,oooooo,kkk"') ;
   	   test.stopTest();}
  
  static testMethod void test_TABE(){
  	   createAssessmentTestData();
  	   uploadAssessmentController_new csv = new uploadAssessmentController_new();
   	   uf.idForTestCCM = ccmid;
   	   csv.csvFileBody = uf.generateCSV_forTABE(); 
   	   csv.csvFile = 'TABE';
  	   test.startTest();  
       csv.readcsvTABE();
   	   test.stopTest();} 
  */  	   
}