src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PRP Cycles</relationshipLabel>
        <relationshipName>AccountsClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intake_Date__c</fullName>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Incident_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Incident Participants</relationshipLabel>
        <relationshipName>Incident_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Date__c</fullName>
        <formula>Incident_Report__r.Incident_Date__c</formula>
        <label>Incident Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incident_Report__c</fullName>
        <label>Incident Report</label>
        <referenceTo>Incident_Report__c</referenceTo>
        <relationshipLabel>Incident Participants</relationshipLabel>
        <relationshipName>Incident_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Parent_Called__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Parent Called?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Plan</label>
        <referenceTo>Program_Plan__c</referenceTo>
        <relationshipLabel>Incident Reports</relationshipLabel>
        <relationshipName>Incident_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statement__c</fullName>
        <inlineHelpText>Record the client&apos;s statement here.</inlineHelpText>
        <label>Statement</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Incident Participant</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Incident Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Incident_Report__c.object
<CustomObject>
    <fields>
        <fullName>Degree_of_Harm_Caused__c</fullName>
        <inlineHelpText>No harm: no harm
Low harm: minor harm, first aid only
Moderate harm: moderate physical harm
Severe harm: serious physical injury</inlineHelpText>
        <label>Degree of Harm Caused</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moderate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Severe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Harm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Incident_Category__c</fullName>
        <label>Incident Category</label>
        <picklist>
            <picklistValues>
                <fullName>Threat of bodily harm to self or others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harassment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weapons possession</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assault</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victim of assault, harassment or crime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegation of abuse/neglect by parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegation of abuse/neglect by staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possession of contraband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior that raises concerns for safety</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Incident_Date__c</fullName>
        <label>Incident Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incident_Description__c</fullName>
        <label>Incident Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Participants_Involved__c</fullName>
        <inlineHelpText>List the CASES clients who were involved in any way (perpetrators, victims, witnesses, provided assistance, etc)</inlineHelpText>
        <label>Participants Involved</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Risk_of_Future_Harm__c</fullName>
        <inlineHelpText>Indicate potential for future injury (if a threat was made, etc). 
Low: low risk of complications
Medium: potential for moderate injury
High: risk of life-threatening harm</inlineHelpText>
        <label>Risk of Future Harm</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moderate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Severe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Risk of Harm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incident Report</label>
    <nameField>
        <label>Brief Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Plans</relationshipLabel>
        <relationshipName>Program_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Program_Plan__r.Client_Name__r.FirstName &amp; &apos; &apos; &amp; Program_Plan__r.Client_Name__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Lookup</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This client has not been involved in any Incidents.</errorMessage>
            <filterItems>
                <field>Incident_Participation__c.Program_Plan__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program_Plan__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Incident_Participation__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Report</label>
        <referenceTo>Incident_Report__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Plan__c</fullName>
        <label>Program Plan</label>
        <referenceTo>Program_Plan__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Progress_Note__c</fullName>
        <label>Progress Note</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>P_Note-{0000}</displayFormat>
        <label>Progress Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/incidentMethodsUnitTest.cls
@isTest (SeeAllData=true)
private class incidentMethodsUnitTest {
	
    static utilityIds utilIds = new utilityIds();
    static Account accCEP = new Account();
    static Account accClient = new Account();
    static Contact con = new Contact();
    static Case_Information__c newCaseInfo =  new Case_Information__c();	

    static testMethod void testReportandParticipantCreate() {
        
        accClient = new Account(Name='Unit Tester', RecordTypeId = utilIds.accClient);
        insert accClient;
        
        newCaseInfo = new Case_Information__c();
        newCaseInfo.Client_Account__c = accClient.Id;
        newCaseInfo.RecordTypeId = utilIds.caseInfoSupremeCourt;
        newCaseInfo.Name = '2013TN456011';
        newCaseInfo.Borough__c = 'Bronx';
        insert newCaseInfo;        
        
        con = new Contact();
        con.firstName = 'Unit';
        con.lastName = 'Tester';
        con.Drug_test_frequency__c = 'Bi-Weekly';
        con.Referral_Date__c = system.today().addDays(-5);
        con.Eligible__c = 'Yes';
        con.Interview_Acceptance_Date__c = system.today().addDays(-3);
        con.Interview_Outcome__c = 'CEP Accepts';
        con.Intake_Approved_By__c = userInfo.getUserId();
        con.Intake_Date__c = System.Today();
        con.Intake_Case__c = newCaseInfo.id;
        con.RecordTypeId = utilIds.conClient;
        con.accountId = accClient.id;    
        
        insert con;
        

        Event thisEvent = new Event();
        thisEvent.RecordTypeId = utilIds.orientationAppointment;
        thisEvent.whoId = con.Id;
        thisEvent.DurationInMinutes = 60;
        thisEvent.ActivityDate = System.Today();
        thisEvent.ActivityDateTime = System.now();
        thisEvent.Verification_Status__c = 'Attended';
        insert thisEvent;   
        
        test.startTest();
        
        Program_Plan__c pp = [select id, Client_Name__r.Id, Client_Name__r.Name from Program_Plan__c 
        					  where Client_Name__c = :con.id];
        
        Incident_Report__c ir = new Incident_Report__c();
        ir.Name = 'Test Report';
        ir.Incident_Date__c = system.Today();
        ir.Degree_of_Harm_Caused__c = 'No Harm';
        ir.Risk_of_Future_Harm__c = 'Moderate';
        ir.Incident_Category__c = 'Harassment';
        ir.Participants_Involved__c = pp.Client_Name__r.Name;
        ir.Incident_Description__c = 'Testing';
        
        insert ir;
        
        Incident_Participation__c ip = new Incident_Participation__c();
        ip.Incident_Report__c = ir.Id;
        ip.Client__c = pp.Client_Name__r.Id;
        ip.Parent_Called__c = true;
        ip.Statement__c = 'Testing';
        
        insert ip;
        
        list<Task> lstTasks = [select id, isClosed from Task where whoId = :pp.Client_Name__r.Id
        					   and RecordTypeId = :utilIds.incidentReportNoteTask and Task_Source__c = :ip.Id];
        
        //was the task created
        system.assert(lstTasks.size() == 1);
        
        Progress_Note__c pn = new Progress_Note__c();
        pn.Program_Plan__c = pp.Id;
        pn.Incident_Participant__c = ip.id;
        pn.RecordTypeId = utilIds.progressNoteIncidentReport;
        pn.Progress_Note__c = 'Test';
        
        insert pn;
        
        lstTasks = [select id from Task where whoId = :pp.Client_Name__r.id 
        					   and RecordTypeId = :utilIds.incidentReportNoteTask 
        					   and Task_Source__c = :ip.Id and isClosed = true];
        					   
        //check that task was closed
        system.assert(lstTasks.size() == 1);
        
        test.stopTest();					   
    }
}