src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Arrest_Date__c</fullName>
        <label>Arrest Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Court_Status__c</fullName>
        <description>Calculate what the actual stage is based on possible data entry combinations.

Can&apos;t include Bail Set - Bond because it defaults to 0 (not blank)</description>
        <formula>IF (NOT(ISBLANK(Sentence__c)) || NOT(ISBLANK(Sentence_Disposition_Date__c)) || Youthful_Offender_Status__c = TRUE || Intensive_Supervision_Probation__c = TRUE, &quot;Final Disposition&quot;,
     IF (NOT(ISBLANK(Indictment__c)) || NOT(ISBLANK(Indictment_Date__c)) || NOT(ISBLANK(Top_Indictment_Charge__c)), &quot;Indicted&quot;,
          IF (NOT(ISBLANK(Criminal_Court_Arraignment_Date__c)) || NOT(ISBLANK(TEXT(Detention_Status_at_CC_Arraignment__c  ))) || NOT(ISBLANK(Top_Criminal_Court_Arraignment_Charge__c)) || NOT(ISBLANK(Bail_Set_Cash__c)) ||  RIGHT(TRIM(Name), 2) &lt;&gt; &quot;NA&quot; , &quot;Arraigned CC&quot;, 
              TEXT( Arraignment_Status_CC__c ))))</formula>
        <label>Case Court Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indictment__c</fullName>
        <inlineHelpText>Two format:s are permitted  
  12345-2006   and  
  SCI12345-YYYY   where YYYY is the year</inlineHelpText>
        <label>Indictment #</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supreme_Court_Period__c</fullName>
        <defaultValue>6</defaultValue>
        <inlineHelpText>Usual period for paticiapnts referred to by Supreme Court; in months. Used to calculate Projected Exit Date by adding time to the first attended orientation date.</inlineHelpText>
        <label>Supreme Court Period</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>P_C_ID__c</fullName>
        <description>get P/C ID from contact</description>
        <formula>Client_Name__r.P_C_ID__c</formula>
        <label>P/C ID</label>
        <type>Text</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/srp_Notification_UnitTest.cls
@isTest (seeAllData=true)
private class srp_Notification_UnitTest{ 
static Id accClient = Utility_ID__c.getValues('SRP Client').RecordType_Id__c;
   static caseRelationshipFutureMethods caserel = new caseRelationshipFutureMethods();
   static utilityIds utilIDs = new utilityIds();
    static UtilityTimeMethods ut = new UtilityTimeMethods();
    static string t_timeBeg;
    static boolean bolStartTimeRequired;
    static Program_Plan__c newProgramPlan = new Program_Plan__c();
    static User userCaseCoordinator;
    static Id eventId = null;
    static Account acc1 = new Account(); 
    static Account acc2 = new Account();
    static Contact con1 = new Contact();
    static Contact con2 = new Contact();    
    static Contact con3 = new Contact();    
    static List<Event> listEvents = new List<Event>();
    static Case_Information__c Case1 =  new Case_Information__c();
    static Case_Information__c Case2 =  new Case_Information__c();

    static Event evt1 = new Event();    
    static Event evt2 = new Event();    
    static Event evt3 = new Event();    
    static List<Id> lstContacts,lstCasesIds;
    
    static List<Contact> lstContactsToInsert = new List<Contact>();
    static List<Case_Information__c> lstCasesToInsert = new List<Case_Information__c>();
    static  string sfid,sfid2,clientId2,event1,event2,repid,cname,pcid,pcid2,repid1,actionid1,actionid2,
    caseid1,caseid2,username,Supervision,IntakeNeedsAssessment,courtRecType;
    static date ctdate,ctdate2; 
    
    static void createBasicData() {
      List<RecordType> lstRecType = [Select id,developername,name from RecordType
         where developername =: 'Court_Ordered_Supervision' or 
         developername =: 'Intake_Needs_Assessment' or developername =: 'CourtDate'];
      for (integer i = 0;i < lstRecType.Size();i++){
         if (lstRecType[i].developername == 'Court_Ordered_Supervision')
            Supervision = lstRecType[i].id;
         if (lstRecType[i].developername == 'Intake_Needs_Assessment')
            IntakeNeedsAssessment = lstRecType[i].id; 
         if (lstRecType[i].developername == 'CourtDate')
            courtRecType = lstRecType[i].id;     
      }
         acc1 = new Account(Name='test1', RecordTypeId = utilIds.accClient);
        acc1.NYSID_Number__c = '12548725T';
        insert acc1;

        acc2 = new Account(Name='test2', RecordTypeId = utilIds.accClient);
        acc2.NYSID_Number__c = '12548725Q';
        insert acc2;
 
        Case1 = new Case_Information__c();
        case1.Client_Account__c = acc1.Id;
        case1.RecordTypeId = utilIds.caseInfoSupremeCourt;
        case1.Name = '2014TT456011';
        case1.supreme_court_period__c = 6;        
        case1.Borough__c = 'Bronx';
        insert case1; 
        caseid1 = case1.id;  
   
        con1 = new Contact();
        con1.firstName = 'first';
        con1.lastName = 'last';   
        con1.Client_Status__c = 'Active';  
        con1.Referral_Date__c = date.today().addDays(-20);
        con1.Current_Intake_Date__c = date.today().addDays(-20);
        con1.RecordTypeId = utilIds.conClient;
        con1.accountId = acc1.id;   
        con1.Reporting_Borough__c = 'Brooklyn';   
        con1.Intake_Approved_By__c = userInfo.getUserId();  
        con1.Interview_Outcome__c = 'CEP Accepts';
        con1.Intake_Case__c = caseid1;
        insert con1;
        sfid = con1.id;
        pcid = con1.P_C_ID__c;

  //      lstContactsToInsert.add(con1);

        case2 = new Case_Information__c();
        case2.Client_Account__c = acc1.Id;
        case2.RecordTypeId = utilIds.caseInfoSupremeCourt;
        case2.Name = '2015TT456011';
        case2.Indictment__c = '1235647899';
   //     case2.Case_Court_Status__c = 'Arraigned (Criminal Court)';      
        case2.Arrest_Date__c = date.today().addDays(-2);        
        case2.Borough__c = 'Bronx';
                                         
        insert case2;  

        Event evt = new Event();
        evt.ActivityDateTime = System.Now().addHours(-48);
        evt.ActivityDate = date.today().addDays(-2);
        evt.DurationInMinutes = 30;
        evt.WhoId = sfid;
        evt.WhatId = caseid1;
        evt.Subject = 'Call';
        evt.DurationInMinutes = 30;
        evt.Verification_Status__c = 'Unexused';
        evt.WhatId = caseid1;
        evt.WhoId = sfid;
        evt.RecordTypeId = Supervision;        
        evt.P_C_ID__c = pcid;
        evt.Verified_By__c = userName; 
        evt.Verification_Date__c = date.today();

        insert evt;
        
  
        evt1 = new Event();
        evt1.ActivityDateTime = System.Now().addHours(-24);
        evt1.ActivityDate = date.today().addDays(-1);
        evt1.DurationInMinutes = 30;
        evt1.Subject = 'Meeting';        
        evt1.Verification_Status__c = 'Unexused';
        evt1.WhatId = caseid1;
        evt1.WhoId = sfid;
        evt1.RecordTypeId = Supervision;          
        evt1.P_C_ID__c = pcid;        
         evt1.Verified_By__c = userName; 
        evt1.Verification_Date__c = date.today();
        insert evt1;
        event2 = evt1.Id;
        ctdate2 = evt1.ActivityDate;
   
        system.assert(evt1 != null);
        
        evt2 = new Event();
        evt2.Subject = 'Intake/Needs Assessment';
        evt2.ActivityDateTime = System.Now().addHours(-5);
        evt2.ActivityDate = date.today();
        evt2.DurationInMinutes = 30;
        evt2.Verification_Status__c = 'Unexused'; 
        evt2.WhatId = caseid1;
        evt2.WhoId = sfid;
        evt2.RecordTypeId = IntakeNeedsAssessment; 
        evt.P_C_ID__c = pcid;
       evt2.Verified_By__c = userName; 
        evt2.Verification_Date__c = date.today();
        insert evt2;
        
        evt3 = new Event();
        evt3.Subject = 'Court Date';
        evt3.ActivityDateTime = System.Now().addHours(+24);
        evt3.ActivityDate = date.today().addDays(+1); 
        evt3.DurationInMinutes = 30;
        evt3.Verification_Status__c = 'Not Verified';        
        evt3.WhoId = sfid;
        evt3.WhatId = caseid1;
        evt3.RecordTypeId = courtRecType;
         evt3.Verified_By__c = userName; 
        evt3.Verification_Date__c = date.today();
        insert(evt3);
   
             
   }  
    static testMethod void Test1(){  
      createBasicData();
        test.startTest();
   //     PageReference pageRef = Page.srp_NotificationPage;
    //    Test.setCurrentPageReference(pageRef);
         srp_NotificationController srp = new srp_NotificationController();
         srp.defaultSelection();
    ////    pageRef = srp.RequeryInfo();
  //      pageRef = srp.showPopup();
    //    pageRef = srp.closePopup();
   //     pageRef = srp.checkDeliqTrack();
  //      srp.lstDeliqToShow  = srp.checkDeliqTrack();
        srp.checkCourt();
        List<SelectOption> returnItems = srp.getReturnItems();
        List<SelectOption> docItems = srp.getDocumentItems();
        List<SelectOption> warrItems = srp.getWarrantItems();
        List<SelectOption> reasItems = srp.getReasonItems();
        List<SelectOption> outItems = srp.getFTAOutcomeItems();
        List<SelectOption> outlettout = srp.getLetterOutcomeItems();
        List<SelectOption> retitems = srp.getReturnItems();
        srp.sfAdmin = false;
        srp.checkDeliqTrack();
        srp.showPopup();
        srp.closePopup();
        test.stoptest();
     }
      
}