src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NYSID_Number__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Format: 8 numbers and 1 character
NNNNNNNNC (no spaces).</inlineHelpText>
        <label>NYSID #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Programs_Served__c</fullName>
        <description>Youth program participants served by this course.</description>
        <inlineHelpText>Leave blank if all youth program clients can be enrolled in this class.</inlineHelpText>
        <label>Program(s) Served</label>
        <picklist>
            <picklistValues>
                <fullName>Adolescent Portable Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BK PEAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx Choices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BX PEAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI START</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Civic Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Screening (FCS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harlem Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justice Scholars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan Choices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervised Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Case Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Alumni Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Trip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop-in Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education / Job Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim SA Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Readiness Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandatory Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stages of Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>START Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Readiness Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP One Day Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Programs_Served__c</fullName>
        <description>Set if course is for specific youth programs</description>
        <inlineHelpText>Set if course is for specific youth programs</inlineHelpText>
        <label>Program(s) Served</label>
        <picklist>
            <picklistValues>
                <fullName>Adolescent Portable Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BK PEAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx Choices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BX PEAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI START</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Civic Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Screening (FCS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harlem Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justice Scholars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan Choices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervised Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The End Date of this schedule</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The start date of this schedule</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relSessionsUserAssigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedule__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>relScheduleSessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_End__c</fullName>
        <label>Session End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Start__c</fullName>
        <label>Session Start</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SearchPortalController_UnitTest.cls
@isTest(SeeAllData=true)
private class SearchPortalController_UnitTest {

    static utilityIds utilIds = new utilityIds();
    static Account newAccountForInsertNoCase = new Account();
    static Account newAccountForInsert = new Account();
    static Case_Information__c newCaseInfo = new Case_Information__c();
    static Case_Information__c newCaseInfo2 = new Case_Information__c();
    static Contact newContactForInsert = new Contact();
    static Contact newContactForInsertNoCase = new Contact();
    static Contact newContactForInsert2 = new Contact();
    static Course__c crsTest = new Course__c();
    static Class__c clTest = new Class__c();
    static Schedule__c scTest = new Schedule__c();
    static Session__c seTest = new Session__c();
    static void createTestData()
  {     
        newAccountForInsert = new Account();
        newAccountForInsert.name = 'Dusty Bottoms';
        newAccountForInsert.RecordTypeId = utilIds.accClient;
        newAccountForInsert.NYSID_Number__c = '90978021U';
        newAccountForInsert.DOB__c = Date.newInstance(1970,1,1);
        insert newAccountForInsert;
        
        newCaseInfo = new Case_Information__c();
        newCaseInfo.Client_Account__c = newAccountforInsert.Id;
        newCaseInfo.RecordTypeId = utilIds.caseInfoCriminalCourt;
        newCaseInfo.Name = '2011BV144590';
        newCaseInfo.Borough__c = 'Bronx';
        insert newCaseInfo;
        
        newCaseInfo2 = new Case_Information__c();
        newCaseInfo2.Client_Account__c = newAccountforInsert.Id;
        newCaseInfo2.RecordTypeId = utilIds.caseInfoCriminalCourt;
        newCaseInfo2.Name = '2012SK414337';
        newCaseInfo2.Borough__c = 'Bronx';
        insert newCaseInfo2;        
        
        newContactForInsert = new Contact();
        newContactForInsert.FirstName = 'Dusty';
        newContactForInsert.lastName = 'Bottoms';
        newContactForInsert.Client_Status__c = 'Incomplete Screening';
        newContactForInsert.PRP_Status__c = 'Successful Exit';
        newContactForInsert.Case_Coordinator__c = utilIds.defaultTaskAssignedTo;
        newContactForInsert.Team_Leader__c = utilIds.defaultTaskAssignedTo;
        newContactForInsert.AccountId = newAccountForInsert.id;
        newContactForInsert.Intake_Case__c = newCaseInfo.id;
        newContactForInsert.Referral_Date__c = date.newInstance(2011,2,1);
        newContactForInsert.RecordTypeId = utilIds.conDTC; 
        insert newContactForInsert;
        
        newContactForInsert2 = new Contact();
        newContactForInsert2.FirstName = 'Dusty1';
        newContactForInsert2.lastName = 'Bottoms1';
        newContactForInsert2.Client_Status__c = 'Incomplete Screening';
        newContactForInsert.PRP_Status__c = 'Unsuccessful Exit';
        newContactForInsert2.Case_Coordinator__c = utilIds.defaultTaskAssignedTo;
        newContactForInsert2.Team_Leader__c = utilIds.defaultTaskAssignedTo;
        newContactForInsert2.AccountId = newAccountForInsert.id;
        newContactForInsert2.Intake_Case__c = newCaseInfo2.id;
        newContactForInsert2.Referral_Date__c = date.newInstance(2011,2,1);
        newContactForInsert2.RecordTypeId = utilIds.conCCM; 
        insert newContactForInsert2;
  
        crsTest = new Course__c();
        crsTest.name = 'TRP One Day Session';
        crsTest.Category__c = 'TRP One Day Session';
        crsTest.Area__c = 'Substance Abuse';
        crsTest.Programs_served__c = 'TRP';        
        insert crsTest;
        
        // Create Class
        clTest = new Class__c();
        clTest.Course__c = crsTest.Id;
      clTest.RecordTypeId = utilIds.classSingle;
        insert clTest;
        
        // Create Schedule
        scTest = new Schedule__c();
        scTest.Class__c = clTest.Id;
        scTest.Start_Date__c = System.Now().addHours(24);
        scTest.End_Date__c = System.Now().addHours(26);
        scTest.RecordTypeId = utilIDs.scheduleSingle;
        insert scTest;
        
        // Create Session
        seTest = new Session__c();
        seTest.Assigned_To__c = UserInfo.getUserId();
        seTest.Schedule__c = scTest.Id;
        seTest.Session_Start__c = scTest.Start_Date__c;
        seTest.Session_End__c = scTest.End_Date__c;
        insert seTest;
  

        newAccountForInsertNoCase = new Account();
        newAccountForInsertNoCase.name = 'Bill Adams';
        newAccountForInsertNoCase.RecordTypeId = utilIds.accClient;
        newAccountForInsertNoCase.NYSID_Number__c = '11111111K';
        newAccountForInsertNoCase.DOB__c = Date.newInstance(1970,1,1);
        insert newAccountForInsertNoCase;
  
  
        newContactForInsertNoCase = new Contact();
        newContactForInsertNoCase.FirstName = 'Bill';
        newContactForInsertNoCase.lastName = 'Adams';
        newContactForInsertNoCase.AccountId = newAccountForInsertNoCase.id;
        newContactForInsertNoCase.RecordTypeId = utilIds.conPRP; 
        newContactForInsertNoCase.Referral_Date__c = date.newInstance(2011,2,1);
        newContactForInsertNoCase.Case_Coordinator__c = utilIds.defaultTaskAssignedTo;
        newContactForInsertNoCase.Team_Leader__c = utilIds.defaultTaskAssignedTo;
        newContactForInsertNoCase.Warrant_id__c = '123564';
        insert newContactForInsertNoCase;
 
  }
   
       static testMethod void test_1() {
        createTestData();
        /*************
        * START TEST
        *************/
        test.startTest();
        
        SearchPortalController_New clsSPC = new SearchPortalController_New();
        clsSPC.strUserType = 'START';
        // GET-SET Tests
        List<SelectOption> lstTestTRPClasses = clsSPC.getlstTRPClasses();
        //System.Assert(lstTestTRPClasses.size() > 0, 'There are no future TRP classes available, this test cannot continue!');
        
        // Misc Class Tests
        clsSPC.doNothing();
        
        // Null Criteria Search
        clsSPC.doCriteriaSearch();
        System.Assert(clsSPC.strStatusMessage != null, 'The NULL Criteria search did not return a proper status message, this test cannot continue!');
        
        // Fill Invalid Criteria to create new client
        clsSPC.clsSearch.strDocket = '2000XX123456';
        clsSPC.clsSearch.strNYSID = '65485273X';
        clsSPC.clsSearch.strFirstName = 'xxxxxxxxxx';
        clsSPC.clsSearch.strLastName = 'yyyyyyyyyy';
        clsSPC.clsSearch.tskSearch.ActivityDate = System.Today().addYears(-18);
        clsSPC.doCriteriaSearch();
        // Test Search - for new client creation
        clsSPC.doCriteriaSearch();
        System.Assert(clsSPC.bolSearchExecuted && !clsSPC.bolQueryExactMatch, 'The -Create New Client- functionality will not continue because the search found an Exact Match, this test cannot continue!');       
        
        // Success test
        PageReference prTestNewClient = clsSPC.createBasicDataForStart();
        System.Assert(prTestNewClient != null, 'The -Create New Client- functionality did not create a new Account properly, this test cannot continue!');
        
        // Failure test, blank out fn/ln
        clsSPC.clsSearch.strFirstName = '';
        clsSPC.clsSearch.strLastName = '';
        prTestNewClient = clsSPC.createBasicDataForStart();
        System.Assert(prTestNewClient == null, 'The -Create New Client- functionality FAIL TEST created an account, this test cannot continue!');
        
        // Fill Valid Criteria
        clsSPC.clsSearch.clearSearchCriteria();
        clsSPC.clsSearch.strDocket = newCaseInfo.Name;
        clsSPC.clsSearch.strLastName = 'Bottoms';
        clsSPC.clsSearch.strFirstname = 'Dusty';
        
        // Full Criteria Search
        
        clsSPC.doCriteriaSearch();
  
        PageReference prTestTRP;
        // TRP - FAIL
        
       prTestTRP = clsSPC.createTRPContact();
   //     System.Assert(prTestTRP == null, 'The - Enroll TRP- functionality FAIL TEST enrolled the client properly, this test cannot continue!');
        
        // TRP - SUCCESS
 //       if (lstTestTRPClasses.Size() <> 0){
        clsSPC.clsSearch.strTRPClass = lstTestTRPClasses[0].getValue();
        clsSPC.clsSearch.strDocket = '2000XX123456';
        prTestTRP = clsSPC.createTRPContact();
    //    System.Assert(prTestTRP != null, 'The - Enroll TRP- functionality did not enroll the client properly, this test cannot continue!');
    //    }
        
        
        test.stopTest();
        /*************
        * STOP TEST
        *************/
    }
      
       static testMethod void test_3() {
        createTestData();
        test.startTest();
        PageReference ref = new PageReference('/apex/SearchPortalPage'); 
        Test.setCurrentPage(ref); 
        test.stopTest();
     }
        static testMethod void test_4() {
        createTestData();
        test.startTest();
  
        SearchPortalController_New clsSPC = new SearchPortalController_New();
        clsSPC.getUserTypes();
       
        PageReference pr;
       
        clsSPC.strUserType = 'CEP';
        pr = clsSPC.createBasicDataForCEP();
        test.stopTest();
 
    }
   
          static testMethod void test_noCaseCEP() {
        createTestData();
        /*************
        * START TEST
        *************/
        test.startTest();
        SearchPortalController_New clsSPC = new SearchPortalController_New();
        clsSPC.strUserType = 'CEP';
        // GET-SET Tests
  
        // Misc Class Tests
        clsSPC.doNothing();

        clsSPC.clsSearch.strDocket = '';
        clsSPC.clsSearch.strNYSID = '11111111K';
        clsSPC.clsSearch.strFirstName = '';
        clsSPC.clsSearch.strLastName = '';
        clsSPC.doCriteriaSearch();
        test.stopTest();
        /*************
        * STOP TEST
        *************/
    }
}