src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>Class_Description__c</fullName>
        <label>Class Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Session_On__c</fullName>
        <description>A system-maintained field that displays the first session for this Class</description>
        <label>First Session On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Instructor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A CEP staff member that will be the primary Instructor for this class.  This Instructor will also be whom the class appointments are assigned to.</description>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relUserClass1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <description>The Career Exploration Program Cycle Number</description>
        <label>Program Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if enrollment open to all programs</description>
        <inlineHelpText>Check if enrollment open to all programs</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <recordTypes>
        <fullName>Fixed</fullName>
        <active>true</active>
        <description>A fixed series of a Class</description>
        <label>Fixed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Case Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Alumni Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Trip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop-in Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education / Job Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim SA Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Readiness Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandatory Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stages of Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>START Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Readiness Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP One Day Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For validation only. If checked, Programs Served multi-select must be empty.</description>
        <inlineHelpText>Check this box if course has open enrollment (available to participants of all youth programs).</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/classMethodsUnitTests.cls
@isTest
private class classMethodsUnitTests 
{
    
    static classMethods classMethods= new classMethods();
    static Contact cont;
    static Course__c crsCEX;
    static Course__c crsGeneral;
    static Class__c clCEXStarted;
    static Class__c clCEX;
    static Class__c clGeneral;
    
    private static void establishCoreData() {
        
        Account acct = new Account();
        acct.name = 'Test';
        acct.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();  
        insert acct;
        
        cont = new Contact();
        cont.AccountId = acct.Id;
        cont.Court_Rep__c = UserInfo.getUserId();
        cont.Firstname = 'DCS';
        cont.LastName = 'APEX Test';
        cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CEP Client').getRecordTypeId();  
        cont.BirthDate = System.Today().addYears(-18);
        cont.Drug_test_frequency__c = 'Bi-Weekly';
        cont.Current_Projected_Exit_Date__c = System.Today().addDays(180);
        cont.Client_Status__c = 'Active';
        cont.Intake_Date__c = System.Today();
        cont.Current_Intake_Date__c = System.Today().addDays(-30);
        cont.Current_Orientation_Date__c = System.Today().addDays(-30);
        cont.Team_Leader__c = UserInfo.getUserId();
        insert cont;
        
        // Create Course
        crsCEX = new Course__c();
        crsCEX.Name = 'Career Ex Test Course';
        crsCEX.Area__c = 'Employment';
        crsCEX.Category__c = 'Career Exploration Training';
        crsCEX.Serves_All_Programs__c = true;        
        insert crsCEX;
        
        crsGeneral = new Course__c();
        crsGeneral.Name = 'General Test Course';
        crsGeneral.Area__c = 'Case Coordination';
        crsGeneral.Category__c = 'Mandatory Class';
        crsGeneral.Serves_All_Programs__c = true;        
        insert crsGeneral;
        
        User u = [SELECT Id FROM User WHERE Profile.Name = 'CEP - ICD Staff' AND IsActive = true LIMIT 1];
        User uEduStaff = [SELECT Id FROM User WHERE Profile.Name = 'CEP - Mental Health Staff' AND IsActive = true LIMIT 1];
        
        // Create Class
        clCEX = new Class__c();
        clCEX.Course__c = crsCEX.Id;
        clCEX.Instructor_1__c = u.Id;
        clCEX.Program_Cycle__c = 1.2;
        clCEX.First_Session_On__c = System.Today();
        clCEX.RecordTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Fixed').getRecordTypeId(); 
        insert clCEX;
        
        clCEXStarted = new Class__c();
        clCEXStarted.Course__c = crsCEX.Id;
        clCEXStarted.Instructor_1__c = u.Id;
        clCEXStarted.Program_Cycle__c = 1.2;
        clCEXStarted.First_Session_On__c = System.Today().addDays(-10);
        clCEXStarted.RecordTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Fixed').getRecordTypeId();  
        
        // Test Create Permissions - error
        System.runAs(uEduStaff) {
            try { 
                insert clCEXStarted;
            } catch(Exception e) { } 
        }
        
        upsert clCEXStarted; 
        
        clGeneral = new Class__c();
        clGeneral.Course__c = crsGeneral.Id;
        clGeneral.Instructor_1__c = u.Id;
        clGeneral.Program_Cycle__c = 1.2;
        clGeneral.First_Session_On__c = System.Today();
        clGeneral.RecordTypeId = Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Fixed').getRecordTypeId(); 
        insert clGeneral;
        
        // Test Edit Permissions - error
        clGeneral.Class_Description__c = 'Update Test';
        System.runAs(uEduStaff) {
            try {
                update clGeneral;
            } catch(Exception e) { } 
        }

        update clGeneral;
        
    }
    
    static testMethod void testStandardController() {
        
        test.startTest();
        
        establishCoreData();
        
        ApexPages.StandardController con = new ApexPages.StandardController(clCEX);
        classMethods= new classMethods(con);
        
        test.stopTest();
        
    }
    
    static testMethod void testCareerExReferral() {
        
        test.startTest();
        
        establishCoreData();
        
        classMethods.tskRef = new Task();
        classMethods.tskRef.WhoId = cont.Id;
        
        // CareerEx Referral FAIL
        ApexPages.currentPage().getParameters().put('id', clGeneral.Id);
        classMethods.clCurrent = clGeneral;
        classMethods.createCareerExReferral();
        
        classMethods.tskRef = new Task();
        classMethods.tskRef.WhoId = cont.Id;
        
        // CareerEx Referral SUCCEED 1
        ApexPages.currentPage().getParameters().put('id', clCEXStarted.Id);
        classMethods.clCurrent = clCEXStarted;
        classMethods.createCareerExReferral();
        
        classMethods.tskRef = new Task();
        classMethods.tskRef.WhoId = cont.Id;
        
        // CareerEx Referral SUCCEED 2
        ApexPages.currentPage().getParameters().put('id', clCEX.Id);
        classMethods.clCurrent = clCEX;
        classMethods.createCareerExReferral();
        
        
        test.stopTest();
        
    }
    
    static testMethod void testGeneralActions() {
        
        test.startTest();
        
        classMethods.returnToClass();
        
        test.stopTest();
        
    }
    
    static testMethod void testDeleteClass() {
        
        test.startTest();
        
        establishCoreData();
        
        User uEduStaff = [SELECT Id FROM User WHERE Profile.Name = 'CEP - ICD Staff' AND IsActive = true LIMIT 1];
        User uSysAdmin = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];
        
        // Test Delete Permissions - error
        System.runAs(uEduStaff) {
            try { 
                delete clGeneral;
            } catch(Exception e) { } 
        }
        
        // Test Delete Permissions - error
        System.runAs(uSysAdmin) {
            try { 
                delete clGeneral;
            } catch(Exception e) { } 
        }
        
        test.stopTest();
        
    }

}