src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <description>Any CASES&apos; Program participant</description>
        <label>Client</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Charges__c.object
<CustomObject>
    <description>To enter all charges for a case - arrest, plea, indictment and court related</description>
    <fields>
        <fullName>Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Charge</label>
        <referenceTo>Penal_Code__c</referenceTo>
        <relationshipLabel>Case Charges (Arrest Charge)</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Docket_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Docket #</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Charges</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Arrest Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indictment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plea/ Finding Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Charges</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Case Charges ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Borough__c</fullName>
        <label>Borough</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Top_Arrest_Charge__c</fullName>
        <label>Top Arrest Charge</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Criminal_Court_Arraignment_Charge__c</fullName>
        <label>Top Criminal Court Arraignment Charge</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Family_Court_Arraignment_Charge__c</fullName>
        <label>Top Family Court Arraignment Charge</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Indictment_Charge__c</fullName>
        <label>Top Indictment Charge</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Plea_Charge__c</fullName>
        <label>Top Plea Charge</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Penal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drug_Related__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this charge is drug related, please check off this box</inlineHelpText>
        <label>Drug Related</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Numeric_Charge_Value__c</fullName>
        <inlineHelpText>Please enter the numeric portion of the charge value. Ex. &quot;VTL 1192-1&quot; would equal 1192.1   You can enter up to three decimal places.</inlineHelpText>
        <label>Numeric Charge Value</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Violent__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this is a violent charge, please check off this box</inlineHelpText>
        <label>Violent</label>
        <type>Checkbox</type>
    </fields>
    <label>Penal Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Penal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/chargeMethodsUnitTests.cls
@isTest(SeeAllData=true)
private class chargeMethodsUnitTests 
{
    
    static Contact con = new Contact();
    static Case_Information__c newCaseInfo =  new Case_Information__c();
    static Penal_Code__c pc_10 = new Penal_Code__c();
    static Penal_Code__c pc_20 = new Penal_Code__c();
    static Penal_Code__c pc_30 = new Penal_Code__c();  
    static Id accClient = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
    static Id conTRP =Schema.SObjectType.Contact.getRecordTypeInfosByName().get('TRP Client').getRecordTypeId();
    static Id caseInfoSupremeCourt = Schema.SObjectType.Case_Information__c.getRecordTypeInfosByName().get('Supreme Court').getRecordTypeId();  
    static void initCore() 
    {
        // Stage Data
        
        pc_10 = new Penal_Code__c(Violent__c = true, Numeric_Charge_Value__c = 10, 
          Name = 'c_10', Level__c = 'V', Drug_Related__c = true, Description__c = 'test pc', 
          Degree__c = '1', Class__c = 'A');
        
        //TC = 1,910,020.000
        pc_20 = new Penal_Code__c(Violent__c = true, Numeric_Charge_Value__c = 20, 
          Name = 'c_20', Level__c = 'V', Drug_Related__c = true, Description__c = 'test pc', 
          Degree__c = '1', Class__c = 'A');
        
        pc_30 = new Penal_Code__c(Violent__c = true, Numeric_Charge_Value__c = 30, 
          Name = 'c_30', Level__c = 'V', Drug_Related__c = true, Description__c = 'test pc', 
          Degree__c = '1', Class__c = 'A');
        insert new sObject[]{pc_10, pc_20, pc_30};        
        
        //clients- accounts
        Account accClient1 = new Account(Name = 'Test Contact 1', RecordTypeId = accClient);   
        
        //dml
        insert accClient1;           
        
        //clients- contacts
        Contact c1 = new Contact(LastName = 'Test Contact 1', recordtypeid = conTRP, 
        Screening_Stage__c = 'Intake Complete', AccountId = accClient1.id);  
        
        newCaseInfo = new Case_Information__c();
        newCaseInfo.Client_Account__c = accClient1.Id;
        newCaseInfo.Name = '2013TN456011';
        newCaseInfo.Borough__c = 'Bronx';       
        newCaseInfo.RecordTypeId = caseInfoSupremeCourt;
        
        insert newCaseInfo;  
    } 
    
    
  static testMethod void testTopCharge() {
    
    initCore();
 
    Case_Charges__c c_charge = new Case_Charges__c(Docket_No__c = newCaseInfo.Id, Charge__c = pc_10.Id, Type__c = 'Arrest Charges');
    insert c_charge;
    
    System.assertEquals(1, [Select count() from Case_Charges__c WHERE Docket_No__c = :newCaseInfo.Id]);

    
    newCaseInfo = [Select Id, Top_Plea_Charge__c, Top_Indictment_Charge__c, Top_Family_Court_Arraignment_Charge__c, 
      Top_Criminal_Court_Arraignment_Charge__c, Top_Arrest_Charge__c from Case_Information__c 
      where Id = :newCaseInfo.Id];
    System.assertEquals('c_10', newCaseInfo.Top_Arrest_Charge__c);
    
    c_charge = new Case_Charges__c(Docket_No__c = newCaseInfo.Id, Charge__c = pc_20.Id, Type__c = 'Arrest Charges');
    insert c_charge;
    
    newCaseInfo = [Select Id, Top_Plea_Charge__c, Top_Indictment_Charge__c, Top_Family_Court_Arraignment_Charge__c, 
      Top_Criminal_Court_Arraignment_Charge__c, Top_Arrest_Charge__c from Case_Information__c 
      where Id = :newCaseInfo.Id];
    System.assertEquals('c_20', newCaseInfo.Top_Arrest_Charge__c);
    
    //Deleting this second charge should revert to c_10 as Top Arrest Charge
    delete c_charge;
    newCaseInfo = [Select Id, Top_Plea_Charge__c, Top_Indictment_Charge__c, Top_Family_Court_Arraignment_Charge__c, 
      Top_Criminal_Court_Arraignment_Charge__c, Top_Arrest_Charge__c from Case_Information__c 
      where Id = :newCaseInfo.Id];
    System.assertEquals('c_10', newCaseInfo.Top_Arrest_Charge__c);
    
    //Reverse true for undelete
    undelete c_charge;
    newCaseInfo = [Select Id, Top_Plea_Charge__c, Top_Indictment_Charge__c, Top_Family_Court_Arraignment_Charge__c, 
      Top_Criminal_Court_Arraignment_Charge__c, Top_Arrest_Charge__c from Case_Information__c where Id = :newCaseInfo.Id];
    System.assertEquals('c_20', newCaseInfo.Top_Arrest_Charge__c);    
    
  }//end testTopCharge
  
  //Second test for this because TopCharge test is hitting SoQL query limit
  static testMethod void testTopCharge2() {
    
    initCore();
    
    Case_Charges__c c_charge = new Case_Charges__c(Docket_No__c = newCaseInfo.Id, Charge__c = pc_10.Id, Type__c = 'Arrest Charges');
    insert c_charge;
    
    System.assertEquals(1, [Select count() from Case_Charges__c WHERE Docket_No__c = :newCaseInfo.Id]);

    
    newCaseInfo = [Select Id, Top_Plea_Charge__c, Top_Indictment_Charge__c, Top_Family_Court_Arraignment_Charge__c, 
      Top_Criminal_Court_Arraignment_Charge__c, Top_Arrest_Charge__c from Case_Information__c where Id = :newCaseInfo.Id];
    System.assertEquals('c_10', newCaseInfo.Top_Arrest_Charge__c);
    
    c_charge = new Case_Charges__c(Docket_No__c = newCaseInfo.Id, Charge__c = pc_20.Id, Type__c = 'Arrest Charges');
    insert c_charge;
    
    newCaseInfo = [Select Id, Top_Plea_Charge__c, Top_Indictment_Charge__c, Top_Family_Court_Arraignment_Charge__c, 
      Top_Criminal_Court_Arraignment_Charge__c, Top_Arrest_Charge__c from Case_Information__c where Id = :newCaseInfo.Id];
    System.assertEquals('c_20', newCaseInfo.Top_Arrest_Charge__c);
    
    //Change the Top Calc value of p_20
    pc_20.Numeric_Charge_Value__c = 1;
    update pc_20;
    
    //Top charge should recalculate
    newCaseInfo = [Select Id, Top_Plea_Charge__c, Top_Indictment_Charge__c, Top_Family_Court_Arraignment_Charge__c, 
      Top_Criminal_Court_Arraignment_Charge__c, Top_Arrest_Charge__c from Case_Information__c where Id = :newCaseInfo.Id];
    System.assertEquals('c_10', newCaseInfo.Top_Arrest_Charge__c);
    
  }//end TestPenalUpdate
}