src/objects/Address_Information__c.object
<CustomObject>
    <fields>
        <fullName>Apt_No__c</fullName>
        <label>Apt. No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Building_No__c</fullName>
        <label>Building No.</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Formula__c</fullName>
        <formula>if(isblank(Zip_Code__c),text(City__c), Text(Zip_Code__r.City__c))</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City Text</label>
        <picklist>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chestnut Ridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deer Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jersey City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mount Vernon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North Bergen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yonkers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Address Information</relationshipLabel>
        <relationshipName>Secondary_Address</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <label>Head of Household</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Lives_with__c</fullName>
        <label>Lives with</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Neighborhood__c</fullName>
        <label>Neighborhood</label>
        <picklist>
            <picklistValues>
                <fullName>Astoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auburndale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bath Beach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bathgate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Battery Park City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bay Ridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bayside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedford Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bedford Stuyvesant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belmont</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bensonhurst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boro Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Breezy Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Briarwood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brighton Beach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broad Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronxdale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn Heights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brownsville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bushwick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canarsie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll Gardens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Harlem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chelsea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinatown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Civic Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claremont</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coney Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-Op City</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State_Formula__c</fullName>
        <formula>if(isblank(Zip_Code__c),text(State__c), Text(Zip_Code__r.State__c))</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State Text</label>
        <picklist>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Jersey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Address Information</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Add-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Address Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Zip_Code_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <picklist>
            <picklistValues>
                <fullName>Bayonne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buffalo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deer Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elizabeth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elmsford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Englewood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hempstead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jackson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jersey City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Livingston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mamaroneck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mastic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Millburn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mount Vernon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paterson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secaucus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Somerville</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staten Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tarrytown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenafly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tobyhanna</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District Of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federated States Of Micronesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marshall Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Zip Code Mapping</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddressInformationMethods.cls
public with sharing class AddressInformationMethods {

    public List<Address_Information__c> newAddressInfos = new List<Address_Information__c>();

    public void validateAndUpdateContact(Map<Id, Address_Information__c> oldMap) {
        
        // This will update the Personal Information section on the Contact object
        //  if the record is set as a "Primary Address".
        
        // 3/28/13 MB: added functionality to clear contact on delete of address record
        
        Set<Id> setclientIds = new Set<Id>();
        Set<String> setZips = new Set<String>();      
        
        for(Address_Information__c add:newAddressInfos) {
        
            setclientIds.add(add.Client__c);
        }        
        
        list<Contact> lstContacts = [Select c.Lives_With__c, c.HomePhone, c.Apt_No__c, c.Building_No__c, 
        							c.City__c, c.Neighborhood__c, c.State__c, c.Street__c, c.Zip__c,
        							(select id, Apt_No__c, Building_No__c, City_Formula__c, City__c, 
        							State_Formula__c, State__c, Neighborhood__c, Street__c, 
        							Home_Phone__c, Contact_Person__c, Relation_to_Client__c, 
        							Relation_to_Client_Other__c, 
        							Contact_Work_Phone__c, Cell_Phone__c, Email__c, Zip_Code__r.Name
        							from Secondary_Address__r where Address_Type__c = 'Primary'
        							order by CreatedDate desc)
        							from Contact c Where c.Id in :setclientIds];
        
        Address_Information__c thisAddress = new Address_Information__c();
        
        for(Contact c :lstContacts) {
            
            //check for duplicate primaries
            if(c.Secondary_Address__r.size() > 1) {
            	
            	//do this because you can only add errors to records in the trigger context
            	oldMap.get(c.Secondary_Address__r[0].Id).Address_Type__c.addError('This client already has a primary'
            	+ ' address. If their primary address has changed, change the type of the other'
            	+ ' address record first.');
            } else if(c.Secondary_Address__r.size() == 0) {
            	
            	c.Apt_No__c = null;
            	c.Building_No__c = null;
            	c.City__c = null;
            	c.State__c = null;
            	c.Zip__c = null;
            	c.Neighborhood__c = null;
            	c.Street__c = null;
            	c.HomePhone = null;
            	c.Lives_With__c = null;
            	
            } else {//size = 1
            	
            	thisAddress = c.Secondary_Address__r[0];
            	
                c.Apt_No__c = thisAddress.Apt_No__c;
                c.Building_No__c = thisAddress.Building_No__c;
				if(thisAddress.City_Formula__c == null || thisAddress.City_Formula__c == '') {
					c.City__c = thisAddress.City__c;
				} else {
					c.City__c = thisAddress.City_Formula__c;
				}
				if(thisAddress.State_Formula__c == null || thisAddress.State_Formula__c == '') {
					c.State__c = thisAddress.State__c;
				} else {
					c.State__c = thisAddress.State_Formula__c;
				}	
                // 11/12/12 MB this line removed because client cell will now be updated on contact directly
                //c.Client_Cell_Phone__c = thisAddress.Client_Cell_Phone__c;
                c.Neighborhood__c = thisAddress.Neighborhood__c;
                c.Street__c = thisAddress.Street__c;
                if(thisAddress.Zip_Code__c == null) {//added 10/8/13, Zip can be null for START clients
                    c.Zip__c = null;
                } else {
                	c.Zip__c = thisAddress.Zip_Code__r.Name;
                }
                // 11/12/12 MB This field was previously updated via similar code in the ClassAddress class. That code is being removed and replicated here
                c.HomePhone = thisAddress.Home_Phone__c;
                
                if(thisAddress.Contact_Person__c != null && thisAddress.Contact_Person__c != '') {
                    c.Lives_With__c = thisAddress.Contact_Person__c + ' (' 
                     + (thisAddress.Relation_to_Client__c == 'Other' ? thisAddress.Relation_to_Client_Other__c : thisAddress.Relation_to_Client__c) 
                     + ')' + (thisAddress.Cell_Phone__c != null ? '\nCell: ' + thisAddress.Cell_Phone__c : '') +
                     + (thisAddress.Contact_Work_Phone__c != null ? '\nWork: ' + thisAddress.Contact_Work_Phone__c : '') +
                     + (thisAddress.Email__c != null ? '\nEmail: ' + thisAddress.Email__c : '');
                }
                else {
                    c.Lives_With__c = null;
                }            	
            	
            }
        }

        update lstContacts;
        
    }
}