src/objects/Administrative_Actions__c.object
<CustomObject>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Activities_Engaged_in_at_Exit__c</fullName>
        <label>Activities Engaged in at Exit</label>
        <picklist>
            <picklistValues>
                <fullName>Employed Full-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employed Part-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In HSE Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Internship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Outpatient Drug Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Outpatient MH Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Residential Drug Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Residential MH Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Vocational Training Program</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CBO_Activity__c</fullName>
        <label>CBO Activity</label>
        <picklist>
            <picklistValues>
                <fullName>Employed Full-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employed Part-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In HSE/pre-HSE Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Internship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Outpatient Drug Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Outpatient MH Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Vocational Training Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Youth Development Programming</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Administrative Action</relationshipLabel>
        <relationshipName>Administrative_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Community_Placement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Placement</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Administrative_Actions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placement_Status__c</fullName>
        <label>Placement Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Attended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Administrative Actions</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>Admin Actions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Administrative Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Portal_Filter__c.object
<CustomObject>
    <description>Used as default filters per tab for users when the access the To Do portal.</description>
    <fields>
        <fullName>CBO_Start_Date__c</fullName>
        <label>CBO - Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Portal Filters</relationshipLabel>
        <relationshipName>Portal_Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Filter</label>
    <nameField>
        <label>Portal Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/toDoPortal_cboPlacement.cls
public with sharing class toDoPortal_cboPlacement {
    
    ////////////////////////////////////
    // This class manages the "CBO Placement" page subtab on the "To Do" tab
    // Demand Chain Systems
    // Modified 20110613 AAB
    // andyb@demandchainsystems.com
    ////////////////////////////////////

    public utilityIds util = new utilityIds();
    public String selectedContact;
    public String exitAdminErrors;
    public Administrative_Actions__c exitNotificationForDisplay = new Administrative_Actions__c();
    public List<Event> eventsForDisplay = new List<Event>();
    public Portal_Filter__c thisPortalFilter {get;set;}
    
    ///////////////////////////////////
    // Class Constructors and GETers
    ///////////////////////////////////
        
    public toDoPortal_cboPlacement() { thisPortalFilter = new Portal_Filter__c(); }
    
    public String getexitAdminErrors() { return exitAdminErrors; }
    
    public String getselectedContact() { return selectedContact; }

    public void setselectedContact(String selectedContact) { this.selectedContact = selectedContact; }

    public Administrative_Actions__c getExitNotifictionDetails() { return exitNotificationForDisplay; }
    
    public List<Event> getClientEvents() { return eventsForDisplay; }
    
    public List<SelectOption> getCaseload() {
        
        // Get a list of all the contacts who have a CBO
        // task that is still open
         
        List<Task> cboTasks = [Select   Id, 
                                        WhoId,
                                        Who.name 
                                        from Task 
                                        Where isClosed = false 
                                        AND recordTypeId = :util.CBOPlacementTask  
                                        Order By Who.Name ASC LIMIT 1000];          
            
        List<SelectOption> caseLoadLists = new List<SelectOption>();
        
        for(Task thisTask:cboTasks) {

            caseLoadLists.add(new SelectOption(thisTask.WhoId,thisTask.Who.Name));
        }
                

        return caseLoadLists;
    }
    
    ///////////////////////////////////
    // Action Methods
    ///////////////////////////////////
    
    public void logSearch() {

    }       
    
    public void doNothing() {
        
        eventsForDisplay.clear();
        Boolean loadTasks = false;
        
        if(selectedContact != null) {
            
            // Added 20110613 AAB per ToDo-TasksScreenDesignSpecs
            Contact curContact = [SELECT Current_Exit_Date__c FROM Contact WHERE Id = :selectedContact];
            
            if(curContact.Current_Exit_Date__c == null) {
                System.Debug('AABTEST - NULL EXIT DATE');
                thisPortalFilter.CBO_Start_Date__c = System.Today();
            } else {
                System.Debug('AABTEST - ' + curContact.Current_Exit_Date__c);
                thisPortalFilter.CBO_Start_Date__c = curContact.Current_Exit_Date__c;   
            }
            
            thisPortalFilter.CBO_Start_Date__c = thisPortalFilter.CBO_Start_Date__c.addDays(-14);
            
            // Header Information
            List<Administrative_Actions__c> exitNotificationForDisplayList = [Select    Id, 
                                                                                        Client__c,
                                                                                        Start_Date__c,
                                                                                        Community_Placement__c,
                                                                                        Action_Date__c,
                                                                                        CBO_Activity__c,
                                                                                        Placement_Status__c,
                                                                                        Activities_Engaged_in_at_Exit__c, 
                                                                                        Client__r.Name 
                                                                                        from Administrative_Actions__c 
                                                                                        Where Client__c = :selectedContact
                                                                                        AND ( recordTypeId = :util.aaExitNotification OR  recordTypeId = :util.aaExitNotificationLocked)];
        
            // Set Info Messages for ZERO Admin Actions
            if(exitNotificationForDisplayList.size() == 0) {
                
                exitNotificationForDisplay.clear();
                exitAdminErrors = '* No Administrative Action for this Client';
            }
            
            // Set Info Messages for ONE Admin Action
            if(exitNotificationForDisplayList.size() == 1) {
            
                exitNotificationForDisplay = exitNotificationForDisplayList[0];
                exitAdminErrors = '';
                loadTasks = true;
            }
            
            // Set Info Messages for MULTIPLE Admin Actions
            if(exitNotificationForDisplayList.size() > 1) {
                
                exitAdminErrors = '* Multiple Administrative Action for this Client';
                exitNotificationForDisplay = exitNotificationForDisplayList[0];
                loadTasks = true;
            }
        
            // Query and return list of applicable Tasks
            if(loadTasks) {
                
                eventsForDisplay = [Select  Subject,
                                            Open_Date__c,
                                            
                                            Verification_Status__c,
                                            OwnerId,
                                            Instructions__c,
                                            What.Name,
                                            RecordTypeId,
                                            RecordType.Name,
                                            Owner.Name 
                                            from Event
                                            Where WhoId = :selectedContact
                                            AND Open_Date__c >= :thisPortalFilter.CBO_Start_Date__c 
                                            AND (
                                                    recordTypeId = :util.educationExternal OR
                                                    recordTypeId = :util.employmentExternal OR
                                                    recordTypeId = :util.substanceAbuseExternal OR
                                                    recordTypeId = :util.mentalHealthExternal
                                                )]; 
            }
        }
    }        
}