src/objects/Administrative_Actions__c.object
<CustomObject>
    <label>Administrative Actions</label>
    <nameField>
        <displayFormat>AA-{00000}</displayFormat>
        <label>Admin Actions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Administrative Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <description>The Career Exploration Program Cycle Number</description>
        <label>Program Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Relationships__c.object
<CustomObject>
    <description>Details relationship between warrant | program | client</description>
    <label>Program Relationships</label>
    <nameField>
        <displayFormat>PR-C{0}</displayFormat>
        <label>Program Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Progress_Note__c</fullName>
        <label>Progress Note</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>P_Note-{0000}</displayFormat>
        <label>Progress Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SF_CRW__c.object
<CustomObject>
    <label>SF CRW</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>SF CRW Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF CRWs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SF_CRW_notes__c.object
<CustomObject>
    <label>SF CRW notes</label>
    <nameField>
        <label>SF CRW notes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SF CRW notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/objectList.cls
public with sharing class objectList {
 //Public String strPassed = System.currentPagereference().getParameters().get('passPar');
// public boolean print{get;set;}
 public String val{get;set;}
 public List<String>  allObjects{get;set;}
 public String objValue{get;set;}
 public String SelectedObj{get;set;}
 public List<String> AllLabels{get;set;}
 public string env{get;set;}
 public boolean sb{get;set;}
 public List<SelectOption> objNames {get;set;}
 PageReference pageRef = ApexPages.currentPage();
 
   public class objDescription{
   public string fldName{get;set;}
   public string fldLabel{get;set;}
   public string fldType{get;set;}
   public string fieldlenght{get;set;}
   public string pklist{get;set;}
   public string fldForm{get;set;}
   public List<String> listPL{get;set;}
   public String fldDescr{get;set;}
   public integer fldNumber{get;set;}
   public String rowColor{get;set;}   
   }
public objectList(){
    objNames = 	objNames1();
   string loginname = UserInfo.getUserName();
   string s1 = loginname.substringAfterLast('.');
   if (s1 != 'org'){
   	  sb = true;
   	  env = s1;
   }	  
   else
     env= 'Production';
}
 
  public List<SelectOption> objNames1()
    {
    List<Schema.SObjectType> gd = Schema.getGlobalDescribe().Values();    
    List<SelectOption> options = new List<SelectOption>();
    options.add(new SelectOption(' Select object',' Select object'));
    options.add(new SelectOption('Contact','Contact'));
    options.add(new SelectOption('Account','Account'));
    options.add(new SelectOption('Case_Information__c','Case Information'));
    options.add(new SelectOption('Event','Event'));
    options.add(new SelectOption('Program_Cycle__c','Program Cycle'));
    options.add(new SelectOption('Administrative_Actions__c', 'Administrative Actions'));
    options.add(new SelectOption('SF_CRW__c', 'SF_CRW__c'));
    options.add(new SelectOption('SF_CRW_notes__c', 'SF_CRW_notes__c'));
    options.add(new SelectOption('Assessment__c', 'SF_CRW_notes__c'));
    options.add(new SelectOption('Program_Relationships__c', 'Program_Relationships__c'));
    options.add(new SelectOption('Progress_Note__c', 'Progress_Note__c'));
    options.add(new SelectOption('Course__c', 'Course__c'));
    options.add(new SelectOption('Class__c', 'Class__c'));
    options.add(new SelectOption('Session__c', 'Session__c'));
    options.add(new SelectOption('Enrollment__c', 'Enrollment__c'));

    options.sort();
    return options;
   }
   integer index = 0;
 //  public String pklist{get;set;}
   public  List<objDescription> lstDescr{get;set;} 
 
   public PageReference buildDescription(){
   	system.debug('\n\n\n XXX selectDockets: ' + objValue);
   	return null; 
   }
 
    public pageReference doNothing(){
   //   if (print == false)    	
   	     this.selectedObj = val;
   	//  else 
   	//     this.selectedObj = strPassed;
   	  lstDescr = buildAllLabels1();
      return null;}
      
      
   public List<objDescription> buildAllLabels1(){ 
   	  if (val == ' Select object')
   	      return null;
    	System.Debug('\n\n XXX objPassed: ' + val);
       lstDescr = new List<objDescription>();    
       objDescription Descr = new objDescription(); 	
   	List<String> AllLabels1 = new List<String>();
   	List<String> AllLabels2 = new List<String>();
   	string label, str1, str2,str3; 
    string Field;
    List<String> ListPL = new List<String>();
    string fieldtname, fieldtype,fieldlenght, type1, pklist, fldDescr, fieldLabel,fldForm;
    PicklistEntry[] picklistValues;
   	String type = selectedObj  ;  // 'Account';
    Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
    Schema.SObjectType leadSchema = schemaMap.get(type);
    Map<String, Schema.SObjectField> fieldMap = leadSchema.getDescribe().fields.getMap();
    String HelpText;
    Boolean hasHelpText;
    integer inumber = 1;
    for (String fieldName: fieldMap.keySet()) {
    	  Schema.DisplayType myType;
          Descr = new objDescription();    	
          List<Schema.Picklistentry> fld = new List<Schema.Picklistentry>();
          Descr.listPL = new List<String>();
 
          fieldname = fieldMap.get(fieldName).getDescribe().getName();
          fieldlabel = fieldMap.get(fieldName).getDescribe().getLabel();
          fieldlenght = String.ValueOf(fieldMap.get(fieldName).getDescribe().getLength());
          hasHelpText = fieldMap.get(fieldName).getDescribe().getInlineHelpText() != null;
          myType = fieldMap.get(fieldName).getDescribe().getType();
          type1 = String.ValueOf(myType).Trim();
          pklist = '';
          fldForm = '';
          ListPL = new List<String>();
          if(myType == Schema.DisplayType.Picklist){
             fld =fieldmap.get(fieldname).getDescribe().getpicklistValues();
             for(integer i = 0;i < fld.Size();i++){
                if (pklist != null){
                   if (i == fld.Size() - 1)
                      pklist = pklist + fld[i].getvalue(); 
                   else
                      pklist = pklist + fld[i].getvalue()+ ',\n';
                }
                else 
                     pklist = fld[i].getvalue() + '\n';
       //        ListPL.add(fld[i].getvalue()) ;     
             }
          }
    //   if(myType == Schema.DisplayType.TextArea)
          fldForm = fieldmap.get(fieldname).getDescribe().getCalculatedFormula();
System.Debug('\n\n XXX fieldname fldForm :' + fieldname + ' '  + fldForm);
        if (pklist <> '')
            str1 = fieldlabel + '---' + fieldname  + '---' + mytype + '---' + fieldlenght + '---' + pklist;
        else{ 
        if (fldForm <> '' && fldForm <> null){
        	str1 = fieldlabel + '---' + fieldname  + '---' + mytype + '---' + fieldlenght + '---' + fldForm;
        }
        else
            str1 = fieldlabel + '---' + fieldname  + '---' + mytype + '---' + fieldlenght;
        }         
        if (hasHelpText == true){
             HelpText = fieldMap.get(fieldName).getDescribe().getInlineHelpText().trim();
             str2 = str1 + '---' + HelpText;
        }
        else 
             str2 = str1;
     AllLabels1.add(str2);
     }

     AllLabels1.Sort();
     string fldname; 
     System.Debug('\n\n\n XXX AllLabels1: ' + AllLabels1.Size());
   String[] splitData;
   inumber = 1;
   for (integer k = 0; k < AllLabels1.size(); k++ ){
      Descr = new objDescription(); 
      splitData = AllLabels1[k].split('---');
      Descr.fldlabel = splitData[0];
      Descr.fldname = splitData[1];
  	  Descr.fldtype = splitData[2];
  	  Descr.fieldlenght = splitData[3];
  	  if (splitData.Size() > 4)
    	  Descr.pklist = splitData[4];
  	  if (splitData.Size() > 5)
    	  Descr.fldDescr = splitData[5];
      Descr.fldNumber = inumber;    	  
    	  
      if (math.MOD(inumber,2) ==1 )
	     Descr.rowColor = '#fffffe';
      else 
    	 Descr.rowColor = '#e0dfde';
     lstDescr.add(Descr);
     inumber++;
   }
     return lstDescr;
   } 
}