src/objects/Apex_Defaults__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds settings that may need to be adjusted or added to frequently (like a list of profiles or subjects).</description>
    <fields>
        <fullName>Profiles_Authorized_to_Manage_Classes_2__c</fullName>
        <label>Profiles Authorized to Manage Classes 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Profiles_Authorized_to_Manage_Classes_3__c</fullName>
        <label>Profiles Authorized to Manage Classes 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Profiles_Authorized_to_Manage_Classes__c</fullName>
        <label>Profiles Authorized to Manage Classes</label>
        <type>TextArea</type>
    </fields>
    <label>Apex Defaults</label>
</CustomObject>

src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>AreaRPT__c</fullName>
        <label>AreaRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryRPT__c</fullName>
        <label>CategoryRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Title__c</fullName>
        <description>A system-maintained field that concatenates the class name, subtitle, section, and cycle number fields. Subtitle added 2/28/13 by MB.</description>
        <formula>Course__r.Name 
+ IF(ISNULL(Subtitle__c) ,&apos;&apos;, &apos; &apos; + Subtitle__c)
+ IF(ISNULL(text(Class_Location__c)),&apos;&apos;,&apos; - &apos;+text(Class_Location__c)) 
+ IF(ISNULL(First_Session_On__c) || Record_Type_RPT__c=&apos;Ongoing&apos;,&apos;&apos;, &apos; /&apos; + TEXT(First_Session_On__c)) 
+ IF(ISNULL(Program_Cycle__c), &apos;&apos;, &apos; /&apos; + TEXT(Program_Cycle__c))</formula>
        <label>Class Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Session_On__c</fullName>
        <description>A system-maintained field that displays the first session for this Class</description>
        <label>First Session On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Instructor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A CEP staff member that will be the primary Instructor for this class.  This Instructor will also be whom the class appointments are assigned to.</description>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relUserClass1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <description>The Career Exploration Program Cycle Number</description>
        <label>Program Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Programs_Served__c</fullName>
        <description>Youth program participants served by this course.</description>
        <inlineHelpText>Leave blank if all youth program clients can be enrolled in this class.</inlineHelpText>
        <label>Program(s) Served</label>
        <picklist>
            <picklistValues>
                <fullName>Adolescent Portable Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BK PEAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronx Choices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BX PEAK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCI START</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Civic Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DTC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Screening (FCS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harlem Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Justice Scholars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manhattan Choices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non CEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens Justice Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervised Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if enrollment open to all programs</description>
        <inlineHelpText>Check if enrollment open to all programs</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Case Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Alumni Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Trip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop-in Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education / Job Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim SA Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Readiness Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandatory Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stages of Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>START Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Readiness Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP One Day Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Course_Description__c</fullName>
        <label>Course Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For validation only. If checked, Programs Served multi-select must be empty.</description>
        <inlineHelpText>Check this box if course has open enrollment (available to participants of all youth programs).</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Limits__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object is used to store criteria that limit the amount of data pulled/ updated by pages and queries, for performance purposes. The org-level values can be overriden for a user by temporarily granting them a user-level setting with expanded limits.</description>
    <fields>
        <fullName>CEXReferralWindow__c</fullName>
        <description>This value is used to calculate the number of days from the start of a class that Clients can be referred to a CEX class.</description>
        <label>CEXReferralWindow</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>System Limits</label>
</CustomObject>

src/classes/classMethods.cls
public class classMethods 
{
    ///////////////////////////////////////////
    // This method manages Classes
    // Author:  AAB / DCS
    // Created:  20110418
    ///////////////////////////////////////////

    public Apex_Defaults__c csApexDefaults = Apex_Defaults__c.getInstance();    
    public String strResult {get;set;}
    public String idClass {get;set;}
    public Integer intReferralOpen {get;set;}   
    public Class__c clCurrent {get;set;}
    public Task tskRef {get;set;}
    public System_Limits__c sd {get;set;}
    public Integer intDaysLapsed {get;set;}
    
    /////////////////////////////////////////
    // Class Constructors
    /////////////////////////////////////////
    public classMethods(ApexPages.StandardController controller) {}
    
    public classMethods() { }
    
    ///////////////////////////////////////////
    // Action Classes
    ///////////////////////////////////////////
    public void verifyCareerExReferral() 
    {
        idClass = ApexPages.currentPage().getParameters().get('id');
        System.Debug('classMethods.Constructor INFO:  idClass = ' + idClass);
        
        // Get Org System Defaults
        sd = System_Limits__c.getOrgDefaults();
        intDaysLapsed = Integer.valueOf(sd.CEXReferralWindow__c);
        
        // Get User List
        List<User> lstUsers = [SELECT Id, Name FROM User WHERE IsActive = true];
        Map<Id, User> mapUsers = new Map<Id, User>();
        for(User u : lstUsers) 
        {
            mapUsers.put(u.Id, u);
        }
        
        clCurrent = [SELECT Id, CategoryRPT__c, AreaRPT__c, Class_Title__c, Instructor_1__c, Program_Cycle__c, First_Session_On__c, RecordTypeId FROM Class__c WHERE Id = :idClass];
        
        // TEST CASE 1 - ONLY CareerEx Training Classes are eligible
        if(clCurrent.CategoryRPT__c != 'Career Exploration Training') 
        {
            // FAIL - Only class eligible for Referral are CareerEx Training
            intReferralOpen = 1;
        }
        
        // TEST CASE 1a - needs to have a schedule
        if(clCurrent.First_Session_On__c == null) 
        {
            intReferralOpen = 3;
        }
        
        // TEST CASE 2 - Class Start + 7 = no referrals can be made, return error message
        // Edited 20111109 AAB per Bug BT-271
        if(clCurrent.First_Session_On__c.AddDays(Integer.valueOf(sd.CEXReferralWindow__c)) >= System.Today()) 
        {
            // PASS - Process
            intReferralOpen = 0;
        } else {
            // FAIL - Present
            intReferralOpen = 2;
        }   
        
        // Instanciate new Task
        tskRef = new Task();
    }
    
    public PageReference createCareerExReferral() 
    {
        // Find out if there is an existing Career Ex Task
        // BT-333 Removed "AND IsClosed = false" and added Program Cycle info from the query per PA
        List<Task> lstExistingTask = [SELECT Id FROM Task 
            WHERE WhoId = :tskRef.WhoId 
            AND RecordTypeId = :Schema.SObjectType.Task.getRecordTypeInfosByName().get('Career Exploration Referral').getRecordTypeId()
            AND Program_Cycle__c = :clCurrent.Program_Cycle__c];
        if(lstExistingTask.size() > 0) 
        {
            tskRef.addError('There is already an existing Referral Task for this Client and this Cycle.  Please check your data and try again.');
            
            return null;
            
        } else {
        
            // Determine Proper Due Date
            Date dteActivityDate;
            if(System.Today() > clCurrent.First_Session_On__c) 
            {
                dteActivityDate = clCurrent.First_Session_On__c.addDays(7);
            } else {
                dteActivityDate = clCurrent.First_Session_On__c;
            }
            
            // Fill in remaining fields
            tskRef.WhatId = clCurrent.Id;
            tskRef.OwnerId = clCurrent.Instructor_1__c;
            tskRef.Subject = 'Career Exploration Referral';
            tskRef.Program_Cycle__c = clCurrent.Program_Cycle__c;
            tskRef.Class_Category__c = clCurrent.CategoryRPT__c;
            tskRef.Area__c = clCurrent.AreaRPT__c;
            tskRef.ActivityDate = dteActivityDate;
            tskRef.Open_Date__c = System.Today();
            tskRef.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Career Exploration Referral').getRecordTypeId();  
            tskRef.Automatically_Generated__c = True;
            insert tskRef;

            
            PageReference pfSuccess = new PageReference('/' + tskRef.Id + '?retURL=/' + clCurrent.Id);
            pfSuccess.setRedirect(true);
            return pfSuccess;
        }
        
        
    }
    
    public PageReference returnToClass() 
    {
        PageReference pfCancel = new PageReference('/' + idClass);
        pfCancel.setRedirect(true);
        return pfCancel;
    }
    
    /////////////////////////////////////////////////
    // Trigger-invoked Methods
    /////////////////////////////////////////////////
    
    public void classReporting(List<Class__c> lstClasses) 
    {
        System.Debug('classMethods.classReporting INFO:  Method Start');
        
        List<Id> lstCourseIds = new List<Id>();
        for(Class__c c : lstClasses) {
            lstCourseIds.add(c.Course__c);
        }
        
        // Populate Cycle Number Map (Career Ex)
        Map<Id, Integer> mapCycleNumbers = new Map<Id, Integer>();
        List<AggregateResult> lstCycle = [SELECT Course__c, MAX(Program_Cycle__c) MaxProgramCycle FROM Class__c WHERE CategoryRPT__c IN('Career Exploration Training', 'Career Exploration Support') GROUP BY Course__c];
        for(AggregateResult ar : lstCycle) 
        {
            Integer intMaxProgramCycle = Integer.valueOf(ar.get('MaxProgramCycle'));
            
            if(intMaxProgramCycle == null) 
            {
                intMaxProgramCycle = 1;
            } else {
                intMaxProgramCycle = intMaxProgramCycle + 1;
            }
            
            mapCycleNumbers.put(String.valueOf(ar.get('Course__c')), intMaxProgramCycle);
        }       
        
        List<Course__c> lstCourses = [SELECT Id, Area__c, Category__c FROM Course__c WHERE Id IN :lstCourseIds];
        
        for(Class__c c : lstClasses) {
            
            // Update Cycle Number 
            
            for(Course__c co : lstCourses) 
            {
                if(co.Id == c.Course__c) 
                {
                    System.Debug('classMethods.classReporting INFO:  Updating Area to ' + co.Area__c + ' and Category to ' + co.Category__c);
                    c.AreaRPT__c = co.Area__c;
                    c.CategoryRPT__c = co.Category__c;
                    
                    if(c.Program_Cycle__c == null && (co.Category__c == 'Career Exploration Training' || co.Category__c == 'Career Exploration Support')) 
                    {
                        c.Program_Cycle__c = mapCycleNumbers.get(co.Id);
                    }
                }
            }
        }       
    }
    
    public void createClass(List<Class__c> lstClasses) 
    {
        List<Id> lstCourseIds = new List<Id>();
        
        // TEST 1:  Only certain profiles can add Classes
        for(Class__c clAdd : lstClasses) 
        {
            if(csApexDefaults.Profiles_Authorized_to_Manage_Classes__c.contains(userInfo.getProfileId())
            || csApexDefaults.Profiles_Authorized_to_Manage_Classes_2__c.contains(userInfo.getProfileId())
            || csApexDefaults.Profiles_Authorized_to_Manage_Classes_3__c.contains(userInfo.getProfileId())) 
            {
            	//doNothing
            } else {
                clAdd.Name.addError('You are not authorized to create a Class.  Please see your manager if you feel this message is being displayed in error.');
            }
            
            lstCourseIds.add(clAdd.Course__c);
        }
        
        // Map through Course Description to Class Description - BT-220
        Map<Id, Course__c> mapCourses = new Map<Id, Course__c>([SELECT Course_Description__c, Serves_All_Programs__c, 
                                                                Programs_Served__c, Enroll_Referral_Only__c
                                                                FROM Course__c WHERE Id IN :lstCourseIds]);

        // set values on class if needed
        for(Class__c c : lstClasses) 
        {
            if(c.Class_Description__c == null || c.Class_Description__c == '') 
            {
                c.Class_Description__c = mapCourses.get(c.Course__c).Course_Description__c; 
            }
            
            if (c.Serves_All_Programs__c == false && c.Programs_Served__c == null) 
            {
                c.Serves_All_Programs__c = mapCourses.get(c.Course__c).Serves_All_Programs__c;
                c.Programs_Served__c = mapCourses.get(c.Course__c).Programs_Served__c;              
            }
            
            if (c.Enroll_Referral_Only_New__c == null) 
            {
                c.Enroll_Referral_Only_New__c = mapCourses.get(c.Course__c).Enroll_Referral_Only__c;        
            }           
        }           
    }
    
    public void editClass(List<Class__c> lstClasses) 
    {
        // TEST 1:  Only certain profiles can add Classes
        for(Class__c clEdit : lstClasses) 
        {
            // Test 1:  Profile Permissions
            if(csApexDefaults.Profiles_Authorized_to_Manage_Classes__c.contains(userInfo.getProfileId())
            || csApexDefaults.Profiles_Authorized_to_Manage_Classes_2__c.contains(userInfo.getProfileId())
            || csApexDefaults.Profiles_Authorized_to_Manage_Classes_3__c.contains(userInfo.getProfileId())) 
            {
            	//doNothing
            } else {
                clEdit.Name.addError('You are not authorized to edit a Class.  Please see your manager if you feel this message is being displayed in error.');
            }
        }
    }
    
    public void deleteClass(List<Class__c> lstClasses) 
    {
        // Get Class Ids to query for Enrollments
        List<Id> lstClassIds = new List<Id>();
        for(Class__c c : lstClasses) 
        {
            lstClassIds.add(c.Id);
        }
        
        // Get Schedules from Class
        List<Schedule__c> lstSchedules = [SELECT Id, (SELECT Id FROM relScheduleSessions__r) FROM Schedule__c WHERE Class__c IN :lstClasses];
        List<Id> lstSessionIds = new List<Id>();
        for(Schedule__c s : lstSchedules) 
        {
            for(Session__c se : s.relScheduleSessions__r) 
            {
                lstSessionIds.add(se.Id);
            }
        }
        
        // Get Events from Sessions
        List<Event> lstEvents = [SELECT WhoId, WhatId, Verification_Status__c FROM Event WHERE WhatId IN :lstSessionIds];
        List<Event> lstEventsDelete = new List<Event>();
        
        // Loop through classes
        for(Class__c clDel : lstClasses) 
        {
            // CASE 1:  Authorized Profiles only
            if(csApexDefaults.Profiles_Authorized_to_Manage_Classes__c.contains(userInfo.getProfileId())
            || csApexDefaults.Profiles_Authorized_to_Manage_Classes_2__c.contains(userInfo.getProfileId())
            || csApexDefaults.Profiles_Authorized_to_Manage_Classes_3__c.contains(userInfo.getProfileId())) 
            {
            	//doNothing
            } else {
                    clDel.Name.addError('You are not authorized to delete a Class.  Please see your manager if you feel this message is being displayed in error.');
            }
            
            // CASE 2:  Test for Clients verified for the Class
            for(Event e : lstEvents) 
            {
                // No additional scope limiting - per the requirements a Class can only have ONE schedule.  If that turns
                // out to not be the case, put additional scope limiting logic in here. 
                if(e.Verification_Status__c != 'Not Verified' && e.Verification_Status__c != 'Cancelled') {
                    clDel.Name.addError('You cannot delete this Class.  There are clients that have been verified for this Class.');
                } else {
                    lstEventsDelete.add(e);
                }
            }       
        }
        
        // Commit Lists to SFDC
        if(lstEventsDelete.size() > 0) { delete lstEventsDelete; }
        
    }

    //when a class is created and it does not have any values in Programs Served, pull the values from the Class's parent Course
    //Receives a list of classes
}