src/objects/AssessmentContainer__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AssessmentContainers</relationshipLabel>
        <relationshipName>AssessmentContainers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>assessmentCode__c</fullName>
        <label>assessmentCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>assessmentName__c</fullName>
        <label>assessmentName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>AssessmentContainer</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>assessmentContainer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AssessmentContainers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BJMHS__c.object
<CustomObject>
    <fields>
        <fullName>AssessmentContainerId__c</fullName>
        <label>AssessmentContainerId</label>
        <referenceTo>AssessmentContainer__c</referenceTo>
        <relationshipName>BJMSH</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Q1_Mind_Control__c</fullName>
        <inlineHelpText>Do you currently believe that someone can control your mind by putting thoughts into your head or taking thoughts out of your head?</inlineHelpText>
        <label>Q1 Mind Control</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Q2_Mind_Reading__c</fullName>
        <description>Do you currently feel that other people know your thoughts and can read your mind?</description>
        <inlineHelpText>Do you currently feel that other people know your thoughts and can read your mind?</inlineHelpText>
        <label>Q2 Mind Reading</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Q3_weight_Gain__c</fullName>
        <inlineHelpText>Have you currently lost or gained as much as two pounds a week for several weeks without even trying?</inlineHelpText>
        <label>Q3 weight Gain</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Q6_Feel_Sinful__c</fullName>
        <inlineHelpText>Have there currently been a few weeks when you felt like you were useless or sinful?</inlineHelpText>
        <label>Q6 Feel Sinful</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey_Notes__c</fullName>
        <description>Survey Notes</description>
        <label>Survey Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>aBJMHS</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>BJMHS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>aBJMHSs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CRAFFT__c.object
<CustomObject>
    <fields>
        <fullName>AssessmentContainerId__c</fullName>
        <label>AssessmentContainerId</label>
        <referenceTo>AssessmentContainer__c</referenceTo>
        <relationshipName>CRAFFTs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>aCRAFFT</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>CRAFFT Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>aCRAFFTs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssessmentSectionController_UnitTest.cls
@isTest (SeeAllData=true)
private class AssessmentSectionController_UnitTest{
  static testData th = new testData();
  static Contact testClient = new Contact();
   static AssessmentContainer__c cnt = new AssessmentContainer__c();
  static Map<string,string> mapAssCodePage = new Map<string,string>();
    static Map<string,string> mapNameCode  = new Map<string,string>();
    static AssessmentContainer__c cont = new AssessmentContainer__c();
    static BJMHS__c BJMHS = new BJMHS__c();
     static CRAFFT__c CRAFFT{get;set;}  
    static ID clientId,assmId,assmId1;
    private static void createTestData() {
        testClient = new Contact();
       testClient = th.client; 
       clientId = testClient.id;
       //**** BJMHS      
     cnt = new AssessmentContainer__c();
     cnt.assessmentCode__c = mapNameCode.get('BJMHS');
     cnt.assessmentName__c = 'BJMHS';
     cnt.Assessment_Date__c = date.today();
     cnt.Client__c = clientId;    
     insert cnt;   
      assmId = cnt.id;  
  
      BJMHS = new BJMHS__c(AssessmentContainerId__c = assmId,Q1_Mind_Control__c = 'Yes',Q2_Mind_Reading__c = 'Yes',Q3_weight_Gain__c = 'Yes',
      Q6_Feel_Sinful__c = 'Yes',Survey_Notes__c = 'Yes');
      insert BJMHS;
  
    //* 	CRAFFT
      cnt = new AssessmentContainer__c();
     cnt.assessmentCode__c = mapNameCode.get('CRAFFT');
     cnt.assessmentName__c = 'CRAFFT';
     cnt.Assessment_Date__c = date.today();
     cnt.Client__c = clientId;    
     insert cnt;   
     assmId1 = cnt.id;
     CRAFFT = new CRAFFT__c();
     CRAFFT.AssessmentContainerId__c = assmId1; 
     insert CRAFFT;
    }  
     static testMethod void testSection(){
     	createTestData();
 	      PageReference pageRef = Page.AssessmentSectionPage;
       Test.setCurrentPageReference(pageRef);
      ApexPages.StandardController sc = new ApexPages.standardController(testClient);
        test.startTest(); 
      AssessmentSectionController ext = new  AssessmentSectionController(sc);
      ext.contactId = clientId;
      ext.client = testClient;
       test.stopTest();    
     }
}