src/objects/Case_Charges__c.object
<CustomObject>
    <description>To enter all charges for a case - arrest, plea, indictment and court related</description>
    <fields>
        <fullName>Charge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Charge</label>
        <referenceTo>Penal_Code__c</referenceTo>
        <relationshipLabel>Case Charges (Arrest Charge)</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Docket_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Docket #</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Charges</relationshipLabel>
        <relationshipName>Case_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Arrest Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Criminal Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indictment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Court Arraignment Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plea/ Finding Charges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Charges</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Case Charges ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Arrest_Date__c</fullName>
        <label>Arrest Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Arrest_Number__c</fullName>
        <label>Arrest #</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Indictment__c</fullName>
        <inlineHelpText>Two format:s are permitted  
  12345-2006   and  
  SCI12345-YYYY   where YYYY is the year</inlineHelpText>
        <label>Indictment #</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Criminal_Court_Arraignment_Charge__c</fullName>
        <label>Top Criminal Court Arraignment Charge</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Penal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Penal Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Penal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/legalHistoryController.cls
public with sharing class legalHistoryController {
    
    public utilityIds utilIds = new utilityIds();
    public String strCase = System.currentPagereference().getParameters().get('case');  
    public String strContact = System.currentPagereference().getParameters().get('contact');  
    public Case_Information__c thisCase {get;set;}
    public Case_Charges__c arrestCharge {get;set;}
    public Case_Charges__c arraignmentCharge {get;set;} 
    public Boolean bolArrChargeMissing {get;set;}
    public String strArrCharge {get;set;}
    public list<hClass> lstCases {get;set;}
    public Contact thisContact {get;set;}
    public Boolean bolSaveSuccessful {get;set;}

    ////////////////////////////////
    // Constructor
    ////////////////////////////////
    public legalHistoryController() { 
    
        if (strCase != null){
        
        thisCase = [select id, Name, RecordTypeId,
            Indictment__c, Arrest_Date__c, Arrest_Number__c, Top_Criminal_Court_Arraignment_Charge__c
            from Case_Information__c where id = :strCase];
        
        arrestCharge = new Case_Charges__c(Docket_No__c = thisCase.Id, Type__c = 'Arrest Charges');                                                 
        
        if(thisCase.Top_Criminal_Court_Arraignment_Charge__c == null) {
                                                  
            arraignmentCharge = new Case_Charges__c(Docket_No__c = thisCase.Id, 
                Type__c = 'Criminal Court Arraignment Charges'); 
            bolArrChargeMissing = true;
        } else {
            
            strArrCharge = thisCase.Top_Criminal_Court_Arraignment_Charge__c;
            bolArrChargeMissing = false;
        }
                    
        thisContact = [select id, FirstName, Lastname, P_C_ID__c, AccountId,
            AKA_1__c, AKA_2__c, AKA_3__c, True_First_Name__c, True_Last_Name__c, True_Middle_Name__c,
            Criminal_Justice_Involvement__c, Prior_Violent_Conviction__c, 
            Prior_Violent_Conviction_Date__c, Prior_Violent_Conviction_Charge__c, Inmate_Location__c,
            Prior_Felony_Convictions__c, Prior_Misdemeanor_Convictions__c
            from Contact where id = :strContact];}   
        
        lstCases = new list<hClass>{new hClass(new Case_Information__c(), new Case_Charges__c(), new Event()), 
            new hClass(new Case_Information__c(), new Case_Charges__c(), new Event()), 
            new hClass(new Case_Information__c(), new Case_Charges__c(), new Event())};                         
    }
    
    //helper class
    
    public class hClass {
        
        public Case_Information__c hCase {get;set;}
        public Case_Charges__c hCharge {get;set;}
        public Event hCourtDate {get;set;}
        
        public hClass(Case_Information__c inputCase, Case_Charges__c inputCharge, Event inputCourtDate){                
            
            hCase = inputCase;
            hCharge = inputCharge;
            hCourtDate = inputCourtDate;
            hCourtDate.RecordTypeID = Utility_ID__c.getValues('Court Date').RecordType_Id__c;
        }
    }
    
    ////////////////////////////////
    // Action Methods
    ////////////////////////////////
    public void doNothing() { }     
    
    public pageReference saveLegalInfo() {  
            
        PageReference prRef = new PageReference('/apex/courtPortal'); 
                       
        try {
            
            update thisContact;
            
            //get level of arraignment charge (if set) before case is updated
            //so recordtype can be changed if necessary
            
            if(arraignmentCharge!= null && arraignmentCharge.Charge__c != null) {
                
                Penal_Code__c pcTemp = [select id, Level__c from Penal_Code__c
                                            where id = :arraignmentCharge.Charge__c];   
                
                if(pcTemp.Level__c == 'F') {
                    
                    thisCase.RecordTypeId = utilIds.caseInfoSupremeCourt;
                } else {
                    
                    thisCase.RecordTypeId = utilIds.caseInfoCriminalCourt;
                }
            }
            
            update thisCase;
            
            list<Case_Information__c> lstCasestoInsert = new list<Case_Information__c>();
            list<Case_Charges__c> lstChargestoInsert = new list<Case_Charges__c>();
            list<Event> lstEventstoInsert = new list<Event>();
            
            if(arrestCharge.Charge__c != null) {
                
                lstChargestoInsert.add(arrestCharge);
            }
            
            if(bolArrChargeMissing && arraignmentCharge.Charge__c != null) {
                
                lstChargestoInsert.add(arraignmentCharge);
            }            
            
            //add cases
            for(hClass hc: lstCases) {
            
                //add other cases
                if(hc.hCase.Name != null) {
                    
                    hc.hCase.RecordTypeId = utilIds.caseInfoCriminalCourt;
                    hc.hCase.Client_Account__c = thisContact.AccountId;                
                    lstCasestoInsert.add(hc.hCase);
                }           
            }
            
            //cases DML
            if(lstCasestoInsert.size() > 0) {
                
                insert lstCasestoInsert;
            } 
            
                    
            //add charges
            for(hClass hc: lstCases) {  
                            
                if(hc.hCharge.Charge__c != null) {
                    
                    hc.hCharge.Docket_No__c = hc.hCase.Id;
                    hc.hCharge.Type__c = 'Arrest Charges';
                    lstChargestoInsert.add(hc.hCharge);
                }
                
                if(hc.hCourtDate.ActivityDate != null) {
                    
                    hc.hCourtDate.whoId = thisContact.Id;
                    hc.hCourtDate.whatId = hc.hCase.Id;
                    hc.hCourtDate.ActivityDateTime = dateTime.newInstance(hc.hCourtDate.ActivityDate, time.newInstance(9,0,0,0));
                    hc.hCourtDate.EndDateTime = hc.hCourtDate.ActivityDateTime.addHours(1);
                    lstEventstoInsert.add(hc.hCourtDate);
                }
                
            }
            
            //charges DML   
            if(lstChargestoInsert.size() > 0) {
                
                insert lstChargestoInsert;
            }
            
            if(lstEventstoInsert.size() > 0) {
                
                insert lstEventstoInsert;
            }     
            
            //done!
            prRef.setRedirect(true);      
                        
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 
            'There was an error creating the new Client.  Please contact your system administrator and provide this information:  \r\r' 
            + string.valueOf(e)));
            prRef = null;
        }
        
 

        return prRef;           
        
    }
    


}