src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Master_Intake_Docket__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Intake Docket</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Client_Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Client_Account__c</valueField>
            </filterItems>
            <infoMessage>Use this field to select the primary intake case when there are multiple intake cases with a mandate, or a client is reinstated and a new case&apos;s mandate is added to the old, &quot;master&quot; docket.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Attached Dockets</relationshipLabel>
        <relationshipName>Attached_Docket</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Mandate__c</fullName>
        <inlineHelpText>Enter the mandate for the attached case. This value will be added to the client&apos;s current mandate on their contact page.</inlineHelpText>
        <label>Attached Case Mandate</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/pluginQueryAttachedMandates.cls
global class pluginQueryAttachedMandates implements Process.Plugin {

    global Process.PluginResult invoke(Process.PluginRequest prRequest) {
        
        //get contact
        String strDocket = (String) prRequest.inputParameters.get('docketId');
        
        String MandateList = '';
        Integer MandateCounter = 0;
        
        List<Case_Information__c> lstCases = [select Name, Original_Mandate__c
                                                from Case_Information__c 
                                                where Master_Intake_Docket__c = :strDocket];        
        
        for(Case_Information__c ci: lstCases) {
            
            MandateList += ci.Name + ', Mandate: ' + ci.Original_Mandate__c + '\n\n';
            MandateCounter += integer.valueOf(ci.Original_Mandate__c);
        }
        
        Map<String,Object> mapResult = new Map<String,Object>();
        
        mapResult.put('MandateList', MandateList);
        mapResult.put('MandateCounter', MandateCounter);
        
        return new Process.PluginResult(mapResult);
        
    }
    
    global Process.PluginDescribeResult describe() {
        
        Process.PluginDescribeResult pdrResult = new Process.PluginDescribeResult();
        pdrResult.Name = 'pluginQueryAttachedMandates';
        pdrResult.Tag = 'APEX Helpers - START';
        pdrResult.inputParameters = new List<Process.PluginDescribeResult.InputParameter> {
            new Process.PluginDescribeResult.inputParameter('docketId',Process.PluginDescribeResult.ParameterType.STRING, true)
        };
        pdrResult.outputParameters = new List<Process.PluginDescribeResult.OutputParameter> { 
            new Process.PluginDescribeResult.OutputParameter('MandateList',Process.PluginDescribeResult.ParameterType.STRING),
            new Process.PluginDescribeResult.OutputParameter('MandateCounter',Process.PluginDescribeResult.ParameterType.INTEGER)
        };
        
        return pdrResult;
        
    }

}