src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Bail_Recommended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bail Recommended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bail_Set_Bond__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Amount as 0-10,000,000 digits; no $ sign. For Detension status of &quot;made Bail&quot; and &quot;In On Bail&quot;</inlineHelpText>
        <label>Bail Set - Bond</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bail_Set_Cash__c</fullName>
        <inlineHelpText>Amount as 0 - 10,000,000 digits; no $ sign. For Detension status of &quot;Made Bail&quot; and &quot;In On Bail&quot;</inlineHelpText>
        <label>Bail Set - Cash</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DA_No_of_Days_DS__c</fullName>
        <label>DA No of Days DS</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DA_Offer_SRP__c</fullName>
        <description>DA offer at arraignment (SRP)</description>
        <label>DA Offer (SRP)</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Jail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>START</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Intake_Date__c</fullName>
        <label>Intake Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Judge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Judge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Judge</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Judge)</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cycle_Type__c</fullName>
        <label>Cycle Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstatement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tier Changes</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason_for_Tier_Change__c</fullName>
        <label>Reason for Tier Change</label>
        <picklist>
            <picklistValues>
                <fullName>Program</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Judge&apos;s request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intake Tier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120 Days in Cycle</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/srpOutcomeScreenCon.cls
public with sharing class srpOutcomeScreenCon 
{
	public string portalName{get;set;}
    public Event thisCourtDate {get;set;}
    public Case_Information__c thisCase {get;set;}
    public Program_Cycle__c newProgCycle {get;set;}
    public Tier__c newTier {get;set;}
    public Event nextCourtDate {get;set;}   
    public Contact thisContact {get;set;}
    public String contactID = ApexPages.currentPage().getParameters().get('contact');
    public String caseID = ApexPages.currentPage().getParameters().get('caseId');   
    public Id progCycleSRP = Utility_ID__c.getValues('SRP Program Cycle').RecordType_Id__c;
    public Id tierSRP = Utility_ID__c.getValues('SR Tier').RecordType_Id__c;    

    public srpOutcomeScreenCon() 
    {
    	 	portalName = ApexPages.currentPage().getParameters().get('portalName');
        if (contactId != null && contactId != '')
        {
            thisContact = [SELECT Id, Screening_Stage__c, Client_Status__c, FirstName, LastName, P_C_Id__c, Intake_Date__c, Current_Intake_Date__c,
                    Judge_s_Conditions__c, Screening_Outcome_srp__c, Arraignment_Outcome__c, Intake_Case__c, Ineligible_Reason_Other__c, SR_Referral__r.Supervision_Level_Recommendation__c
                    FROM Contact WHERE Id = :contactID];
            if (caseId != null && caseId != '')
            { 
                thisCase = [SELECT Id, Judge__c, Bail_Set_Cash__c, Bail_Set_Bond__c, DA_Offer_SRP__c, DA_No_of_Days_DS__c, Bail_Recommended__c 
                    FROM Case_Information__c WHERE Id = :caseId];
            }
            newProgCycle = new Program_Cycle__c();
            newTier = new Tier__c();
            thisCourtDate =new Event();
            nextCourtDate = new Event();
        }   
    }

    public pageReference saveOutcome()
    {      
        if(thisContact.Screening_Outcome_srp__c != 'Eligible' && thisContact.Screening_Outcome_srp__c !=''&& thisContact.Screening_Outcome_srp__c !=NULL)
                    thisContact.Client_Status__c = 'Never Enrolled';            
        if(thisContact.Arraignment_Outcome__c != 'Released into Supervised Release'&& thisContact.Arraignment_Outcome__c !=''&& thisContact.Arraignment_Outcome__c !=NULL)
                    thisContact.Client_Status__c = 'Never Enrolled';
        else
            if(thisContact.Screening_Outcome_srp__c == 'Eligible' 
                && thisContact.Arraignment_Outcome__c == 'Released into Supervised Release')
            {
                thisContact.Client_Status__c = 'Active';
                thisContact.Current_Intake_Date__c = thisContact.Intake_Date__c;
                newProgCycle.RecordTypeId = progCycleSRP;              
                newProgCycle.Client__c = thisContact.Id;
                newProgCycle.Cycle_Type__c = 'Intake';
                newProgCycle.Start_Date__c = thisContact.Intake_Date__c;
                insert newProgCycle;
                
                Tier__c thisTier = new Tier__c();
                thisTier.RecordTypeId = tierSRP;
                thisTier.Contact__c = thisContact.Id;
                thisTier.Program_Cycle__c = newProgCycle.Id;
                thisTier.Reason_for_Tier_Change__c = 'Intake Tier';
                thisTier.Start_Date__c = thisContact.Intake_Date__c;
                String suplvl = thisContact.SR_Referral__r.Supervision_Level_Recommendation__c;
                system.debug('suplvl: ' + suplvl);
                thisTier.Tier__c = suplvl;
                insert thisTier;
                update thisCase;
            }
        update thisContact;
        updateCourtDate();
        PageReference prRef;
        if (portalName != null)
           prRef = new PageReference('/apex/allCourtsPage');
        else
           prRef = new PageReference('/apex/courtPortal_srp');
        prRef.setRedirect(true);
        return prRef; 
                    
    }

    public void doNothing() { }

    public pageReference goPortal() 
    {
        
          PageReference prRef;
        if (portalName != null)
           prRef = new PageReference('/apex/allCourtsPage');
        else
           prRef = new PageReference('/apex/courtPortal_srp');
        prRef.setRedirect(true);
        return prRef;       
    } 
    
    
    public void updateCourtDate() 
    {
        
        if(nextCourtDate.ActivityDate != null) 
        {
            try 
            { 
                nextCourtDate.whoId = thisContact.Id;
                nextCourtDate.Subject = 'Court Date';
                nextCourtDate.RecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Court Date').getRecordTypeId();
                nextCourtDate.WhatId = thisContact.Intake_Case__c; 
                nextCourtDate.DurationInMinutes = 60;
                nextCourtDate.Court_Date_Type__c = 'Adjournment';    
                nextCourtDate.ActivityDateTime = 
                    DateTime.newInstance(nextCourtDate.ActivityDate, Time.newInstance(12,0,0,0));
                    
                insert nextCourtDate;                
            }
            catch(Exception e) 
            {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'There was an error creating the new Client.  Please contact your system administrator and provide this information:  \r\r' + string.valueOf(e)));
            }
        
        }
    }
}