src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Affiliation__c</fullName>
        <inlineHelpText>Select the organization to which this  Defense Attorney or Law Guardian belongs or select  &quot;none&quot;.</inlineHelpText>
        <label>Affiliation</label>
        <picklist>
            <picklistValues>
                <fullName>18 B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brooklyn Defenders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Defenders of Harlem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York County Defenders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queens Law Associates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The Bronx Defenders</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Defense_Attorney_Law_Guardian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Defense Attorney/ Law Guardian</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Attorney/ Law Guardian</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Defense Attorney/ Law Guardian)</relationshipLabel>
        <relationshipName>Case_Information2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Judge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Judge</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Judge</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Judge)</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PSI_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PSI Officer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Case_Information1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probation_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Probation Officer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Probation Officer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Probation Officer)</relationshipLabel>
        <relationshipName>Case_Information3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prosecutor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prosecutor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Attorney/ Law Guardian</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Information (Prosecutor)</relationshipLabel>
        <relationshipName>Case_Information4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/u_attorneyInfoCEPController.cls
public with sharing class u_attorneyInfoCEPController {
   
    public utilityIds utilIds = new utilityIds();
    public String strCase = System.currentPagereference().getParameters().get('case');  
    public String strContact = System.currentPagereference().getParameters().get('contact');  
    public Case_Information__c thisCase {get;set;}
    public Contact thisContact {get;set;}
    public Boolean bolSaveSuccessful {get;set;}


    ////////////////////////////////
    // Constructor
    ////////////////////////////////
    public u_attorneyInfoCEPController() { 
        if (strCase != null){
        
        thisCase = [select id, Defense_Attorney_Law_Guardian__c, Affiliation__c, Prosecutor__c, 
            Judge__c, Probation_Officer__c, PSI_Officer__c
            from Case_Information__c where id = :strCase];
            
        thisContact = [select id, accountId, FirstName, LastName, P_C_Id__c, Screening_Stage__c,
            Attorney_Called_On__c, Attorney_Consent__c, Attorney_Decision_Date__c, Attorney_Notes__c
            from Contact where id = :strContact];
            
        }  

    }
    
    ////////////////////////////////
    // Action Methods
    ////////////////////////////////
    public void doNothing() { }
    
    public pageReference goPortal() {
        
 //           PageReference prRef = new PageReference('/apex/courtPortal_CEP?sfdc.tabName=01rm00000004PyA');
           PageReference prRef = new PageReference('/apex/allCourtsPage');
            prRef.setRedirect(true);
            return prRef;       
    }    
    
    public pageReference goAttorneyConsent() {
        
            PageReference prRef = new PageReference('/apex/u_cepIntakeContainer?contactId=' + thisContact.Id
                + '&accountId=' + thisContact.accountId + '&intakeCaseId=' + case.id + '&stage=Attorney');
            prRef.setRedirect(true);
            return prRef;       
    }  
    
    public void updateAttorneyInfo() {
        
        try {
        
            if(thisContact.Attorney_Consent__c == 'Yes') {
            
                thisContact.Screening_Stage__c = 'Pending Interview';
            }            
            update thisCase;
            update thisContact;
            bolSaveSuccessful = true;
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'There was an error creating the new Client.  Please contact your system administrator and provide this information:  \r\r' + string.valueOf(e)));
            bolSaveSuccessful = false;
        }
        
    }
    


}