src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Detained_Dates__c.object
<CustomObject>
    <description>To record multiple detained dates and release dates for a case</description>
    <fields>
        <fullName>Contact_Detained_Dates_Lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Detained Dates</relationshipLabel>
        <relationshipName>Contact_Detained_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Released__c</fullName>
        <label>Date Released</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Detained_Date__c</fullName>
        <label>Detained Date</label>
        <type>Date</type>
    </fields>
    <label>Detained Dates</label>
    <nameField>
        <displayFormat>DD-{0000}</displayFormat>
        <label>Detained Dates ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detained Dates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/ChoicesComplTrackingUnitTest.cls
@isTest (SeeAllData=true)
private class ChoicesComplTrackingUnitTest {
    static Id curFewId_Internal = Utility_ID__c.getValues('Case Coordination').RecordType_Id__c;
    static Id afterShcoolExternalId = Utility_ID__c.getValues('Case Coordination External').RecordType_Id__c;
    static Case_Information__c caseTest = new Case_Information__c();
    static Contact contactTest = new Contact();
    static Detained_Dates__c detDates = new Detained_Dates__c();
    static UtilityIDs uid = new  UtilityIDs();
    static Id contId; 
    static date selDate;
    Static string choiceClient = uid.conBXChoices;
    static void createTestData() {
        contactTest = new Contact();
        contactTest.recordtypeid = choiceClient;
        contactTest = new Contact();
        contactTest.lastName = 'Lasttest';
        contactTest.firstName = 'firsttest';
        contactTest.current_intake_date__c = date.today() - 1;
   //     contactTest.Current_Exit_date__c = date.today() + 1;
        insert contactTest;     
        contId = contactTest.id;
        detDates = new Detained_Dates__c();
        detDates.Detained_date__c = date.today();
        detDates.date_Released__c = date.today() + 5;   
        detDates.Contact_Detained_Dates_Lookup__c = contactTest.id; 
        insert detDates;    
        
        List<Event> lstEvents = new List<Event>();
        Event evt = new Event();
        evt.recordtypeid = curFewId_Internal;
        evt.verification_status__c = 'Not Verified';
        evt.ActivityDateTime = datetime.now();
        evt.ActivityDate = date.today();
        evt.DurationInMinutes = 60;
        evt.WhoId = contactTest.id;
        evt.subject = 'Curfew';
        lstEvents.add(evt);     
        
        selDate = evt.ActivityDate;
        
        evt = new Event();
        evt.recordtypeid = curFewId_Internal;
        evt.verification_status__c = 'Not Verified';
        evt.ActivityDateTime = datetime.now();
        evt.ActivityDate = date.today();
        evt.DurationInMinutes = 60;
        evt.WhoId = contactTest.id;
        evt.subject = 'Program Reporting';
        lstEvents.add(evt);     
        insert lstEvents;
         }
     
        static testMethod void testClassInit() {
        ChoicesComplTrackingController tc = new ChoicesComplTrackingController();
        test.startTest();  
        tc.cmNames = 's';
        tc.proxyObject.activitydate = date.today();
        tc.lst2track = tc.getContacts();
        test.stopTest();}
  
        static testMethod void testMisc(){
          ChoicesComplTrackingController tc = new ChoicesComplTrackingController();
           test.starttest();
           tc.proxyObject.activitydate = date.today();
           tc.selectedDate = date.today();
           tc.lst2track = tc.getContacts();
           string dow = tc.getDayOfWeek();
           string dow1 = tc.getDateDow();
           tc.getStatusItems();
           tc.getCmItems();
           tc.doNothing();
        test.stopTest();}

       static testMethod void testMisc1(){
       	createTestData();
          ChoicesComplTrackingController tc = new ChoicesComplTrackingController();
           test.starttest();
           tc.contid = contid;
           tc.selectedDate = selDate;
           tc.createApp();
           test.stopTest();}
 }