src/objects/Case_Information__c.object
<CustomObject>
    <description>To record all cases for a client.</description>
    <fields>
        <fullName>Case_Status_at_Exit__c</fullName>
        <label>Case Status at Exit</label>
        <picklist>
            <picklistValues>
                <fullName>Sentenced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convicted, Adjourned for Sentencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disposition Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-adjudication/Pending Disposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Account__c</fullName>
        <label>Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Information</relationshipLabel>
        <relationshipName>Case_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Disposition__c</fullName>
        <label>Disposition</label>
        <picklist>
            <picklistValues>
                <fullName>Dismissal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plead Guilty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial - Dismissed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial - Acquitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial - Convicted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial - Hung Jury/Retrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sentence_Disposition_Date__c</fullName>
        <inlineHelpText>Cannot be later than today&apos;s date.</inlineHelpText>
        <label>Disposition Date</label>
        <type>Date</type>
    </fields>
    <label>Case Information</label>
    <nameField>
        <label>Docket #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Case_Status_at_Exit__c</fullName>
        <description>Case status at time of exit from current program</description>
        <label>Case Status at Exit</label>
        <picklist>
            <picklistValues>
                <fullName>Sentenced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Convicted, Adjourned for Sentencing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disposition Entered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-adjudication/Pending Disposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Relationships</relationshipLabel>
        <relationshipName>Case_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Docket__c</fullName>
        <label>Docket</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sentence_Coordinated_with_SRP__c</fullName>
        <defaultValue>&quot;No&quot;</defaultValue>
        <globalPicklist>YesNo</globalPicklist>
        <label>Sentence Coordinated with SRP</label>
        <type>Picklist</type>
    </fields>
    <label>Case Relationship</label>
    <nameField>
        <displayFormat>CR-{0}</displayFormat>
        <label>Case Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cycle_Type__c</fullName>
        <label>Cycle Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstatement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Reason_Other__c</fullName>
        <label>Exit Reason (Other)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exit_Reason__c</fullName>
        <label>Exit Reason</label>
        <picklist>
            <controllingField>Exit_Type__c</controllingField>
            <picklistValues>
                <fullName>7/30 Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternative Services Found</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospitalized - Long Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incarcerated - Long Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Follow-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Met Program Objectives/Graduation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moved out of area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Arrest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New VFO Re-Arrest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Warrant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recipient Requests Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment Failure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Probation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loss to Follow-Up/No Show for Extended Period</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exit_Type__c</fullName>
        <label>Exit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Administrative Discharge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ICM Step-Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Program_Cycle_Formula__c</fullName>
        <formula>Client__r.Most_Recent_Program_Cycle__c = Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Most Recent Program Cycle?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Tier</label>
        <referenceTo>Tier__c</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tier Changes</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Most Recent Tier?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/srp_ExitClientConExt.cls
Public class srp_ExitClientConExt 
{

    public PageReference cancel() {
        return null;
    }

    public Program_Cycle__c pcc {get;set;}
    public Case_Information__c caseInfo {get; set;}
    public Case_Relationship__c caseRel {get; set;}
    public Tier__c tier {get; set;}
    public Contact con {get; set;}
    String contactId {get;set;}


    public srp_ExitClientConExt() 
    { 
        contactId = ApexPages.currentPage().getParameters().get('Id');

        if(!String.IsBlank(contactId))
        {
        
            con = new Contact();
            con = [SELECT Id, P_C_ID__c, Intake_Case__c FROM Contact WHERE Id = :contactId];
               
            pcc = new Program_Cycle__c();
            pcc=[SELECT Id, Client__c, Start_Date__c, End_Date__c, Exit_Reason__c, Exit_Reason_Other__c, Exit_Type__c,
             Cycle_Type__c, Most_Recent_Tier__c  
             FROM Program_Cycle__c WHERE Client__c = :con.Id AND Most_Recent_Program_Cycle_Formula__c = TRUE]; 
   
            tier = new Tier__c();
            tier = [SELECT Id, End_Date__c FROM Tier__c WHERE Id = :pcc.Most_Recent_Tier__c];
           
            caseRel = new Case_Relationship__c();
system.debug('INTAKE CASE: ' + con.Intake_Case__c);
if (con.Intake_case__c != NULL)
{ 
            caseRel = [SELECT Id, Docket__c, Case_Status_at_Exit__c, Sentence_Coordinated_with_SRP__c 
                FROM Case_Relationship__c WHERE Contact__c = :con.Id AND Docket__c = :con.Intake_Case__c];
}
            caseInfo = new Case_Information__c();
            caseInfo=[SELECT Id, Name, Case_Status_at_Exit__c, Disposition__c, Client_Account__c, Sentence_Disposition_Date__c, Sentence_Type__c, Sentence__c  
                FROM Case_Information__c WHERE Id= :caseRel.Docket__c];
system.debug('CASEINFO: ' + caseInfo);

        }
    }

    public pageReference saveThis()
    {     
            con.Client_Status__c = 'Exited';
            update con;
            update caseInfo;
            upsert caseRel;
            update pcc;
            
            tier.End_Date__c = pcc.End_Date__c;
            update tier;
            return (new PageReference('/' + con.Id));  
    }
}