src/objects/Case_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Boro_Court__c</fullName>
        <formula>if (text(Docket__r.Borough__c)=&apos;Bronx&apos;,&apos;X&apos;,left(text(Docket__r.Borough__c),1)) + &apos;-&apos;+
left(Docket__r.RecordType.Name,1) + &apos;C&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Boro Court</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseBoro__c</fullName>
        <formula>text(Docket__r.Borough__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CaseBoro</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intake Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Contact__r.Name_and_P_C_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Relationships</relationshipLabel>
        <relationshipName>Case_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Docket_Indictment__c</fullName>
        <formula>if(Docket__r.Indictment__c = &apos;&apos;,Docket__r.Name, Docket__r.Indictment__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Docket Indictment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket_Name__c</fullName>
        <formula>Docket__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Docket Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Docket__c</fullName>
        <label>Docket</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Case Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <formula>Contact__r.FirstName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FirstName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Indictment__c</fullName>
        <formula>Docket__r.Indictment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Indictment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <formula>Contact__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LastName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NYSID__c</fullName>
        <formula>Contact__r.NYSID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NYSID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCID__c</fullName>
        <formula>Contact__r.P_C_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PCID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>substitute(Contact__r.RecordType.Name, &quot; Client&quot;, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lastNameSoundex__c</fullName>
        <formula>Contact__r.Last_Name_Soundex__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>lastNameSoundex</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>programId__c</fullName>
        <formula>Contact__r.Most_Recent_Program_Plan__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>programId</label>
        <type>Text</type>
    </fields>
    <label>Case Relationship</label>
    <nameField>
        <displayFormat>CR-{0}</displayFormat>
        <label>Case Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>Girl Rising, ATD or Supreme Court Boys</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_ID__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds all the record type ids</description>
    <fields>
        <fullName>RecordType_Id__c</fullName>
        <label>RecordType Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Utility ID</label>
</CustomObject>

src/classes/SearchOnMobileController.cls
public with sharing class SearchOnMobileController {
    public SearchOnMobileController(){
      
    } 
 public string searchValue{get;set;}
  public List<SelectOption> SearchItems;
   public List<SelectOption> getSearchItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Docket','Docket/Indictment'));
        options.add(new SelectOption('NYSID','NYSID'));
        options.add(new SelectOption('Name','Name'));
        return options;
   }
   public void setSearchItems(){
    SearchItems = this.SearchItems;
   } 
  string searchParameter{get;set;} 
 public string fnameValue{get;set;}   
 public string lnameValue{get;set;}   
 public string docketValue{get;set;}   
 public string nysidValue{get;set;}   


 public class clients{
    public string  cname{get;set;}
    public string  strIntakeDate{get;set;}
    public string  strExitDate{get;set;}
    public string  status{get;set;}
    public string  docket{get;set;}
    public string  nysid{get;set;}
    public string  docname{get;set;}
    public string  pcid{get;set;}
 } 
   Id accClient = Utility_Id__c.getValues('Client').RecordType_Id__c;
 
   List<clients> lstclients = new List<clients>();
   public List<clients> lstclientsShow{get;set;}
   
   clients oneclient = new clients();
   
   public void selectClient(){
   	if (lstclients != null)
   	    lstclients.clear();
   	string strWhere = '';
    string selectCases = 'SELECT Case_Type__c,Client_Name__c,Docket__c,Name,Program__c,Contact__c, ' + 
    'docket_name__c, Indictment__c, Docket_Indictment__c, Boro_Court__c,CaseBoro__c,pcid__c,nysid__c, '+ 
    'programId__c,firstname__c, lastname__c FROM Case_Relationship__c where ' ;  
       
    if (searchValue == 'Docket'){
       searchParameter = docketValue.trim().toUpperCase();
       strWhere += ' docket_name__c =:  searchParameter or Docket_Indictment__c =: searchParameter'; 
 
 //      strWhere += ' docket_name__c LIKE \'%' + searchParameter.right(6) + '%\' ' 
   //         + 'or Docket_Indictment__c =: searchParameter'; 
     }
     else{
        if (searchValue == 'Name'){
        	searchParameter = fnameValue + lnameValue;
         strWhere =  ' FirstName__c LIKE \'%' + fnameValue + '%\' ' + 
          'and  (LastName__c LIKE \'%' + lnameValue  + '%\' OR lastNameSoundex__c = \'' 
                    + Utility_Soundex.toSoundex(lnameValue) + '\')';  
        }
         
      else{
         if (searchValue == 'NYSID'){ 
            searchParameter = nysidValue.toUpperCase();
            strWhere = ' NYSID__c  =:  searchParameter'; 
  /*
            strWhere = ' NYSID__c LIKE \'%' + searchParameter + '%\' '
               + ' OR NYSID__c LIKE \'%' + searchParameter + '%\' '               
               + ' OR NYSID__c LIKE \'%' + searchParameter.mid(0,6) + '%\' '
               + ' OR NYSID__c LIKE \'%' + searchParameter.mid(1,6) + '%\' '
               + ' OR NYSID__c LIKE \'%' + searchParameter.mid(2,6) + '%\' '
               + ' OR NYSID__c LIKE \'%' + searchParameter.mid(3,6) + '%\' ';            
     */
              } }}
        Map<string,string> mapDocName = new Map<string,string>();
        Map<string,string> mapDoc = new Map<string,string>();
              Set<String> iDs = new Set<String>(); 
        if ( strWhere == '' || searchParameter == ''){
             ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.Info, 'Please enter a search criteria'));
              return;}
        else{
        	selectCases += strWhere;
        	List<Case_Relationship__c> lstSelected = Database.Query(selectCases);
        	if (lstSelected.Size() != 0){
         
               for (Case_Relationship__c cr: lstSelected){
                   iDs.add(cr.Contact__c);	
                   if (cr.Indictment__c != '' && cr.Indictment__c != null) 
                      mapDocName.put(cr.Contact__c,'Indictment');
                   else
                      mapDocName.put(cr.Contact__c,'Docket');
                   mapDoc.put(cr.Contact__c,cr.Docket_Indictment__c);
               }}
           else{
               ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.Info, 'No Clients found'));
              return;
            }     
            
              
            for (Contact c : [Select name,Client_Status__c, Next_Court_Date__c,p_c_id__c,
           Current_Intake_Date__c, current_exit_date__c,Current_Exit_Type__c,NYSID__c
           from Contact where id in: iDs and Client_Status__c != : 'Never Enrolled'   
              order by name]){
              oneclient = new clients();
              oneclient.cname = c.name;
              if (c.Current_Intake_Date__c != null)
                 oneclient.strIntakeDate = c.Current_Intake_Date__c.format();
              if (c.Current_Exit_Date__c != null)
                 oneclient.strExitDate = c.Current_Exit_Date__c.format();
              oneclient.pcid = c.P_C_ID__c;
              oneclient.docket = mapdoc.get(c.id);
         
              oneclient.docname = mapdocName.get(c.id);
              oneClient.nysid = c.NYSID__c;              
              lstclients.add(oneclient);
           }
          lstclientsShow = lstclients;
          }
          }
    //    }
     public PageReference returnToHomePage(){
     	PageReference pageRef = new PageReference('/home/home.jsp');
        pageRef.setRedirect(true);
         return pageRef;
     	
     	
     }   
   }