src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>CategoryRPT__c</fullName>
        <label>CategoryRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dummy_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, create session logic is not run on the schedule. This is used for schedules where the sessions will be added via a nightly process, such as for the DTC Groups.</description>
        <label>Dummy Schedule?</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relSessionsUserAssigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Category__c</fullName>
        <formula>TEXT( Schedule__r.Class__r.Course__r.Category__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <formula>Schedule__r.Class__r.Course__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedule__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>relScheduleSessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_End__c</fullName>
        <label>Session End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Start__c</fullName>
        <label>Session Start</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jobCreateSessionsforDTCGroups.cls
global class jobCreateSessionsforDTCGroups {
    
    global utilityIds utilIds = new utilityIds();

    global void createSessions(integer intLimit) {  
        
        //existing schedules
        list<Schedule__c> lstSchedules = [select id, Class__r.Course__r.Name from Schedule__c
            where Class__r.CategoryRPT__c = 'START Group' and Dummy_Schedule__c = true];
            
        map<string, Schedule__c> mapSchedules = new map<string,Schedule__c>();
        
        for(Schedule__c s: lstSchedules) {
            
            mapSchedules.put(s.Class__r.Course__r.Name, s);
        }               
        
        //existing sessions
        list<Session__c> lstExistingSessions = [select id, Course_Name__c, Session_Start__c from Session__c 
            where Course_Category__c = 'START Group' and Session_Start__c >= :system.now().addMonths(-6)];
            
        map<string, Session__c> mapExistingSessions = new map<string,Session__c>();
        
        for(Session__c s: lstExistingSessions) {
            
            mapExistingSessions.put(s.Course_Name__c+';;'+s.Session_Start__c.format('yyyy-MM-dd HH:mm:ss'), s);
        }   
        
        //pull events to be processed
        list<Event> lstEvents = [select id, Subject, whatId, activityDate, activityDateTime, DurationinMinutes, 
            Skip_Triggers__c, ownerId, Task_Source__c
            from Event 
            where RecordTypeId = :utilIds.courseCatalogClass and whatId = null 
            and (P_C_ID__c LIKE '%DTC%' or P_C_ID__c LIKE '%CCM%') limit :intLimit];
                                
        map<String, Event> mapUniqueSessionsNeeded = new map<String, Event>();
        
        for(Event e: lstEvents) {
            
            //create unique list of sessions using concatenated string. the string will be broken up later
            mapUniqueSessionsNeeded.put(e.Subject+';;'+e.ActivityDateTime.format('yyyy-MM-dd HH:mm:ss'), e);
        }       
        
        List<Session__c> lstSessionstoCreate = new list<Session__c>();
        
        Session__c newSession = new Session__c();               
        
        //loop through strings to see which exist
        for(string str: mapUniqueSessionsNeeded.keySet()) {
            
            if(!mapExistingSessions.containsKey(str)) {
                
                //mark event as error if schedule does not exist
                if(!mapSchedules.containsKey(str.split(';;')[0])) {
                    
                    for(Event e: lstEvents) {
                        
                        if(mapUniqueSessionsNeeded.get(str) == e) {
                        e.task_source__c = 'Error';
                        }
                    }               
                } else {
                
                    //create new session if does not exist
                    newSession = new Session__c();
                    newSession.Session_Start__c = dateTime.valueOf(str.split(';;')[1]);
                    newSession.Session_End__c = dateTime.valueOf(str.split(';;')[1]).addMinutes(15);
                    newSession.Assigned_To__c = mapUniqueSessionsNeeded.get(str).ownerId;
                    newSession.Schedule__c = mapSchedules.get(str.split(';;')[0]).id;
                
                    lstSessionstoCreate.add(newSession);
                }
            } 
        }
        
        //create new sessions
        
        if(lstSessionstoCreate.size() > 0) {
        
            insert lstSessionstoCreate;
        
            //re-query existing sessions (need course_name__c formula field)
            lstExistingSessions = [select id, Course_Name__c, Session_Start__c from Session__c 
                where Course_Category__c = 'START Group' and createdDate >= :system.today().addDays(-1)];
            
            for(Session__c s: lstExistingSessions) {
                
                mapExistingSessions.put(s.Course_Name__c+';;'+s.Session_Start__c.format('yyyy-MM-dd HH:mm:ss'), s);
            }   
        }   
        
        String strKey = '';
        
        system.debug(lstEvents);
        system.debug(mapExistingSessions);
                
        //now, assign events to new sessions    
        for(Event e: lstEvents) {
            
            strKey = e.Subject+';;'+e.ActivityDateTime.format('yyyy-MM-dd HH:mm:ss');
            
            system.debug(strKey);
            
            if(mapExistingSessions.containsKey(strKey)) {
                
                //link events to existing sessions
                e.whatID = mapExistingSessions.get(strKey).id;
                e.Skip_Triggers__c = true;
            }           
                    
        }   
        
        update lstEvents;               
                                
    }

}