src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>AreaRPT__c</fullName>
        <label>AreaRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryRPT__c</fullName>
        <label>CategoryRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Title__c</fullName>
        <description>A system-maintained field that concatenates the class name, subtitle, section, and cycle number fields. Subtitle added 2/28/13 by MB.</description>
        <formula>Course__r.Name 
+ IF(ISNULL(Subtitle__c) ,&apos;&apos;, &apos; &apos; + Subtitle__c)
+ IF(ISNULL(text(Class_Location__c)),&apos;&apos;,&apos; - &apos;+text(Class_Location__c)) 
+ IF(ISNULL(First_Session_On__c) || Record_Type_RPT__c=&apos;Ongoing&apos;,&apos;&apos;, &apos; /&apos; + TEXT(First_Session_On__c)) 
+ IF(ISNULL(Program_Cycle__c), &apos;&apos;, &apos; /&apos; + TEXT(Program_Cycle__c))</formula>
        <label>Class Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Session_On__c</fullName>
        <description>A system-maintained field that displays the first session for this Class</description>
        <label>First Session On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Instructor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A CEP staff member that will be the primary Instructor for this class.  This Instructor will also be whom the class appointments are assigned to.</description>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relUserClass1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Instructor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An additional Instructor for this class</description>
        <label>Instructor 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relUserClass2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Instructor_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An additional Instructor for this class</description>
        <label>Instructor 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relUserClass3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Session_On__c</fullName>
        <description>A system-maintained field that displays the last session for this Class</description>
        <label>Last Session On</label>
        <type>Date</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <recordTypes>
        <fullName>Ongoing</fullName>
        <active>true</active>
        <description>An ongoing instance of a Class</description>
        <label>Ongoing</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <fields>
        <fullName>Session_End__c</fullName>
        <label>Session End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Start__c</fullName>
        <label>Session Start</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/courseRoster.cls
public with sharing class courseRoster {

    ///////////////////////////////////////////
    // This method manages the Class Roster (printing)
    // Author:  AAB / DCS
    // Created:  20110421
    ///////////////////////////////////////////
    public utilityIds utilIds = new utilityIds();
    public String strClassId {get;set;}
    public String strSessionId {get;set;}
    public String strInstructors {get;set;}
    public String strSessionStart {get;set;}
    public String strClassDateRange {get;set;}
    public Class__c clCurrent {get;set;}
    public Session__c seCurrent {get;set;}
    public List<Enrollment__c> lstEnrollments {get;set;}
    public List<Event> lstEvents {get;set;}
    public List<Contact> lstContacts {get;set;}
    public List<clientsForDisplay> lstRoster = new List<clientsForDisplay>();
    
    /////////////////////////////////////////
    // Helper Classes
    /////////////////////////////////////////
    public class clientsForDisplay {
        
        public Contact con {get;set;}
        public String strVerification {get;set;}
        public String strParticipation {get;set;}
                
    }
    
    /////////////////////////////////////////
    // Class Constructors / GETers
    /////////////////////////////////////////
    public courseRoster() {
        
        strClassId = ApexPages.currentPage().getParameters().get('c');
        strSessionId = ApexPages.currentPage().getParameters().get('s');
        
        // Get Data from Passed vars
        clCurrent = [SELECT Id, AreaRPT__c, CategoryRPT__c, Class_Title__c, Instructor_1__r.Name, Instructor_2__r.Name, Instructor_3__r.Name, First_Session_On__c, Last_Session_On__c FROM Class__c WHERE Id = :strClassId];
        seCurrent = [SELECT Session_Start__c, Session_End__c FROM Session__c WHERE Id = :strSessionId];
        lstEvents = [SELECT Verification_status__c, WhoId FROM Event WHERE RecordTypeId = :utilIds.courseCatalogClass AND WhatId = :strSessionId];
        
        //added 11/5/13 MB display class start time
        strSessionStart = seCurrent.Session_Start__c.format('M/d/yyyy H:mm a');
        system.debug(clCurrent.Last_Session_On__c);
        strClassDateRange = clCurrent.First_Session_On__c.format()+' - '+(clCurrent.Last_Session_On__c==null?'Ongoing':clCurrent.Last_Session_On__c.format());
        
        // Format List of Instructors
        strInstructors = clCurrent.Instructor_1__r.Name;
        if(clCurrent.Instructor_2__r.Name != null) { strInstructors += '<br />' + clCurrent.Instructor_2__r.Name; }
        if(clCurrent.Instructor_3__r.Name != null) { strInstructors += '<br />' + clCurrent.Instructor_3__r.Name; }
        
        // Get list of Contact Ids for list
        List<Id> lstContactIds = new List<Id>();
        for(Event e : lstEvents) {
            lstContactIds.add(e.WhoId);
        }
        
        // Get Data from lists
        // QC 20120214 add ORDER BY Name to select statement - roster should print alphabetically
        lstContacts = [Select Name, Current_Projected_Exit_Date__c, Current_Exit_Date__c, Case_Coordinator__r.Name, Case_Coordinator__c, P_C_ID__c, Contract_Formula__c FROM Contact WHERE Id IN :lstContactIds ORDER BY Name ASC];
        
        // Assemble Client Roster
        for(Contact c : lstContacts) {
            
            clientsForDisplay nClientForDisplay = new clientsForDisplay();
            nClientForDisplay.con = c;
            
            for(Event e : lstEvents) {
                if(e.WhoId == c.Id) {
                    nClientForDisplay.strVerification = e.Verification_status__c;
                    break;
                }
            }
            
            lstRoster.add(nClientForDisplay);           
        }
        
    }
    
    public List<clientsForDisplay> getRoster() {
        
        return lstRoster;
        
    }

}