src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Penal_Code__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Numeric_Charge_Value__c</fullName>
        <inlineHelpText>Please enter the numeric portion of the charge value. Ex. &quot;VTL 1192-1&quot; would equal 1192.1   You can enter up to three decimal places.</inlineHelpText>
        <label>Numeric Charge Value</label>
        <precision>7</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SRP_Exclusion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Charge will exclude participation in SRP. Ideally this would be called &quot;Programs Excluded&quot; and be a multipick list.</description>
        <label>SRP Exclusion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Top_Charge_Calculation__c</fullName>
        <formula>Calc_Level__c +  Calc_Class__c  +  Numeric_Charge_Value__c +  Calc_Violent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the calculated value used in determining Top Charge</inlineHelpText>
        <label>Top Charge Calculation</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Penal Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Penal Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Referral to SRP program, before Candidate status before conversion to Contact record. Equivalent to Lead</description>
    <fields>
        <fullName>Attorney_Consent_Date__c</fullName>
        <formula>IF(TEXT(Attorney_Consent__c) = &apos;Yes&apos;, (IF(TEXT(ReferredBy__c) = &apos;DC&apos;, Referral_Date__c, Screening_Date__c)), NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attorney Consent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ContactId</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Court_Representative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Screened in court by this person</description>
        <label>Court Representative</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ineligible__c</fullName>
        <description>Eligible/Ineligible formula for SRP. Works as a formula as long as just one program.</description>
        <formula>IF( and(Age_at_Arrest_Calc__c&gt;0,Age_at_Arrest_Calc__c&lt;16),&quot;Age Ineligible&quot;,
 IF(or(  Text(Top_Arraignment_Charge_CC_lu__r.Level__c) =&quot;V&quot; , Top_Arraignment_Charge_CC_lu__r.SRP_Exclusion__c =TRUE),&quot;Charge Ineligible&quot;,
  IF( Domestic_Violence_Charges__c =TRUE,&quot;Ineligible - Domestic Violence&quot;,
    IF( left(MOCJ_Risk_Category__c,4) = &quot;High&quot;,&quot;Ineligible - MOCJ High&quot;, 
      IF(len( Ineligible_Reason__c )&gt;0,&quot;Ineligible - Other&quot;,
        IF(Len(Text(Referral_is_Ineligible__c))&gt;0,Text(Referral_is_Ineligible__c),
          IF( NOT(ISPICKVAL( ContactId__r.Screening_Outcome_srp__c , &quot;Eligible&quot;)),Text( ContactId__r.Screening_Outcome_srp__c  ),
&quot;&quot;)))))))</formula>
        <label>Ineligible?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NYSID__c</fullName>
        <label>NYSID</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RA_Total_Score_Calc__c</fullName>
        <description>Risk Assessment total score</description>
        <formula>RA_Age_Calc__c +  RA_Open_Cases_Calc__c +  RA_First_Arrest_Calc__c +  RA_Prior_Warrant_Calc__c +  RA_Misd_Conviction_Calc__c + RA_Felony_Calc__c + RA_Drug_Conviction_Calc__c + RA_Fulltime_Calc__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RA Total Score Calc</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Referral_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date referral was received/started</description>
        <label>Referral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Screening_Date__c</fullName>
        <description>Date candidate was first screened in court</description>
        <label>Screening Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>docketid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>docketid</label>
        <referenceTo>Case_Information__c</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{0}</displayFormat>
        <label>Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/xxxTabController.cls
public class xxxTabController {

    private ApexPages.StandardController sc;
    public Referral__c referral;
    public Boolean isEdit {get; set;}
    public Boolean isNew {get; set;}
    public String screeningStage {get; set;}
    public boolean input { get; set; }
    public String selecttab1 { get; set; }
    public boolean output { get; set; }
    public Map<String, String> pageParameters = new Map<String, String>();
    public String referralId {get; set;}
    public String retURL {get; set;}
    public String detectedMode {get;set;}
    public String saveNew {get;set;}
    private String selectedTab;
    public Boolean sryAgeRange {get; set;}  //in Supervised Release Youth's age range

    public MAP <id, Penal_Code__c> mapPenalCodes
    {
      get {
        if (mapPenalCodes == null)
          mapPenalCodes = new MAP<id, Penal_Code__c>(
                          [SELECT Id, Name, Class__c, Degree__c, Description__c, Level__c, 
                               SRP_Exclusion__c, Top_Charge_Calculation__c
                          FROM Penal_Code__c]);
        return mapPenalCodes;
      } set;
    }
    public String pcValue {get; set;}
    public String pcName {get;set;}
    public string pcClass {get;set;}
    public String pcSrpExclusion {get;set;}
    public String pcLevel {get;set;}
    public String pcDegree {get;set;}
    public String getPcNumChgVal() 
    {
      return null;
    }
    public xxxTabController(ApexPages.StandardController sc) 
    {
        if (!Test.isRunningTest())         
        sc.addFields(new List<String> {'ContactId__c','DocketId__c', 'Attorney_Consent_Date__c','RA_Total_Score_Calc__c', 'Ineligible__c'});
        referral = (Referral__c)sc.getRecord();
        pageParameters = ApexPages.currentPage().getParameters();
        referralId = PageParameters.get('id');
        retURL = PageParameters.get('retURL');
        saveNew = PageParameters.get('save_new');
        if (referralId == null)
            { DetectedMode = 'New';  } 
        else if (referralId != null &  retURL!= null)
            { DetectedMode = 'Edit'; } 
        else if (referralId != null & retURL == null)
            { DetectedMode = 'View'; }
        //selectedTab = 'tabOne';
        output=false;
        input=true;
        selectedTab = 'tab1';
    }

    public PageReference saveBasicInfo() 
    {
       /*  
        system.debug('Screening Stage: ' + referral.Screening_Stage__c);
        if(referral.Screening_Stage__c == '')
        {
            String nysid = referral.NYSID__c;
            nysid.toUpperCase();
            referral.NYSID__c = nysid;
            referral.Screening_Stage__c = 'Eligibility Testing';
            Upsert referral;
        }
        if basic info
                create record
                validate nysid
                check age
                change screening stage to eligibility testing
                rerender show basic view /eligibility edit

            if eligibility testing

            
            if Additional Information
            if Completed Evaluation 
    */        
        if(DetectedMode == 'New')
        {
            String nysid = referral.NYSID__c;
            referral.NYSID__c = nysid.toUpperCase();
            referral.Screening_Stage__c = 'Eligibility Testing';        
            if(referral.Screening_Date__c == NULL){referral.Screening_Date__c = referral.Referral_Date__c;}
            if(referral.Court_Representative__c == NULL){referral.Court_Representative__c = UserInfo.getUserId();}
            referral.Screening_Stage__c = 'Eligibility Testing';
            Upsert referral;
        }
        selecttab1 ='name2';
        return null;
        //PageReference referralPage = new PageReference('/'+referral.id);
        //return referralPage;
    }

    public List<Penal_Code__c> penalCodeList {
      get {
        if (penalCodeList == null) {
          penalCodeList= [select Id, Name, Description__c, Top_Charge_Calculation__c, Numeric_Charge_Value__c, SRP_Exclusion__c
            FROM Penal_Code__c Order By Name];
        }
        return penalCodeList;        
      } set;
    }
    
    public List<SelectOption> penalCodes
    {
      get{
        List<SelectOption> penalCodes = new List<SelectOption>();
        penalCodes.add(new SelectOption('',''));
        for (Penal_Code__c p : [select Id, name, description__c from Penal_Code__c order by name])
        {
            penalCodes.add(new SelectOption(p.id,p.name.trim()));
        }
        return penalCodes;
        }
      set{penalCodes = this.penalCodes;}
    }    

//////////////////////  TAB MANAGEMENT  ////////////////////////////////

  public boolean getistab1disabled() {
    return selectedTab <> 'tab1';
  }

  public boolean getistab2disabled() {
    return selectedTab <> 'tab2';
  }

  public boolean getistab3disabled() {
    return selectedTab <> 'tab3';
  }

  public boolean getistab4disabled() {
    return selectedTab <> 'tab4';
  }

  public boolean getistab5disabled() {
    return selectedTab <> 'tab5';
  }  

  public void enabletab1() {
    selectedtab = 'tab1';
  }

  public void enabletab2() {
    selectedtab = 'tab2';
  }

  public void enabletab3() {
    selectedtab = 'tab3';
  }

  public void enabletab4() {
    selectedtab = 'tab4';
  }

  public void enabletab5() {
    selectedtab = 'tab5';
  }
  public string getselectedtab() {
     return selectedtab;
  }
}