src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>Extension_Days_to_Generate__c</fullName>
        <defaultValue>8</defaultValue>
        <description>This field will be used to extend and ongoing class by a set number of days</description>
        <label>Extension Days to Generate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months_of_Sessions_to_Generate__c</fullName>
        <description>This field is used to initially (on creation) generate the sessions for ongoing classes only.  It will generate classes from the start date of the class the first time; so if the user enters 2 months, then it will be 2 months from the start date.</description>
        <label>Months of Sessions to Generate</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_Type_RPT__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type RPT</label>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <recordTypes>
        <fullName>Fixed</fullName>
        <active>true</active>
        <description>A fixed series of a Class</description>
        <label>Fixed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>AutoExtendFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AutoExtendFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Change_Schedule_As_Of__c</fullName>
        <description>Set this field if you are making changes to an active schedule.  All session dates equal to or greater to the value in this field will be modified</description>
        <inlineHelpText>Set this field if you are making changes to an active schedule.  All session dates equal to or greater to the value in this field will be modified</inlineHelpText>
        <label>Change Schedule As Of</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The End Date of this schedule</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Extension_Days_to_Generate__c</fullName>
        <defaultValue>8</defaultValue>
        <label>Extension Days to Generate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Friday_End_Time__c</fullName>
        <label>Friday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Friday_Start_Time__c</fullName>
        <label>Friday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Friday</description>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monday_End_Time__c</fullName>
        <label>Monday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Monday_Start_Time__c</fullName>
        <label>Monday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Monday</description>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Months_of_Sessions_to_Generate__c</fullName>
        <label>Months of Sessions to Generate</label>
        <picklist>
            <picklistValues>
                <fullName>2</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Original_End_Date__c</fullName>
        <label>Original End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Original_Start_Date__c</fullName>
        <label>Original Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Record_Type_RPT__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Saturday_End_Time__c</fullName>
        <label>Saturday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Saturday_Start_Time__c</fullName>
        <label>Saturday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Saturday</description>
        <label>Saturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Single_Session_Ongoing__c</fullName>
        <description>If ongoing single session class then skip jobAutoextendSchedule</description>
        <formula>TEXT(Class__r.Default_Ending_Session__c)</formula>
        <label>Single Session Ongoing</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The start date of this schedule</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sunday_End_Time__c</fullName>
        <label>Sunday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sunday_Start_Time__c</fullName>
        <label>Sunday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Sunday</description>
        <label>Sunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday_End_Time__c</fullName>
        <label>Thursday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Thursday_Start_Time__c</fullName>
        <label>Thursday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Thursday</description>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday_End_Time__c</fullName>
        <label>Tuesday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Tuesday_Start_Time__c</fullName>
        <label>Tuesday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Tuesday</description>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UI_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UI_Start_Date__c</fullName>
        <description>This is used by the New Schedule VF page</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Wednesday_End_Time__c</fullName>
        <label>Wednesday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Wednesday_Start_Time__c</fullName>
        <label>Wednesday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Wednesday</description>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jobAutoExtendSchedule.cls
global class jobAutoExtendSchedule implements Database.Batchable<SObject> {
     
    global String query;
    global utilityIds clsUtilIds = new utilityIds();    
    global List<SObject> glstJobRecords;
    
    //constructor
    global jobAutoExtendSchedule() 
    {
        //20160303 EBG/DCS - fixed syntax error in query (missing comma after Single_Session_Ongoing__c) and removed filter on same field
        //build the query to find all rules we are to monitor for required workflows, and create a case for each rule
        String strQuery = 'SELECT ';
                    strQuery += 'UI_Start_Date__c, UI_End_Date__c, Record_Type_RPT__c, RecordTypeId, ';
                    strQuery += 'SystemModstamp, Start_Date__c, Original_Start_Date__c, Original_End_Date__c, ';
                    strQuery += 'Name, Months_of_Sessions_to_Generate__c, LastModifiedDate, LastModifiedById, LastActivityDate, ';
                    strQuery += 'IsDeleted, Id, Extension_Days_to_Generate__c, End_Date__c, CreatedDate, CreatedById, Class__c, ';
                    strQuery += 'Change_Schedule_As_Of__c, AutoExtendFlag__c, Single_Session_Ongoing__c, ';
                    strQuery += 'Monday__c, Monday_Start_Time__c, Monday_End_Time__c, ';
                    strQuery += 'Tuesday__c, Tuesday_Start_Time__c, Tuesday_End_Time__c, ';
                    strQuery += 'Wednesday__c, Wednesday_Start_Time__c, Wednesday_End_Time__c, ';
                    strQuery += 'Thursday__c, Thursday_Start_Time__c, Thursday_End_Time__c, ';
                    strQuery += 'Friday__c, Friday_Start_Time__c, Friday_End_Time__c, ';
                    strQuery += 'Saturday__c, Saturday_Start_Time__c, Saturday_End_Time__c, ';
                    strQuery += 'Sunday__c, Sunday_Start_Time__c, Sunday_End_Time__c ';
                    strQuery += 'FROM Schedule__c s ';
                    strQuery += 'WHERE s.RecordTypeId = \'' + clsUtilIds.scheduleOngoing + '\' '; 
                    strQuery += 'AND s.End_Date__c > ' + system.now().format('yyyy-MM-dd') + 'T00:00:00Z';
        system.debug('\nstrQuery: ' + strQuery + '\n');        
        query = strQuery;
    }
    
    
    ////////////////////////////////////////////////
    //base method that runs when the class is instantiated.  Its return value is sent to the "execute" routine
    ////////////////////////////////////////////////
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        system.debug('\n\n******Inside start.\n');
        system.debug('\n\n******Inside start.  query:\n' + query + '\n*********\n');
      
        return Database.getQueryLocator(query);
    }


    ////////////////////////////////////////////////
    // EXECUTE
    ////////////////////////////////////////////////
    global void execute(Database.BatchableContext BC, List<SObject> jobRecords) 
    {
        system.debug('Inside execute.');
        //the results of the query are returned in a list of SObjects, so as we process each record we need to 
        //convert it to a hard typed variable
        glstJobRecords = jobRecords;

        List<Schedule__c> lstSchedulesExtend = new List<Schedule__c>();
        
        // Loop through Schedule__c records and look for any end dates that are 30 days out, then extend by 8 days
        system.debug('glstJobRecords');
        system.debug(glstJobRecords);
        for (SObject jr : glstJobRecords) 
        {
            Schedule__c s = (Schedule__c)jr;
            
            System.Debug('**** clsScheduleMethods.autoExtendOngoingClasses INFO:  Checking ScheduleId: ' + s.Id + ' if End_Date__c is <= today (' + s.End_Date__c.addDays(-30) + ')');
            
            if(s.End_Date__c.addDays(-30) <= System.Today()) 
            {
                System.Debug('**** clsScheduleMethods.autoExtendOngoingClasses INFO:  Extending ScheduleId: ' + s.Id + ' by ' + s.Extension_Days_To_Generate__c + ' days');
                
                //20160310 EBG/DCS - set Change Schedule As Of to one day after the current value and then extend the class.  Do this because
                //we don't want events for sessions already created through the end of the schedule to be deleted
                //s.Change_Schedule_As_Of__c = System.Today();
                Datetime dttChangeDate = s.End_Date__c.addDays(1);
                s.Change_Schedule_As_Of__c = Date.newInstance(dttChangeDate.year(), dttChangeDate.month(), dttChangeDate.day());
                s.End_Date__c = s.End_Date__c.addDays(Integer.valueOf(s.Extension_Days_To_Generate__c));
                lstSchedulesExtend.add(s);
            }
        }

        system.debug('lstSchedulesExtend' + lstSchedulesExtend.size());
        if(lstSchedulesExtend.size() > 0) { update lstSchedulesExtend; }

    }

    
    ////////////////////////////////////////////////
    // FINISH
    ////////////////////////////////////////////////
    global void finish(Database.BatchableContext BC)
    {

        //get the custom settings for the notification process
        //Automated_Notification_Settings__c cstNotif = Automated_Notification_Settings__c.getInstance();
        //String strAdminEmail = cstNotif.Missing_Email_Admin_Address__c;
        String strAdminEmail = 'qcushing@cases.org';
        
        // Get the ID of the AsyncApexJob representing this batch job
        // from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [Select Id
                                , CompletedDate
                                , Status
                                , ExtendedStatus
                                , JobType
                                , NumberOfErrors
                                , JobItemsProcessed
                                , TotalJobItems 
                            from AsyncApexJob 
                            where Id = :BC.getJobId()];
        
        // Send an email to the admin notifying of job failure.
        String strSubject = '';
        
        if (a.NumberOfErrors > 0) 
        {
            strSubject = 'Error in Scheduled Routine : jobAutoExtendSchedule';
        } else {
            strSubject = 'SUCCESS Scheduled Routine : jobAutoExtendSchedule';
        }
        
        // Send Email on Completion
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {strAdminEmail};
        mail.setToAddresses(toAddresses);
        mail.setSubject(strSubject);
        String strBody = 'The batch Apex job processed ' + a.TotalJobItems +' batches with '+ a.NumberOfErrors + ' failures.\n' +
                        '\nCompletedDate: ' + a.CompletedDate +
                        '\nStatus: ' + a.Status +
                        '\nExtendedStatus: ' + a.ExtendedStatus +
                        '\nJobType: ' + a.JobType +
                        '\nJobItemsProcessed: ' + a.JobItemsProcessed;
                        
        mail.setPlainTextBody(strBody);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
        //cheating for unit test purposes 
        Integer i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        i = 0;
        
    }
}