src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if enrollment open to all programs</description>
        <inlineHelpText>Check if enrollment open to all programs</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Case Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Alumni Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Trip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop-in Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education / Job Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim SA Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Readiness Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandatory Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stages of Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>START Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Readiness Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP One Day Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For validation only. If checked, Programs Served multi-select must be empty.</description>
        <inlineHelpText>Check this box if course has open enrollment (available to participants of all youth programs).</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Friday</description>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Monday</description>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Saturday</description>
        <label>Saturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Sunday</description>
        <label>Sunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Thursday</description>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Tuesday</description>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UI_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UI_Start_Date__c</fullName>
        <description>This is used by the New Schedule VF page</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Wednesday</description>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedule__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>relScheduleSessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/scheduleNewInstanceUnitTests.cls
@isTest(SeeAllData=True)
private class scheduleNewInstanceUnitTests {

    ///////////////////////////////////////////
    // This test method covers scheduleNewInstance
    // Created 20110706 AAB / DCS
    ///////////////////////////////////////////
    
    static utilityIds utilIds = new utilityIds();
    static Course__c crsTest;
    static Class__c clTest;
    static Schedule__c scTest;
    static Contact conTest;
    static Enrollment__c enrTest;
    static Session__c seTest;
    static Event evt1;
    static Event evt2;
    
    static void establishCoreData(Integer intClassType) {
        
        system.debug('\n\n*** utilIds.cepIcdStaff: ' + utilIds.cepIcdStaff);
        
        User u = [SELECT Id FROM User WHERE IsActive = true AND ProfileId = :utilIds.cepIcdStaff LIMIT 1];
        
        // Create Client
        conTest = new Contact();
        conTest.FirstName = 'Howdy';
        conTest.LastName = 'Doody';
        conTest.Client_Status__c = 'Active';
        insert conTest;
        
        // Create Course
        crsTest = new Course__c();
        crsTest.name = 'Test Course';
        crsTest.Category__c = 'Category';
        crsTest.Area__c = 'Area';
        crsTest.Serves_All_Programs__c = true;        
        insert crsTest;
        
        // Create Class
        clTest = new Class__c();
        clTest.Course__c = crsTest.Id;
        if(intClassType == 0) { clTest.RecordTypeId = utilIds.classSingle; }
        if(intClassType == 1) { clTest.RecordTypeId = utilIds.classFixed; }
        if(intClassType == 2) { clTest.RecordTypeId = utilIds.classOngoing; }
    
        insert clTest;
        
    }

    static testMethod void testController() {
        
        establishCoreData(0);
        
        test.startTest();
        
        ApexPages.CurrentPage().getParameters().put('id',clTest.Id);
        scheduleNewInstance clsSchedule = new scheduleNewInstance();
        
        test.stopTest();
        
    }
    
    static testMethod void testScheduleSingle() {
        
        establishCoreData(0);
        
        ApexPages.CurrentPage().getParameters().put('id',clTest.Id);
        scheduleNewInstance clsSchedule = new scheduleNewInstance();
        
        test.startTest();
        
        // Set UI variables - error handling
        clsSchedule.createNewSchedule();
        
        // Test End Time before Start Time
        clsSchedule.schNew = new Schedule__c();
        clsSchedule.schNew.UI_Start_Date__c = System.Today();
        clsSchedule.strTimeStart = '10:00';
        clsSchedule.strStartAMPM = 'PM';
        clsSchedule.strTimeEnd = '11:00';
        clsSchedule.strEndAMPM = 'AM';
        clsSchedule.schNew.Class__c = clsSchedule.idClass;
        clsSchedule.schNew.RecordTypeId = utilIds.scheduleSingle;
        
        clsSchedule.createNewSchedule();
        
        // Test Success
        clsSchedule.strStartAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        test.stopTest();
        
    }

    static testMethod void testScheduleFixed() {
        
        establishCoreData(1);
        
        ApexPages.CurrentPage().getParameters().put('id',clTest.Id);
        scheduleNewInstance clsSchedule = new scheduleNewInstance();
        
        test.startTest();
        
        // Set UI variables - error handling
        clsSchedule.createNewSchedule();
        
        clsSchedule.schNew = new Schedule__c();
        clsSchedule.schNew.UI_Start_Date__c = System.Today();
        clsSchedule.schNew.UI_End_Date__c = System.Today().addDays(30);
        clsSchedule.strTimeStart = '10:00';
        clsSchedule.strStartAMPM = 'AM';
        clsSchedule.strTimeEnd = '11:00';
        clsSchedule.strEndAMPM = 'AM';
        clsSchedule.schNew.Monday__c = false;
        clsSchedule.schNew.Tuesday__c = false;
        clsSchedule.schNew.Wednesday__c = false;
        clsSchedule.schNew.Thursday__c = false;
        clsSchedule.schNew.Friday__c = false;
        clsSchedule.schNew.Saturday__c = false;
        clsSchedule.schNew.Sunday__c = false;
        clsSchedule.schNew.Class__c = clsSchedule.idClass;
        clsSchedule.schNew.RecordTypeId = utilIds.scheduleFixed;
        clsSchedule.createNewSchedule();
        
        // Test Day Checks
        clsSchedule.schNew.Monday__c = true;
        clsSchedule.schNew.Tuesday__c = true;
        clsSchedule.schNew.Wednesday__c = true;
        clsSchedule.schNew.Thursday__c = true;
        clsSchedule.schNew.Friday__c = true;
        clsSchedule.schNew.Saturday__c = true;
        clsSchedule.schNew.Sunday__c = true;
        clsSchedule.createNewSchedule();
        
        // Test Time Checks
        clsSchedule.strTimeStartMonday = '11:00';
        clsSchedule.strTimeEndMonday = '10:00';
        clsSchedule.strStartMondayAMPM = 'AM';
        clsSchedule.strEndMondayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartMonday = '10:00';
        clsSchedule.strTimeEndMonday = '11:00';
        clsSchedule.strStartMondayAMPM = 'AM';
        clsSchedule.strEndMondayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartTuesday = '11:00';
        clsSchedule.strTimeEndTuesday = '10:00';
        clsSchedule.strStartTuesdayAMPM = 'AM';
        clsSchedule.strEndTuesdayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartTuesday = '10:00';
        clsSchedule.strTimeEndTuesday = '11:00';
        clsSchedule.strStartTuesdayAMPM = 'AM';
        clsSchedule.strEndTuesdayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartWednesday = '11:00';
        clsSchedule.strTimeEndWednesday = '10:00';
        clsSchedule.strStartWednesdayAMPM = 'AM';
        clsSchedule.strEndWednesdayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartWednesday = '10:00';
        clsSchedule.strTimeEndWednesday = '11:00';
        clsSchedule.strStartWednesdayAMPM = 'AM';
        clsSchedule.strEndWednesdayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartThursday = '11:00';
        clsSchedule.strTimeEndThursday = '10:00';
        clsSchedule.strStartThursdayAMPM = 'AM';
        clsSchedule.strEndThursdayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartThursday = '10:00';
        clsSchedule.strTimeEndThursday = '11:00';
        clsSchedule.strStartThursdayAMPM = 'AM';
        clsSchedule.strEndThursdayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartFriday = '11:00';
        clsSchedule.strTimeEndFriday = '10:00';
        clsSchedule.strStartFridayAMPM = 'AM';
        clsSchedule.strEndFridayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartFriday = '10:00';
        clsSchedule.strTimeEndFriday = '11:00';
        clsSchedule.strStartFridayAMPM = 'AM';
        clsSchedule.strEndFridayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartSaturday = '11:00';
        clsSchedule.strTimeEndSaturday = '10:00';
        clsSchedule.strStartSaturdayAMPM = 'AM';
        clsSchedule.strEndSaturdayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartSaturday = '10:00';
        clsSchedule.strTimeEndSaturday = '11:00';
        clsSchedule.strStartSaturdayAMPM = 'AM';
        clsSchedule.strEndSaturdayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartSunday = '11:00';
        clsSchedule.strTimeEndSunday = '10:00';
        clsSchedule.strStartSundayAMPM = 'AM';
        clsSchedule.strEndSundayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        clsSchedule.strTimeStartSunday = '10:00';
        clsSchedule.strTimeEndSunday = '11:00';
        clsSchedule.strStartSundayAMPM = 'AM';
        clsSchedule.strEndSundayAMPM = 'AM';
        clsSchedule.createNewSchedule();
        
        test.stopTest();
        
    }
    
    static testMethod void testMiscActions() {
        
        establishCoreData(0);
        
        ApexPages.CurrentPage().getParameters().put('id',clTest.Id);
        scheduleNewInstance clsSchedule = new scheduleNewInstance();
        
        test.startTest();
        
        clsSchedule.cancelSchedule();
        
        test.stopTest();
        
    }
}