src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if enrollment open to all programs</description>
        <inlineHelpText>Check if enrollment open to all programs</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For validation only. If checked, Programs Served multi-select must be empty.</description>
        <inlineHelpText>Check this box if course has open enrollment (available to participants of all youth programs).</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Client that will be enrolled in a Class</description>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>relContactEnrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Enrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Most Recent Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrollment_Conflict__c.object
<CustomObject>
    <description>This custom object is used to track any enrolled Class / Session conflicts</description>
    <fields>
        <fullName>Conflict_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conflict Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Enrollment Conflicts</relationshipLabel>
        <relationshipName>relSessionConflict</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conflicting_Appointment__c</fullName>
        <label>Conflicting Appointment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <referenceTo>Enrollment__c</referenceTo>
        <relationshipLabel>Enrollment Conflicts</relationshipLabel>
        <relationshipName>relEnrollmentConflict</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Conflict</label>
    <nameField>
        <displayFormat>EC-{00000000}</displayFormat>
        <label>Enrollment Conflict Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Conflicts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The End Date of this schedule</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The start date of this schedule</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relSessionsUserAssigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedule__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>relScheduleSessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_End__c</fullName>
        <label>Session End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Start__c</fullName>
        <label>Session Start</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/courseConflictUnitTests.cls
@isTest
private class courseConflictUnitTests {
    
    static utilityIds utilIDs = new utilityIds();
    static Course__c crsTest;
    static Class__c clTest;
    static Schedule__c scTest;
    static Contact conTest;
    static Enrollment__c enrTest;
    static Session__c seTest;
    static Event evt1;
    static Event evt2;
    
    static void establishCoreData() {
        
        User u = new User();
        u.FirstName = 'Unit';
        u.LastName = 'Tester';
        u.ProfileId = utilIDs.cepIcdStaff;
        //u.ProfileId = '00e60000000vR5g';
        u.Username = 'unittester@cases.org';
        u.Email = 'unittester@cases.org';
        u.Alias = 'UTCASES';
        u.TimeZoneSidKey = 'America/Chicago';
        u.LocaleSidKey = 'en_US';
        u.EmailEncodingKey = 'UTF-8';
        u.LanguageLocaleKey = 'en_US';
        insert u;
        
        // Create Client
        conTest = new Contact();
        conTest.FirstName = 'Howdy';
        conTest.LastName = 'Doody';
        conTest.Client_Status__c = 'Active';
        insert conTest;
        
        // Create Course
        crsTest = new Course__c();
        crsTest.name = 'Test Course';
        crsTest.Serves_All_Programs__c = true;        
        insert crsTest;
        
        // Create Class
        clTest = new Class__c();
        clTest.Course__c = crsTest.Id;
        insert clTest;
        
        // Create Schedule
        scTest = new Schedule__c();
        scTest.Class__c = clTest.Id;
        scTest.Start_Date__c = System.Today().addDays(7);
        scTest.End_Date__c = System.Today().addDays(7);
        scTest.RecordTypeId = utilIDs.scheduleSingle;
        insert scTest;
        
        // Create Session
        seTest = new Session__c();
        seTest.Assigned_To__c = u.Id;
        seTest.Schedule__c = scTest.Id;
        seTest.Session_Start__c = scTest.Start_Date__c;
        seTest.Session_End__c = scTest.End_Date__c;
        insert seTest;
        
        // Create Enrollment
        enrTest = new Enrollment__c();
        enrTest.Class__c = clTest.Id;
        enrTest.Client__c = conTest.Id;
        enrTest.Most_Recent_Enrollment__c = true;
        insert enrTest;
        
        // Create Event
        evt1 = new Event();
        evt1.RecordTypeId = utilIDs.courseCatalogClass;
        evt1.OwnerId = u.Id;
        evt1.WhoId = conTest.Id;
        evt1.ActivityDate = scTest.Start_Date__c.date();
        evt1.ActivityDateTime = scTest.Start_Date__c;
        evt1.StartDateTime = scTest.Start_Date__c;
        evt1.EndDateTime = scTest.End_Date__c;
        evt1.Subject = 'HSE Class';
        insert evt1;
        
    }

    static testMethod void testController() {
        
        test.startTest();
        
        establishCoreData();
        
        Class__c clCurrent = [SELECT Id FROM Class__c LIMIT 1];
        
        ApexPages.CurrentPage().getParameters().put('c',clCurrent.Id);
        courseConflict clsConflict = new courseConflict();
        
        clsConflict.clCurrent = clTest;
        
        clsConflict.getConflicts();
        
        // Create Conflict!
        Enrollment_Conflict__c enrCon = new Enrollment_Conflict__c();
        enrCon.Conflict_Session__c = seTest.Id;
        enrCon.Enrollment__c = enrTest.Id;
        enrCon.Conflicting_Appointment__c = evt1.Id;
        insert enrCon;
        
        clsConflict.getConflicts();
        
        
        test.stopTest();
        
    }
}