src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>AreaRPT__c</fullName>
        <label>AreaRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryRPT__c</fullName>
        <label>CategoryRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Title__c</fullName>
        <description>A system-maintained field that concatenates the class name, subtitle, section, and cycle number fields. Subtitle added 2/28/13 by MB.</description>
        <formula>Course__r.Name 
+ IF(ISNULL(Subtitle__c) ,&apos;&apos;, &apos; &apos; + Subtitle__c)
+ IF(ISNULL(text(Class_Location__c)),&apos;&apos;,&apos; - &apos;+text(Class_Location__c)) 
+ IF(ISNULL(First_Session_On__c) || Record_Type_RPT__c=&apos;Ongoing&apos;,&apos;&apos;, &apos; /&apos; + TEXT(First_Session_On__c)) 
+ IF(ISNULL(Program_Cycle__c), &apos;&apos;, &apos; /&apos; + TEXT(Program_Cycle__c))</formula>
        <label>Class Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Session_On__c</fullName>
        <description>A system-maintained field that displays the first session for this Class</description>
        <label>First Session On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Instructor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A CEP staff member that will be the primary Instructor for this class.  This Instructor will also be whom the class appointments are assigned to.</description>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relUserClass1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Session_On__c</fullName>
        <description>A system-maintained field that displays the last session for this Class</description>
        <label>Last Session On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <description>The Career Exploration Program Cycle Number</description>
        <label>Program Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client_Class_Status_Field__c</fullName>
        <label>Client Class Status Field</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Client that will be enrolled in a Class</description>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>relContactEnrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrollment_Conflict__c.object
<CustomObject>
    <description>This custom object is used to track any enrolled Class / Session conflicts</description>
    <fields>
        <fullName>Conflict_Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conflict Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Enrollment Conflicts</relationshipLabel>
        <relationshipName>relSessionConflict</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Conflicting_Appointment__c</fullName>
        <label>Conflicting Appointment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <referenceTo>Enrollment__c</referenceTo>
        <relationshipLabel>Enrollment Conflicts</relationshipLabel>
        <relationshipName>relEnrollmentConflict</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment Conflict</label>
    <nameField>
        <displayFormat>EC-{00000000}</displayFormat>
        <label>Enrollment Conflict Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollment Conflicts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relSessionsUserAssigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Session_End__c</fullName>
        <label>Session End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Start__c</fullName>
        <label>Session Start</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/courseConflict.cls
public with sharing class courseConflict {

    ///////////////////////////////////////////
    // This method manages Conflict of Class Enrollments
    // Author:  AAB / DCS
    // Created:  20110427
    ///////////////////////////////////////////
    
    public utilityIds utilIds = new utilityIds();
    public String strClassId {get;set;}
    public Class__c clCurrent {get;set;}
    public List<conflictsForDisplay> lstConflicts = new List<conflictsForDisplay>();
    public String strConflictId {get;set;}
    public String strContactId {get;set;}
    public String strMessage {get;set;}
    
    ////////////////////////////////////////////
    // Helper Classes
    ////////////////////////////////////////////
    
    public class conflictsForDisplay {
        
        public Enrollment_Conflict__c ec {get;set;}
        public Event evtConflict {get;set;}
        public Contact c {get;set;}
        public Session__c s {get;set;}
                
    }
    
    /////////////////////////////////////////
    // Class Constructor / GETers
    /////////////////////////////////////////
    public courseConflict () {
        
        strClassId = ApexPages.currentPage().getParameters().get('c');
        clCurrent = [SELECT Id, Class_Title__c, First_Session_On__c, Last_Session_On__c, Instructor_1__r.Name FROM Class__c WHERE Id = :strClassId];
        
    }
    
    public List<conflictsForDisplay> getConflicts() {
        
        // Clear out the list
        lstConflicts.clear();
        
        // Get Initial List
        List<Enrollment__c> lstEnrollments = [SELECT Id, Client__c FROM Enrollment__c WHERE Class__c = :clCurrent.Id AND Client_Class_Status_Field__c = 'Active'];
        
        // Build Id Lists for Dependent Lists
        List<Id> lstEnrollmentIds = new List<Id>();
        List<Id> lstClientIds = new List<Id>();
        for(Enrollment__c e : lstEnrollments) {
            lstEnrollmentIds.add(e.Id);
            lstClientIds.add(e.Client__c);
        }
        
        List<Enrollment_Conflict__c> lstEnrollmentConflicts = [SELECT Enrollment__c, Conflict_Session__c, Conflicting_Appointment__c FROM Enrollment_Conflict__c WHERE Enrollment__c IN :lstEnrollments];
        System.Debug('Confict Count = ' + lstEnrollmentConflicts.size());
        
        List<Id> lstEventIds = new List<Id>();
        List<Id> lstSessionIds = new List<Id>();
        for(Enrollment_Conflict__c eConflict : lstEnrollmentConflicts) {
            lstEventIds.add(eConflict.Conflicting_Appointment__c);
            lstSessionIds.add(eConflict.Conflict_Session__c);
        }
        
        // Get Dependent Lists
        List<Session__c> lstConflictSessions = [SELECT Id, Session_Start__c, Session_End__c, Assigned_To__r.Name FROM Session__c WHERE Id IN :lstSessionIds];
        //List<Contact> lstConflictContacts = [SELECT Id, Name, Current_Projected_Exit_Date__c FROM Contact WHERE Id IN :lstClientIds];
        Map<Id, Contact> mapConflictContacts = new Map<Id, Contact>([SELECT Id, Name, Current_Projected_Exit_Date__c FROM Contact WHERE Id IN :lstClientIds]); 
        //List<Event> lstConflictEvents = [SELECT Id, WhoId, StartDateTime, EndDateTime, Subject FROM Event WHERE Id IN :lstEventIds];
        Map<Id, Event> mapConflictEvents = new Map<Id, Event>([SELECT Id, WhoId, StartDateTime, EndDateTime, Subject FROM Event WHERE Id IN :lstEventIds]);
        
        for(Enrollment_Conflict__c eConflict : lstEnrollmentConflicts) {
            
            conflictsForDisplay cfdNew = new conflictsForDisplay();
            
            // Enrollment Conflict
            cfdNew.ec = eConflict;
            
            // Session that is in conflict
            for(Session__c seConflict : lstConflictSessions) {
                if(seConflict.Id == eConflict.Conflict_Session__c) {
                    cfdNew.s = seConflict;
                    break;
                }
            }
            
            // Event that is in conflict
            if(mapConflictEvents.get(eConflict.Conflicting_Appointment__c) != null) {
                
                // Assign Event
                cfdNew.evtConflict = mapConflictEvents.get(eConflict.Conflicting_Appointment__c);
                
                // Assign Contact
                cfdNew.c = mapConflictContacts.get(cfdNew.evtConflict.WhoId);
                
            }
/*          for(Event evtConflictEvent : lstConflictEvents) {
                if(string.valueOf(evtConflictEvent.Id) == eConflict.Conflicting_Appointment__c) {
                    
                    // Assign Event
                    cfdNew.evtConflict = evtConflictEvent;
                    
                    // Assign Contact
                    for(Contact conConflict : lstConflictContacts) {
                        if(conConflict.Id == evtConflictEvent.WhoId) {
                            cfdNew.c = conConflict;
                            break;
                        }
                    }
                    
                    break;
                }
            }
*/
            if(lstConflicts.size() < 999 && cfdNew.evtConflict != null) {
                lstConflicts.add(cfdNew);
            }   
            
        }
        
        
        return lstConflicts;
        
    }
    
    public void resubmitConflict() {
            
        Boolean bolCreateEvent = true;
        
        Enrollment_Conflict__c ec = [Select Id, Name, Enrollment__c, Conflict_Session__c, Conflicting_Appointment__c From Enrollment_Conflict__c WHERE Id = :strConflictId];
        Session__c s = [SELECT Id, Session_Start__c, Session_End__c FROM Session__c WHERE Id = :ec.Conflict_Session__c];
        Enrollment__c enr = [SELECT Class__c FROM Enrollment__c WHERE Id = :ec.Enrollment__c];
        Class__c clCurrent = [SELECT RecordTypeId, Instructor_1__c, Program_Cycle__c, CategoryRPT__c, Class_Title__c, AreaRPT__c FROM Class__c WHERE Id = :enr.Class__c];
        
        //9/13/13 MB modifying the list of events pulled so that it ignores cancelled and withdrawn events, and uses
        //the same code as the conflict creator in courseEnrollment
        List<Event> lstEvt = [SELECT Id, RecordTypeId, ActivityDate, WhoId, ActivityDateTime, StartDateTime, EndDateTime 
                                FROM Event 
                                WHERE WhoId = :strContactId 
                                AND Verification_Status__c != 'Cancelled' 
                                AND Verification_Status__c != 'Withdrawn' 
                                AND IsDeleted = false 
                                AND IsRecurrence = false 
                                AND StartDateTime >= :System.Now() 
                                AND RecordTypeId != :utilIds.courtDate 
                                AND (RecordTypeID != :utilIds.caseCoordination 
                                AND Subject != 'Program Reporting')];
        
        for(Event e : lstEvt) {
            
            System.Debug('TESTING = ' + e.Id);
        
            //BT-266 ebg - added check for other event covering exact timeframe as the session
            if((e.StartDateTime < s.Session_Start__c && e.EndDateTime > s.Session_Start__c) ||
                (e.StartDateTime < s.Session_End__c && e.EndDateTime > s.Session_End__c) ||
                (e.StartDateTime < s.Session_Start__c && e.EndDateTime > s.Session_End__c) ||
                (e.StartDateTime == s.Session_Start__c && e.EndDateTime == s.Session_End__c)) {
                
                bolCreateEvent = false;
                strMessage = 'There is a conflict that is preventing you from proceeding.  Please review the Events for this Client and try again.';
            }
        }
        
        if(bolCreateEvent == true) {
            
            Event evt = new Event();
                        
            Long lngClassDuration = (s.Session_End__c.getTime() - s.Session_Start__c.getTime());
            
            evt.WhoId = strContactId;
            evt.WhatId = s.Id;
            evt.OwnerId = clCurrent.Instructor_1__c;
            evt.Program_Cycle__c = clCurrent.Program_Cycle__c;
            evt.Area__c = clCurrent.AreaRPT__c;
            evt.Class_Category__c = clCurrent.CategoryRPT__c;
            evt.RecordTypeId = utilIds.courseCatalogClass;
            evt.Subject = clCurrent.Class_Title__c;
            evt.ActivityDateTime = s.Session_Start__c;
            evt.ActivityDate = s.Session_Start__c.date();
            evt.StartDateTime = s.Session_Start__c;
            evt.EndDateTime = s.Session_End__c;
            evt.Verification_Status__c = 'Not Verified';
            evt.DurationInMinutes = Integer.valueOf(lngClassDuration) / 60000;
            evt.SkipRestrictions__c = true;
            evt.ClassTypeRPT__c = clCurrent.RecordTypeId;
            if(Integer.valueOf(lngClassDuration) / 60000 > 0) { 
                // Insert Event
                insert evt; 
                
                // Delete Enrollment Conflict Record
                delete ec;
                strMessage = 'The conflict has been resolved and the Client is now scheduled in the Class.';
            }
        }
    
        
        getConflicts();
    }
    
}