src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if enrollment open to all programs</description>
        <inlineHelpText>Check if enrollment open to all programs</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Case Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Alumni Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Trip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop-in Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education / Job Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim SA Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Readiness Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandatory Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stages of Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>START Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Readiness Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP One Day Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For validation only. If checked, Programs Served multi-select must be empty.</description>
        <inlineHelpText>Check this box if course has open enrollment (available to participants of all youth programs).</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/courseCatalogUnitTests.cls
@isTest
private class courseCatalogUnitTests {
    
    ///////////////////////////////////////////
    // This test class covers the Course Catalog functionality
    // Created by AAB / DCS 20110413
    ///////////////////////////////////////////
    
    static testMethod void testController() {
        
        Course__c crsTest = new Course__c();
        crsTest.name = 'test';
        crsTest.Serves_All_Programs__c = true;        
        insert crsTest;
        
        ApexPages.StandardController ctr = new ApexPages.Standardcontroller(crsTest);
        
        courseCatalog clsCourseCatalog = new courseCatalog(ctr);
        
    }
    
    static testMethod void testPOSTVariables() {
        
        test.startTest();
        
        ApexPages.CurrentPage().getParameters().put('result','referralsuccess');
        courseCatalog clsCourseCatalog = new courseCatalog();
        
        test.stopTest();
        
    }

    static testMethod void testGeneralCourseCatalog() {
        
        test.startTest();
        
        courseCatalog clsCourseCatalog = new courseCatalog();
        
        clsCourseCatalog.clsForDisplay = clsCourseCatalog.getClasses();
        
        clsCourseCatalog.doNothing();
        clsCourseCatalog.clearSearch();
        //clsCourseCatalog.createEnrollment();
        clsCourseCatalog.createNewCourse();
        
        // Search - Clear Criteria
        clsCourseCatalog.intClassType = 0;
        clsCourseCatalog.createNewClass();
        
        clsCourseCatalog.intClassType = 1;
        clsCourseCatalog.createNewClass();

        clsCourseCatalog.intClassType = 2;
        clsCourseCatalog.createNewClass();
        
        // Search - Specify Criteria
        
        clsCourseCatalog.coSearch.Category__c = 'Education';
        clsCourseCatalog.clsForDisplay = clsCourseCatalog.getClasses();
        
        clsCourseCatalog.coSearch.Area__c = 'Area';
        clsCourseCatalog.tskDummy.ActivityDate = null;
        clsCourseCatalog.tskDummy.Closing_Date__c = null;
        clsCourseCatalog.clsForDisplay = clsCourseCatalog.getClasses();
        
        clsCourseCatalog.tskDummy.ActivityDate = System.Today();
        clsCourseCatalog.tskDummy.Closing_Date__c = null;
        clsCourseCatalog.clsForDisplay = clsCourseCatalog.getClasses();
        
        clsCourseCatalog.tskDummy.ActivityDate = null;
        clsCourseCatalog.coSearch.Area__c = null;
        clsCourseCatalog.coSearch.Category__c = null;
        clsCourseCatalog.tskDummy.Closing_Date__c = System.Today();
        clsCourseCatalog.clsForDisplay = clsCourseCatalog.getClasses();
        
        clsCourseCatalog.tskDummy.ActivityDate = System.Today();
        clsCourseCatalog.coSearch.Area__c = null;
        clsCourseCatalog.coSearch.Category__c = null;
        clsCourseCatalog.tskDummy.Closing_Date__c = null;
        clsCourseCatalog.clsForDisplay = clsCourseCatalog.getClasses();
        
        test.stopTest();
        
    }
    
    static testMethod void testGeneralCourseCatalogRun2() {
        
        courseCatalog clsCourseCatalog = new courseCatalog();
        
        clsCourseCatalog.clsForDisplay = clsCourseCatalog.getClasses();
        
        clsCourseCatalog.clearSearch();
        
        // Search - Clear Criteria
        clsCourseCatalog.intClassType = 0;
        
        // Search - Specify Criteria
        
        test.startTest();
        
        clsCourseCatalog.coSearch.Category__c = 'Education';
        clsCourseCatalog.coSearch.Area__c = 'Area';
        clsCourseCatalog.tskDummy.ActivityDate = System.Today();
        clsCourseCatalog.tskDummy.Closing_Date__c = System.Today();
        clsCourseCatalog.clsForDisplay = clsCourseCatalog.getClasses();
        
        test.stopTest();
        
    }
    
    static testMethod void gradingAndVerification() {
        
        Course__c crsTest = new Course__c();
        crsTest.name = 'Test Course';
    	crsTest.Serves_All_Programs__c = true;        
        insert crsTest;
        
        Class__c clsTest = new Class__c();
        clsTest.Course__c = crsTest.Id;
        insert clsTest;
        
        test.startTest();
        
        courseCatalog clsCourseCatalog = new courseCatalog();
        clsCourseCatalog.strEnrollmentClassId = clsTest.Id;
        //clsCourseCatalog.gradingAndVerification();
        
        test.stopTest();
        
    }
}