src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>AreaRPT__c</fullName>
        <label>AreaRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryRPT__c</fullName>
        <label>CategoryRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Case Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substance Abuse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Alumni Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Exploration Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Trip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop-in Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education / Job Fair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interim SA Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Readiness Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mandatory Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Academic Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation Activity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stages of Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>START Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Readiness Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TASC Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRP One Day Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth Development</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dummy_Schedule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, create session logic is not run on the schedule. This is used for schedules where the sessions will be added via a nightly process, such as for the DTC Groups.</description>
        <label>Dummy Schedule?</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/courseMethods.cls
public with sharing class courseMethods {

	public utilityIds utilId = new utilityIds();
	public List<Course__c> lstCourses = new List<Course__c>();

    public courseMethods() {  }
    
    public void updateClassAttributes() {
        
        List<Id> lstCourseIds = new List<Id>();
        for(Course__c c : lstCourses) {
            lstCourseIds.add(c.Id);
        }
        
        List<Class__c> lstClasses = [SELECT Id, Course__c, AreaRPT__c, CategoryRPT__c FROM Class__c WHERE Course__c IN :lstCourses];
        
        for(Course__c coLoop : lstCourses) {
            for(Class__c c : lstClasses) {
                if(c.Course__c == coLoop.Id) {
                    c.AreaRPT__c = coLoop.Area__c;
                    c.CategoryRPT__c = coLoop.Category__c;
                }
            }
        }
        
        if(lstClasses.size() > 0) { update lstClasses; }
        
    }
    
	//for START groups, create a dummy class and schedule to be used for DTC Groups
	public void createDummyClass() {
		
		list<Class__c> lstClassestoCreate = new list<Class__c>();
		list<Schedule__c> lstSchedulestoCreate = new list<Schedule__c>();
		Class__c tempCL = new Class__c();
		Schedule__c tempSch = new Schedule__c();
		
		for(Course__c c: lstCourses) {
			
			if(c.Category__c == 'START Group') {
				
				tempCL = new Class__c(RecordtypeId = utilId.classFixed, Course__c = c.id);
				lstClassestoCreate.add(tempCL);
			}
		}
		
		insert lstClassestoCreate;
		
		for(Class__c c: lstClassestoCreate) {

				tempSch = new Schedule__c(RecordtypeId = utilId.scheduleFixed, Class__c = c.id, Dummy_Schedule__c = true);
				lstSchedulestoCreate.add(tempSch);			
		}
		
		insert lstSchedulestoCreate;
		
	}    
}