src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>AreaRPT__c</fullName>
        <label>AreaRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryRPT__c</fullName>
        <label>CategoryRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class_Title__c</fullName>
        <description>A system-maintained field that concatenates the class name, subtitle, section, and cycle number fields. Subtitle added 2/28/13 by MB.</description>
        <formula>Course__r.Name 
+ IF(ISNULL(Subtitle__c) ,&apos;&apos;, &apos; &apos; + Subtitle__c)
+ IF(ISNULL(text(Class_Location__c)),&apos;&apos;,&apos; - &apos;+text(Class_Location__c)) 
+ IF(ISNULL(First_Session_On__c) || Record_Type_RPT__c=&apos;Ongoing&apos;,&apos;&apos;, &apos; /&apos; + TEXT(First_Session_On__c)) 
+ IF(ISNULL(Program_Cycle__c), &apos;&apos;, &apos; /&apos; + TEXT(Program_Cycle__c))</formula>
        <label>Class Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Ending_Session__c</fullName>
        <description>whether to enroll clients through their projected exit dates or through the end of the class, even if that is beyond their projected exit date.  Clients without a projected exit date are enrolled through the &quot;end of class&quot; or however many future sessions exist.</description>
        <label>Default Ending Session</label>
        <picklist>
            <picklistValues>
                <fullName>Sessions up to last Class date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sessions up to Client&apos;s projected exit date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single session only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Instructor_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A CEP staff member that will be the primary Instructor for this class.  This Instructor will also be whom the class appointments are assigned to.</description>
        <label>Instructor 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>relUserClass1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <description>The Career Exploration Program Cycle Number</description>
        <label>Program Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <recordTypes>
        <fullName>Single</fullName>
        <active>true</active>
        <description>A single instance of a Class</description>
        <label>Single</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client_Class_Status_Field__c</fullName>
        <label>Client Class Status Field</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Client that will be enrolled in a Class</description>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>relContactEnrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Enrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Most Recent Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <fields>
        <fullName>ClassId__c</fullName>
        <formula>Schedule__r.Class__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ClassId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedule__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>relScheduleSessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Session_End__c</fullName>
        <label>Session End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Start__c</fullName>
        <label>Session Start</label>
        <type>DateTime</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sessionMethods.cls
public class sessionMethods {


    public utilityIds utilIds = new utilityIds(); 
    
    //////////////////////////////////
    // Constructors / Helpers
    //////////////////////////////////
    public sessionMethods() { }
    

    public void additionalSessionEnrollments(List<Session__c> lstSessions) {
        
        // Build list of existing events to do a dupe check on
        /////////////////////////////
        
        List<Event> lstCreateEvents = new List<Event>();
        List<Event> lstUpdateEvents = new List<Event>();
        Set<Id> setClassIds = new Set<Id>();
        
        Map<Id, Class__c> mapClass = new Map<Id, Class__c>();
        Map<Id, Id> mapSessionSchedule = new Map<Id, Id>();
        
        List<Id> lstScheduleIds = new List<Id>();
        Set<Id> setSessionIds = new Set<Id>();
        for(Session__c s : lstSessions) { 
            lstScheduleIds.add(s.Schedule__c);
            setSessionIds.add(s.Id);
            mapSessionSchedule.put(s.Id, s.Schedule__c);
            setClassIds.add(s.ClassId__c);
        }
        
        List<Enrollment__c> lstEnrollments = [SELECT Id, Class__c, Client__c FROM Enrollment__c WHERE Class__c IN :setClassIds AND Most_Recent_Enrollment__c = true AND Client_Class_Status_Field__c = 'Active' AND Client__c != null];
		//20160303 EBG/DCS - added field "Default_Ending_Session__c" to query results
        List<Class__c> lstClasses = [SELECT Id, Instructor_1__c, Class_Title__c, AreaRPT__c, CategoryRPT__c, RecordTypeId, Program_Cycle__c, Default_Ending_Session__c FROM Class__c WHERE Id IN :setClassIds];
        for(Class__c c : lstClasses) {
            mapClass.put(c.Id, c);
        }
        
        Set<Id> setClientIds = new Set<Id>();
        for(Enrollment__c enr : lstEnrollments) {
            setClientIds.add(enr.Client__c);
        }
        
        // Removed per BT-307 - logic moved to Grading and Verification page 20120410
        // Create List of Existing Events to control "Last Session Flag"
        //List<Event> lstEvents = [SELECT Id, WhoId, WhatId, LastClassRPT__c FROM Event WHERE WhoId IN :setClientIds AND WhatId IN :mapSessionSchedule.keySet() ORDER BY WhoId ASC, ActivityDateTime ASC];
        
        // Loop through sessions to create Events for Clients
        for(Session__c ses : lstSessions) {
            //20160303 EBG/DCS - if the class being extended is a "Single session only", do not extend the enrollments for the clients
            if (mapClass.get(ses.ClassId__c).Default_Ending_Session__c == 'Single session only') {
                //move to next session
                continue;
            }
            System.Debug('sessionMethods.additionalSessionEnrollments INFO:  STEP 1');
                    
            for(Enrollment__c enr : lstEnrollments) {
                System.Debug('sessionMethods.additionalSessionEnrollments INFO:  STEP 2');
                
                if(enr.Class__c == ses.ClassId__c) {
                    System.Debug('sessionMethods.additionalSessionEnrollments INFO:  Creating Event for ' + enr.Client__c + ' on ' + ses.Session_Start__c);
                    Event evt = new Event();
                    
                    evt.WhoId = enr.Client__c;
                    evt.WhatId = ses.Id;
                    evt.OwnerId = mapClass.get(ses.ClassId__c).Instructor_1__c;
                    evt.RecordTypeId = utilIds.courseCatalogClass;
                    evt.Subject = mapClass.get(ses.ClassId__c).Class_Title__c;
                    evt.ActivityDateTime = ses.Session_Start__c;
                    
                    // BT-282 NEED TO FIX - CALCULATE CORRECT NUMBER OF MINUTES
                    //evt.DurationInMinutes = 60;
                    Long lngDiff = (((ses.Session_End__c.getTime() - ses.Session_Start__c.getTime()) / 1000) / 60);
                    System.Debug('sessionMethods.additionalSessionEnrollments INFO:  intDiff = ' + lngDiff);
                    evt.DurationInMinutes = Integer.valueOf(lngDiff);
                    
                    // BT-282 ALSO, NEED TO POPULATE THE CLASS CATEGORY AND AREA WITH VALUES ON MANUAL SESSION CREATE
                    evt.Class_Category__c = mapClass.get(ses.ClassId__c).CategoryRPT__c;
                    evt.Area__c = mapClass.get(ses.ClassId__c).AreaRPT__c;
                    evt.ClassTypeRPT__c = mapClass.get(ses.ClassId__c).RecordTypeId;
                    evt.Program_Cycle__c = mapClass.get(ses.ClassId__c).Program_Cycle__c;
                    
                    evt.ActivityDate = ses.Session_Start__c.date();
                    evt.SkipRestrictions__c = true;
                    
                    // Removed per BT-307 - logic moved to Grading and Verification page 20120410
                    // Added BT-307 Check for "Last Class RPT Flag"
                    //for(Event eEvt : lstEvents) {
                    //  // Ensure we're talking about the right WHO in the session's schedule
                    //  if(eEvt.WhoId == evt.WhoId && mapSessionSchedule.get(eEvt.WhatId) == mapSessionSchedule.get(evt.WhatId)) {
                    //      //if(eEvt.LastClassRPT__c == true && eEvt.ActivityDateTime < evt.ActivityDateTime) {
                    //      if(eEvt.ActivityDateTime < evt.ActivityDateTime) {
                    //          
                    //          evt.LastClassRPT__c = true;
                    //          eEvt.LastClassRPT__c = false;
                    //          lstUpdateEvents.add(eEvt);
                    //          
                    //      }
                    //  }
                    //}
                    
                    lstCreateEvents.add(evt);
                } // End If
            } // End Enrollment
        } // End Session
        
        if(lstCreateEvents.size() > 0) { insert lstCreateEvents; }
        if(lstUpdateEvents.size() > 0) { update lstUpdateEvents; }
        
    }
    
    public void deleteSessionEvents(List<Session__c> lstSessions) {
        
        // This will delete all Events associated to a Session
        
        List<Id> lstSessionIds = new List<Id>();
        for(Session__c s : lstSessions) { lstSessionIds.add(s.Id); }
        
        List<Event> lstEventsToDelete = [SELECT Id FROM Event WHERE WhatId IN :lstSessionIds];
        
        if(lstEventsToDelete.size() > 0) { delete lstEventsToDelete; }
        
    }

}