src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>Extension_Days_to_Generate__c</fullName>
        <defaultValue>8</defaultValue>
        <description>This field will be used to extend and ongoing class by a set number of days</description>
        <label>Extension Days to Generate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Months_of_Sessions_to_Generate__c</fullName>
        <description>This field is used to initially (on creation) generate the sessions for ongoing classes only.  It will generate classes from the start date of the class the first time; so if the user enters 2 months, then it will be 2 months from the start date.</description>
        <label>Months of Sessions to Generate</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_Type_RPT__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type RPT</label>
        <type>Text</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>AutoExtendFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AutoExtendFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Change_Schedule_As_Of__c</fullName>
        <description>Set this field if you are making changes to an active schedule.  All session dates equal to or greater to the value in this field will be modified</description>
        <inlineHelpText>Set this field if you are making changes to an active schedule.  All session dates equal to or greater to the value in this field will be modified</inlineHelpText>
        <label>Change Schedule As Of</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The End Date of this schedule</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Extension_Days_to_Generate__c</fullName>
        <defaultValue>8</defaultValue>
        <label>Extension Days to Generate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Friday_End_Time__c</fullName>
        <label>Friday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Friday_Start_Time__c</fullName>
        <label>Friday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Friday</description>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monday_End_Time__c</fullName>
        <label>Monday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Monday_Start_Time__c</fullName>
        <label>Monday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Monday</description>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Months_of_Sessions_to_Generate__c</fullName>
        <label>Months of Sessions to Generate</label>
        <picklist>
            <picklistValues>
                <fullName>2</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Original_End_Date__c</fullName>
        <label>Original End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Original_Start_Date__c</fullName>
        <label>Original Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Record_Type_RPT__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Saturday_End_Time__c</fullName>
        <label>Saturday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Saturday_Start_Time__c</fullName>
        <label>Saturday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Saturday</description>
        <label>Saturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The start date of this schedule</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sunday_End_Time__c</fullName>
        <label>Sunday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sunday_Start_Time__c</fullName>
        <label>Sunday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Sunday</description>
        <label>Sunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday_End_Time__c</fullName>
        <label>Thursday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Thursday_Start_Time__c</fullName>
        <label>Thursday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Thursday</description>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday_End_Time__c</fullName>
        <label>Tuesday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Tuesday_Start_Time__c</fullName>
        <label>Tuesday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Tuesday</description>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UI_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UI_Start_Date__c</fullName>
        <description>This is used by the New Schedule VF page</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Wednesday_End_Time__c</fullName>
        <label>Wednesday End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Wednesday_Start_Time__c</fullName>
        <label>Wednesday Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if this schedule includes a session on Wednesday</description>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jobAutoExtendSchedule_UnitTest.cls
public class jobAutoExtendSchedule_UnitTest {
    
    public static testMethod void testBatch() {


        utilityIds clsUtilIds = new utilityIds();    

        Test.StartTest();

        jobAutoExtendSchedule job = new jobAutoExtendSchedule();

        String strQuery = 'SELECT ';
                    strQuery += 'UI_Start_Date__c, UI_End_Date__c, Record_Type_RPT__c, RecordTypeId, ';
                    strQuery += 'SystemModstamp, Start_Date__c, Original_Start_Date__c, Original_End_Date__c, ';
                    strQuery += 'Name, Months_of_Sessions_to_Generate__c, LastModifiedDate, LastModifiedById, LastActivityDate, ';
                    strQuery += 'IsDeleted, Id, Extension_Days_to_Generate__c, End_Date__c, CreatedDate, CreatedById, Class__c, ';
                    strQuery += 'Change_Schedule_As_Of__c, AutoExtendFlag__c, ';
                    strQuery += 'Monday__c, Monday_Start_Time__c, Monday_End_Time__c, ';
                    strQuery += 'Tuesday__c, Tuesday_Start_Time__c, Tuesday_End_Time__c, ';
                    strQuery += 'Wednesday__c, Wednesday_Start_Time__c, Wednesday_End_Time__c, ';
                    strQuery += 'Thursday__c, Thursday_Start_Time__c, Thursday_End_Time__c, ';
                    strQuery += 'Friday__c, Friday_Start_Time__c, Friday_End_Time__c, ';
                    strQuery += 'Saturday__c, Saturday_Start_Time__c, Saturday_End_Time__c, ';
                    strQuery += 'Sunday__c, Sunday_Start_Time__c, Sunday_End_Time__c ';
                    strQuery += 'FROM Schedule__c s ';
                    strQuery += 'WHERE s.RecordTypeId = \'' + clsUtilIds.scheduleOngoing + '\' '; 
                    strQuery += 'AND s.End_Date__c > ' + system.now().format('yyyy-MM-dd') + 'T00:00:00Z LIMIT 1';  

                                            
        job.query = strQuery;
        ID batchprocessid = Database.executeBatch(job);

        

        Test.StopTest();
    
    }

}