src/objects/Class__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Course object.</description>
    <fields>
        <fullName>CategoryRPT__c</fullName>
        <label>CategoryRPT</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course__c</fullName>
        <description>The Offering that this Course is related to.</description>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>relCourseClasses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if enrollment open to all programs</description>
        <inlineHelpText>Check if enrollment open to all programs</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <recordTypes>
        <fullName>Fixed</fullName>
        <active>true</active>
        <description>A fixed series of a Class</description>
        <label>Fixed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Single</fullName>
        <active>true</active>
        <description>A single instance of a Class</description>
        <label>Single</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Course__c.object
<CustomObject>
    <description>This custom object is the top-level of the Course Registration module.  This holds informational fields on what educational course / offering will be placed into a Class.</description>
    <fields>
        <fullName>Serves_All_Programs__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For validation only. If checked, Programs Served multi-select must be empty.</description>
        <inlineHelpText>Check this box if course has open enrollment (available to participants of all youth programs).</inlineHelpText>
        <label>Serves All Programs</label>
        <type>Checkbox</type>
    </fields>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Enrollment__c.object
<CustomObject>
    <description>This custom object is a singular instance of a Client&apos;s (Contact) enrollment in a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Client will be enrolled in</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule__c.object
<CustomObject>
    <description>This custom object is a singular instance (one to many) of the Class object.  Schedules are logical instances of a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>The Class that this Schedule is related to.</description>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Schedules</relationshipLabel>
        <relationshipName>Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>The End Date of this schedule</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The start date of this schedule</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <label>Schedule</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Session__c.object
<CustomObject>
    <description>This custom object is a one to many relationship to the Schedule object. Sessions are operational instances of a Schedule.</description>
    <fields>
        <fullName>Schedule__c</fullName>
        <label>Schedule</label>
        <referenceTo>Schedule__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>relScheduleSessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Session</label>
    <nameField>
        <displayFormat>CSS-{00000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/courseEnrollmentUnitTests.cls
@isTest
private class courseEnrollmentUnitTests {
    
    static utilityIds utilIDs = new utilityIds();
    static Course__c crsTest;
    static Class__c clTest;
    static Schedule__c scTest;
    static Contact conTest;
    static Enrollment__c enrTest;
    static Session__c seTest;
    static Event evt1;
    static Event evt2;
    
    static void establishCoreData() {
        
        User u = [SELECT Id FROM User WHERE IsActive = true AND ProfileId = :utilIDs.cepIcdStaff LIMIT 1];
        
        // Create Client
        conTest = new Contact();
        conTest.FirstName = 'Howdy';
        conTest.LastName = 'Doody';
        conTest.Client_Status__c = 'Active';
        insert conTest;
        
        // Create Course
        crsTest = new Course__c();
        crsTest.name = 'Test Course';
        crsTest.Serves_All_Programs__c = true;        
        insert crsTest;
        
        // Create Class
        clTest = new Class__c();
        clTest.Course__c = crsTest.Id;
        insert clTest;
        
        // Create Schedule
        scTest = new Schedule__c();
        scTest.Class__c = clTest.Id;
        scTest.Start_Date__c = System.Today().addDays(7);
        scTest.End_Date__c = System.Today().addDays(7);
        scTest.RecordTypeId = Schema.SObjectType.Schedule__c.getRecordTypeInfosByName().get('Single Schedule').getRecordTypeId();
        insert scTest;
        
    }
    
    static testMethod void testController() {
        
        test.startTest();
        
        establishCoreData();
        
        Class__c clCurrent = [SELECT Id FROM Class__c LIMIT 1];
        
        ApexPages.CurrentPage().getParameters().put('c',clCurrent.Id);
        courseEnrollment clsEnrollment = new courseEnrollment();
        
                
        
        test.stopTest();
        
    }
    
/*  static testMethod void testFixedController() {
        
        test.startTest();
        
        establishCoreData();
        
        Class__c clCurrent = [SELECT Id FROM Class__c WHERE RecordTypeId = :Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Fixed').getRecordTypeId() LIMIT 1];
        
        ApexPages.CurrentPage().getParameters().put('c',clCurrent.Id);
        courseEnrollment clsEnrollment = new courseEnrollment();
        
        test.stopTest();
        
    }
    
    static testMethod void testCEXController() {
        
        test.startTest();
        
        establishCoreData();
        
        Class__c clCurrent = [SELECT Id FROM Class__c WHERE CategoryRPT__c = 'Career Exploration Training' LIMIT 1];
        
        ApexPages.CurrentPage().getParameters().put('c',clCurrent.Id);
        courseEnrollment clsEnrollment = new courseEnrollment();
        
        test.stopTest();
        
    }
*/  
    static testMethod void testPageActions() {
        
        establishCoreData();
        
        test.startTest();
        
        Class__c clCurrent = [SELECT Id FROM Class__c WHERE RecordTypeId = :Schema.SObjectType.Class__c.getRecordTypeInfosByName().get('Fixed').getRecordTypeId() LIMIT 1];
        
        ApexPages.CurrentPage().getParameters().put('c',clTest.Id);
        courseEnrollment clsEnrollment = new courseEnrollment();
        clsEnrollment.strClassId = clTest.Id;
        
        clsEnrollment.init();
        
        // Test Getters
        List<courseEnrollment.clientsForDisplay> lstEnrollees = new List<courseEnrollment.clientsForDisplay>();
        
        clsEnrollment.intEnrollees = 0;
        lstEnrollees = clsEnrollment.getClients();
        
        clsEnrollment.intEnrollees = 1;
        lstEnrollees = clsEnrollment.getClients();
        
        clsEnrollment.intEnrollees = 2;
        lstEnrollees = clsEnrollment.getClients();
        
        clsEnrollment.intEnrollees = 3;
        lstEnrollees = clsEnrollment.getClients();
        
        clsEnrollment.intEnrollees = 4;
        lstEnrollees = clsEnrollment.getClients();
        
        clsEnrollment.intEnrollees = 5;
        lstEnrollees = clsEnrollment.getClients();
        
        List<selectOption> lstSearchOptions = new List<selectOption>();
        lstSearchOptions = clsEnrollment.getSearchOptions();
        
        List<selectOption> lstSessionStart = new List<selectOption>();
        lstSearchOptions = clsEnrollment.getSessionStart();
        
        List<selectOption> lstSessionEnd = new List<selectOption>();
        lstSearchOptions = clsEnrollment.getSessionEnd();
        
        // Here we go
        clsEnrollment.doNothing();
        clsEnrollment.printRoster();
        clsEnrollment.viewConflicts();
        clsEnrollment.createCeXPInterview();
        clsEnrollment.cancelAndReturn();
        

        
        // Enrollment
        clsEnrollment.lstEnrollees.clear();
        
        courseEnrollment.clientsForDisplay nClientForDisplay = new courseEnrollment.clientsForDisplay();
        nClientForDisplay.con = conTest;
        nClientForDisplay.chk = true;
        nClientForDisplay.bolEnrolled = false;
        
        clsEnrollment.lstEnrollees.add(nClientForDisplay);
        
        clsEnrollment.clCurrent = null;
        clsEnrollment.enrollClients();
        
        // Enroll again with conflicts
        
        evt1 = new Event();
        evt1.RecordTypeId = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Course Catalog Class').getRecordTypeId();  
        evt1.OwnerId = UserInfo.getUserId();
        evt1.WhoId = conTest.Id;
        evt1.ActivityDate = scTest.Start_Date__c.date();
        evt1.ActivityDateTime = scTest.Start_Date__c;
        evt1.StartDateTime = scTest.Start_Date__c;
        evt1.EndDateTime = scTest.End_Date__c;
        evt1.Subject = 'HSE Class';
        insert evt1;
        
        
        clsEnrollment.enrollClients();
        
        test.stopTest();
        
    }
}