src/objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>Client</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Employer_Name__c</fullName>
        <description>Show either Account Name (Employer linked) or Other Employer text or Both</description>
        <formula>if(isblank(Employer__c),Other_Employer__c, Employer__r.Name &amp;if(len(Other_Employer__c)&gt;0,&apos; - &apos;&amp;Other_Employer__c, &apos;&apos;))</formula>
        <label>Employer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field to employer - in accounts</description>
        <label>Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Employment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employment_Type__c</fullName>
        <label>Employment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Employed FT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employed PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Job Training/Readiness Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internship</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hourly_Pay__c</fullName>
        <label>Hourly Pay</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Work_Hours_from_and_to__c</fullName>
        <inlineHelpText>Format:  Example  9:00 to 5:00</inlineHelpText>
        <label>Work Hours (From and To)</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Employment</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Emp-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/employmentMethods.cls
public class employmentMethods {

    public List<Employment__c> newEmployments = new List<Employment__c>();

    ///////////////////////
    // TRIGGER ACTIONS
    ///////////////////////
    
    public void updateContactEmploymentSection() {
        
        String strCurEmployment = '';
        String strEmployer = '';
        String strJobTitle = '';
        String strWorkHours = '';
        Date dteStartDate = null;
        Double dblHourlyPay = null;
        
        String strRecentEmployer = '';
        String strRecentEmployerType = '';
        Date dtRecentStartDate = null;
        Date dtRecentEndDate = null;
        
        Date dtHoldEndDate = null;
        
        // Get Client Set for Update
        Set<Id> clientIds = new Set<Id>();
        for(Employment__c thisEmp : newEmployments) {
        
            clientIds.add(thisEmp.Client__c);
        }
        
        // Get Client and Employment records (sub-query)
        List<Contact> lstEffCont = [SELECT c.Job_Title__c, c.Employer__c, c.Current_Employment__c, (SELECT Hourly_Pay__c, Employment_Type__c, Job_Title__c, Start_Date__c, End_Date__c, Employer_Name__c, Work_Hours_from_and_to__c FROM Client__r ORDER BY Start_Date__c ASC) FROM Contact c Where Id in :clientIds];
        
        // Start Looping and Testing Contact
        for (Contact thisContact : lstEffCont) {
            
            // Clear out variables
            strCurEmployment = 'Unemployed';
            strEmployer = '';
            strJobTitle = '';
            strWorkHours = '';
            dteStartDate = null;
            dblHourlyPay = null;
            //random start date of 1/1/1950
            dtHoldEndDate = date.newInstance(1950, 1, 1);
            
            // Enter Employment__c sub-loop
            for (Employment__c thisEmp : thisContact.Client__r) {
                
                // Check for single record vs. multiple records
                if (thisContact.Client__r.size() == 1) {
                    
                    if (thisEmp.End_Date__c == null) {
                        strCurEmployment = thisEmp.Employment_Type__c;
                        strEmployer = thisEmp.Employer_Name__c;
                        strJobTitle = thisEmp.Job_Title__c;
                        strWorkHours = thisEmp.Work_Hours_from_and_to__c;
                        dteStartDate = thisEmp.Start_Date__c;
                        dblHourlyPay = thisEmp.Hourly_Pay__c;
                    }
                        //20120913 ebg - BT-030
                        strRecentEmployer = thisEmp.Employer_Name__c;
                        strRecentEmployerType = thisEmp.Employment_Type__c;
                        dtRecentStartDate = thisEmp.Start_Date__c;
                        dtRecentEndDate = thisEmp.End_Date__c;

                    
                } else {
                    // The subquery is sorted by start date, subsequent looping will bring forward the correct values on the last run
                    
                    if (thisEmp.End_Date__c == null) {
                        strCurEmployment = thisEmp.Employment_Type__c;
                        strEmployer = thisEmp.Employer_Name__c;
                        strJobTitle = thisEmp.Job_Title__c;
                        strWorkHours = thisEmp.Work_Hours_from_and_to__c;
                        dteStartDate = thisEmp.Start_Date__c;
                        dblHourlyPay = thisEmp.Hourly_Pay__c;
                        
                        //20120913 ebg - BT-030
                        strRecentEmployer = thisEmp.Employer_Name__c;
                        strRecentEmployerType = thisEmp.Employment_Type__c;
                        dtRecentStartDate = thisEmp.Start_Date__c;
                        dtRecentEndDate = thisEmp.End_Date__c;
                        
                        
                    } else {
                        if (thisEmp.End_Date__c > dtHoldEndDate) {
                            strRecentEmployer = thisEmp.Employer_Name__c;
                            strRecentEmployerType = thisEmp.Employment_Type__c;
                            dtRecentStartDate = thisEmp.Start_Date__c;
                            dtRecentEndDate = thisEmp.End_Date__c;
                        }
                    }
                    dtHoldEndDate = thisEmp.End_Date__c;
                    
                }
                
                                
            }
            
            /////////////////////////
            // Update Contact Fields
            /////////////////////////
            
            thisContact.Current_Employment__c = strCurEmployment;
            thisContact.Employer__c = strEmployer;
            thisContact.Job_Title__c = strJobTitle;
            thisContact.Work_Hours_from_and_to__c = strWorkHours;
            thisContact.Start_Date__c = dteStartDate;
            thisContact.Hourly_Pay__c = dblHourlyPay;   
            
            //20120913 ebg - BT-030
            thisContact.Most_Recent_Employer__c = strRecentEmployer;
            thisContact.Most_Recent_Employment_Type__c = strRecentEmployerType;
            thisContact.Most_Recent_Employment_Start_Date__c = dtRecentStartDate;
            thisContact.Most_Recent_Employment_End_Date__c = dtRecentEndDate;
                    
        }
        
        // Commit Updates
        update lstEffCont;
    }
}