src/objects/FollowUp__c.object
<CustomObject>
    <description>Details individual as well as monthly PRP program follow ups</description>
    <fields>
        <fullName>Date_Of_Follow_Up__c</fullName>
        <label>Date Of Follow Up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Discharge_Date_By_Phone_Visit__c</fullName>
        <label>Discharge Date By Phone/Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discharge_Transfer_Reason__c</fullName>
        <label>Discharge/Transfer Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Outcome__c</fullName>
        <label>Follow Up Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Status Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Status Not Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Program_Start_Date_If_Any__c</fullName>
        <label>New Program Start Date (If Any)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Relationships__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Relationship</label>
        <referenceTo>Program_Relationships__c</referenceTo>
        <relationshipLabel>Follow Up</relationshipLabel>
        <relationshipName>FollowUps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Start_Date__c</fullName>
        <formula>Program_Relationships__r.Program_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <picklist>
            <picklistValues>
                <fullName>Never Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FLWU-{00000}</displayFormat>
        <label>Follow Up</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Up</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Relationships__c.object
<CustomObject>
    <description>Details relationship between warrant | program | client</description>
    <fields>
        <fullName>Discharge_Date_Phone_Visit__c</fullName>
        <inlineHelpText>For ACS Involvement, this it the Closing Date of the case.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discharge_Transfer_Reason__c</fullName>
        <label>Discharge/Transfer Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Verified_Phone_Visit__c</fullName>
        <label>Last Verified by Phone/Visit</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Program_Start_Date__c</fullName>
        <inlineHelpText>The Star Date is the date on which the linkage is made.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Status_Phone_Visit__c</fullName>
        <label>Program Status by Phone/Visit</label>
        <picklist>
            <picklistValues>
                <fullName>Never Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program Relationships</label>
    <nameField>
        <displayFormat>PR-C{0}</displayFormat>
        <label>Program Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/programRelationshipMethods.cls
public with sharing class programRelationshipMethods {
    
    public void updateProgRelNonPRP(List<Id> lstPRIds) {
        
        //lists and maps
        //map<id, FollowUp__c> mapMostRecentFU = new map<id, FollowUp__c>();
        
        //find related Program Relationships
        list<Program_Relationships__c> lstPRs =  [select id, Discharge_Date_Phone_Visit__c, 
        Last_Verified_Phone_Visit__c, Program_Status_Phone_Visit__c, Discharge_Transfer_Reason__c, 
        Program_Start_Date__c,
        (select id, Program_Relationships__c, Date_Of_Follow_Up__c, Program_Status__c, 
        Discharge_Transfer_Reason__c, Discharge_Date_By_Phone_Visit__c, New_Program_Start_Date_If_Any__c 
        from FollowUps__r where Follow_Up_Outcome__c = 'Status Confirmed' 
        order by Date_Of_Follow_Up__c desc limit 1)
        from Program_Relationships__c where id in :lstPRIds];
        
        //get most recent successful follow up for each PR in scope
        /*for(Program_Relationships__c pr: [select id, name, 
        (select id, Program_Relationships__c, Date_Of_Follow_Up__c, Program_Status__c, 
        Discharge_Transfer_Reason__c, Discharge_Date_By_Phone_Visit__c, New_Program_Start_Date_If_Any__c 
        from FollowUps__r where Follow_Up_Outcome__c = 'Status Confirmed' 
        order by Date_Of_Follow_Up__c desc limit 1) from Program_Relationships__c 
        where id in :lstPRIds]) {
            
            for(FollowUp__c fu: pr.FollowUps__r) {
                
                mapMostRecentFU.put(pr.id, fu);
            }
        }*/
            
        //set values on program relationship    
        for(Program_Relationships__c pr: lstPRs) {
            
            //PR won't be in map if there were no "status confirmed" follow ups related to it
            if(pr.FollowUps__r.size() == 0) {
                
                pr.Discharge_Date_Phone_Visit__c = null;
                pr.Discharge_Transfer_Reason__c = null;
                pr.Last_Verified_Phone_Visit__c = null;
                pr.Program_Status_Phone_Visit__c = 'Pending Intake';
            } else {
                
                pr.Last_Verified_Phone_Visit__c = pr.FollowUps__r[0].Date_Of_Follow_Up__c;
                pr.Discharge_Date_Phone_Visit__c = pr.FollowUps__r[0].Discharge_Date_By_Phone_Visit__c;
                pr.Discharge_Transfer_Reason__c = pr.FollowUps__r[0].Discharge_Transfer_Reason__c;
                pr.Program_Status_Phone_Visit__c = pr.FollowUps__r[0].Program_Status__c;
                if(pr.FollowUps__r[0].New_Program_Start_Date_If_Any__c != null) {
                    
                    pr.Program_Start_Date__c = pr.FollowUps__r[0].New_Program_Start_Date_If_Any__c;
                }                
            }   
        }   
        
        //dml
        update lstPRs;
    }
}