src/objects/FollowUp__c.object
<CustomObject>
    <description>Details individual as well as monthly PRP program follow ups</description>
    <fields>
        <fullName>Date_Of_Follow_Up__c</fullName>
        <label>Date Of Follow Up</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Discharge_Date_By_Phone_Visit__c</fullName>
        <label>Discharge Date By Phone/Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discharge_Transfer_Reason__c</fullName>
        <label>Discharge/Transfer Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Outcome__c</fullName>
        <label>Follow Up Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Status Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Status Not Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Left Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Response</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program_Relationships__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Relationship</label>
        <referenceTo>Program_Relationships__c</referenceTo>
        <relationshipLabel>Follow Up</relationshipLabel>
        <relationshipName>FollowUps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Status__c</fullName>
        <label>Program Status</label>
        <picklist>
            <picklistValues>
                <fullName>Never Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Intake</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>QC: Hidden field, used for filtered lookup of Verified With</description>
        <formula>Program_Relationships__r.Program__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warrant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links parole officer follow up to warrant (contact)</description>
        <label>Warrant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Parole Office Follow Up</relationshipLabel>
        <relationshipName>Follow_Up1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Follow Up</label>
    <nameField>
        <displayFormat>FLWU-{00000}</displayFormat>
        <label>Follow Up</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Up</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>Girl Rising, ATD or Supreme Court Boys</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Relationships__c.object
<CustomObject>
    <description>Details relationship between warrant | program | client</description>
    <fields>
        <fullName>Discharge_Date_Phone_Visit__c</fullName>
        <inlineHelpText>For ACS Involvement, this it the Closing Date of the case.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Discharge_Transfer_Reason__c</fullName>
        <label>Discharge/Transfer Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Verified_Phone_Visit__c</fullName>
        <label>Last Verified by Phone/Visit</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Program_Status_Phone_Visit__c</fullName>
        <label>Program Status by Phone/Visit</label>
        <picklist>
            <picklistValues>
                <fullName>Never Enrolled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Successful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsuccessful</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly &quot;Program&quot;, Formerly Treatment Agency, changed 9/29/13 for START by MB</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Entities, Treatment Agency, CASES Programs</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Warrant Relationships</relationshipLabel>
        <relationshipName>Program_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Date__c</fullName>
        <label>Referral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Warrant__c</fullName>
        <description>previously referred to as &quot;PRP Cycle&quot;, changed by MB 9/29/13</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Relationships</relationshipLabel>
        <relationshipName>Program_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Relationships</label>
    <nameField>
        <displayFormat>PR-C{0}</displayFormat>
        <label>Program Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Program_Relationships_Unit_Test.cls
@isTest(SeeAllData=true)
public class Program_Relationships_Unit_Test {

    static testMethod void testProgRelUpdate() {
        
        utilityIds utilIds = new utilityIds();
        
        //treatment orgs
        Account accReferralOrg1 = new Account(Name = 'Treatment Agency Test 1');
        
        Account accReferralOrg2 = new Account(Name = 'Treatment Agency Test 2');    
        
        //dml
        insert new sObject[]{accReferralOrg1, accReferralOrg2};
        
        //clients- accounts
        Account accClient1 = new Account(Name = 'Test Contact 1',  
        RecordTypeId = utilIds.accClient);
                
        Account accClient2 = new Account(Name = 'Test Contact 2',
        RecordTypeId = utilIds.accClient);   
        
        //dml
        insert new sObject[]{accClient1, accClient2};            
        
        //clients- contacts
        Contact c1 = new Contact(LastName = 'Test Contact 1', recordtypeid = utilIds.conDTC, 
        AccountId = accClient1.id);
        
        Contact c2 = new Contact(LastName = 'Test Contact 2', recordtypeid = utilIds.conCCM, 
        AccountId = accClient2.id);
        
        //dml
        insert new sObject[]{c1, c2};           
        
        //program relationships
        Program_Relationships__c c1pr1 = new Program_Relationships__c(Warrant__c = c1.id, 
        Program__c = accReferralOrg1.id, Referral_Date__c = date.newInstance(2013, 06, 1), 
        recordtypeId = utilIds.progRelReferral);
        
        Program_Relationships__c c1pr2 = new Program_Relationships__c(Warrant__c = c1.id, 
        Program__c = accReferralOrg2.id, Referral_Date__c = date.newInstance(2013, 06, 6), 
        recordtypeId = utilIds.progRelReferral);      
        
        Program_Relationships__c c2pr1 = new Program_Relationships__c(Warrant__c = c2.id, 
        Program__c = accReferralOrg1.id, Referral_Date__c = date.newInstance(2013, 06, 9), 
        recordtypeId = utilIds.progRelReferral);      
        
        //dml
        insert new sObject[]{c1pr1, c1pr2, c2pr1};
        
        // follow ups
        FollowUp__c c1pr1f1 = New FollowUp__c(Program_Relationships__c = c1pr1.id, 
        Date_Of_Follow_Up__c = dateTime.newInstance(2013, 06, 5, 12, 30, 1), Follow_Up_Outcome__c = 'Status Confirmed',
        Program_Status__c = 'Active', RecordTypeId = utilIds.FollowUpReferral );
        
        FollowUp__c c1pr1f2 = New FollowUp__c(Program_Relationships__c = c1pr1.id, 
        Date_Of_Follow_Up__c = dateTime.newInstance(2013, 06, 6, 12, 30, 1), Follow_Up_Outcome__c = 'Status Not Confirmed', 
        RecordTypeId = utilIds.FollowUpReferral);       
        
        FollowUp__c c1pr2f1 = New FollowUp__c(Program_Relationships__c = c1pr2.id, 
        Date_Of_Follow_Up__c = dateTime.newInstance(2013, 06, 8, 12, 30, 1), Follow_Up_Outcome__c = 'Status Confirmed',
        Program_Status__c = 'Active', RecordTypeId = utilIds.FollowUpReferral);     

        FollowUp__c c1pr2f2 = New FollowUp__c(Program_Relationships__c = c1pr2.id, 
        Date_Of_Follow_Up__c = dateTime.newInstance(2013, 06, 10, 12, 30, 1), Follow_Up_Outcome__c = 'Status Confirmed',
        Program_Status__c = 'Successful', Discharge_Date_By_Phone_Visit__c = date.newInstance(2013, 06, 10),
        Discharge_Transfer_Reason__c = 'Completed program', RecordTypeId = utilIds.FollowUpReferral);       
        
        FollowUp__c c2pr1f1 = New FollowUp__c(Program_Relationships__c = c2pr1.id, 
        Date_Of_Follow_Up__c = dateTime.newInstance(2013, 06, 11, 12, 30, 1), Follow_Up_Outcome__c = 'Status Not Confirmed',
        Program_Status__c = 'Never Enrolled', RecordTypeId = utilIds.FollowUpReferral);
        
        //dml
        insert new sObject[]{c1pr1f1, c1pr1f2, c1pr2f1, c1pr2f2, c2pr1f1};
        
        //query current field values to check if insert worked correctly
        map<Id, Program_Relationships__c> results = new map<Id, Program_Relationships__c>(
        [select id, Program_Status_Phone_Visit__c, Last_Verified_Phone_Visit__c, 
        Discharge_Transfer_Reason__c, Discharge_Date_Phone_Visit__c
        from Program_Relationships__c where id = :c1pr1.id or id = :c1pr2.id or id = :c2pr1.id]);           
        
        //check c1pr1
        system.assertEquals(results.get(c1pr1.id).Program_Status_Phone_Visit__c, null);
        system.assertEquals(results.get(c1pr1.id).Last_Verified_Phone_Visit__c, dateTime.newInstance(2013, 06, 5, 12, 30, 1));      
        
        //check c1pr2
        system.assertEquals(results.get(c1pr2.id).Program_Status_Phone_Visit__c, null);     
        system.assertEquals(results.get(c1pr2.id).Last_Verified_Phone_Visit__c, dateTime.newInstance(2013, 06, 10, 12, 30, 1));
        system.assertEquals(results.get(c1pr2.id).Discharge_Transfer_Reason__c, 'Completed program');
        system.assertEquals(results.get(c1pr2.id).Discharge_Date_Phone_Visit__c, date.newInstance(2013, 06, 10));
        
        //check c2pr1
        system.assertEquals(results.get(c2pr1.id).Program_Status_Phone_Visit__c, null);
        
        
        //modify follow ups to check update and delete processing
        c1pr1f2.Follow_Up_Outcome__c = 'Status Confirmed';
        c1pr1f2.Program_Status__c = 'Pending Intake';
        
        update c1pr1f2;
        delete c1pr2f2;
        
        //query current field values to check if insert worked correctly
        map<Id, Program_Relationships__c> results2 = new map<Id, Program_Relationships__c>(
        [select id, Program_Status_Phone_Visit__c, Last_Verified_Phone_Visit__c, 
        Discharge_Transfer_Reason__c, Discharge_Date_Phone_Visit__c
        from Program_Relationships__c where id = :c1pr1.id or id = :c1pr2.id or id = :c2pr1.id]);       
        
        //check c1pr1
        system.assertEquals(results2.get(c1pr1.id).Program_Status_Phone_Visit__c, null);        
        system.assertEquals(results2.get(c1pr1.id).Last_Verified_Phone_Visit__c, dateTime.newInstance(2013, 06, 6, 12, 30, 1));
        
        //check c1pr2               
        system.assertEquals(results2.get(c1pr2.id).Program_Status_Phone_Visit__c, null);        
        system.assertEquals(results2.get(c1pr2.id).Last_Verified_Phone_Visit__c, dateTime.newInstance(2013, 06, 8, 12, 30, 1));     
        system.assertEquals(results2.get(c1pr2.id).Discharge_Transfer_Reason__c, null); 
                                        
    }
}