src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Program_Plan__r.Client_Name__r.FirstName &amp; &apos; &apos; &amp;  Program_Plan__r.Client_Name__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Objective</label>
        <picklist>
            <controllingField>Area__c</controllingField>
            <picklistValues>
                <fullName>Abstain from alcohol and drug use</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete CEP&apos;s substance use group.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment Assessment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment Readiness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfill community service obligations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfill court obligations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfill probation obligations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participate in assessment/counseling services with CEP-EBH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participate in internal drug counseling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participate in outpatient counseling services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participate in outpatient drug treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursue basic Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursue Career Exploration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursue college degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursue employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursue GED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursue high school diploma</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursue vocational training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resume</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Other_Goal__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Plan__c</fullName>
        <label>Program Plan</label>
        <referenceTo>Program_Plan__c</referenceTo>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Objective</label>
    <nameField>
        <displayFormat>Obj-{00000}</displayFormat>
        <label>Objective Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Plans</relationshipLabel>
        <relationshipName>Program_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Diagnosis_New__c</fullName>
        <label>Current Diagnosis (New)</label>
        <picklist>
            <picklistValues>
                <fullName>(33) Intellectual Disability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(41) Global Developmental Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(41) Unspecified Intellectual Disability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(42) Language Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(44) Speech Sound Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(45) Childhood-Onset Fluency Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(47) Social Communication Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(49) Unspecified Communication Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(50) Autism Spectrum Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(59) Attention-Deficit/Hyper Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(65) Other Specified AD/H Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(66) Unspecified AD/H Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(66) Specific Learning Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(86) Other Specified Neurodev Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(86) Unspecified Neurodev Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(90) Schizotypal (Personality) Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(90) Delusional Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(94) Brief Psychotic Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(96) Schizophreniform Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(99) Schizophrenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(105) Schizoaffective Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(110) Subst/Med-Induced Psych Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(115) Psych Disorder Due to Medical Cond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(119) Catatonia Assoc w/ Mental Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(120) Catatonic Disorder Due to Med Cond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(121) Unspecified Catatonia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(122) Other Spec Schiz Spectrum/Psych</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(122) Unspecified Schiz Spectrum/Psych</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(123) Bipolar I Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(132) Bipolar II Disorder</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Current_Diagnosis_for_DOHMH__c</fullName>
        <description>Reporting field for DOHMH that displays a semicolon-separated list of DSM codes without text names</description>
        <label>Current Diagnosis for DOHMH</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goals__c</fullName>
        <label>Goal(s)</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Jail_Based_Diagnosis_New__c</fullName>
        <label>Jail-Based Diagnosis (New)</label>
        <picklist>
            <picklistValues>
                <fullName>(33) Intellectual Disability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(41) Global Developmental Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(41) Unspecified Intellectual Disability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(42) Language Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(44) Speech Sound Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(45) Childhood-Onset Fluency Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(47) Social Communication Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(49) Unspecified Communication Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(50) Autism Spectrum Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(59) Attention-Deficit/Hyper Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(65) Other Specified AD/H Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(66) Unspecified AD/H Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(66) Specific Learning Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(86) Other Specified Neurodev Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(86) Unspecified Neurodev Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(90) Schizotypal (Personality) Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(90) Delusional Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(94) Brief Psychotic Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(96) Schizophreniform Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(99) Schizophrenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(105) Schizoaffective Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(110) Subst/Med-Induced Psych Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(115) Psych Disorder Due to Medical Cond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(119) Catatonia Assoc w/ Mental Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(120) Catatonic Disorder Due to Med Cond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(121) Unspecified Catatonia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(122) Other Spec Schiz Spectrum/Psych</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(122) Unspecified Schiz Spectrum/Psych</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(123) Bipolar I Disorder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(132) Bipolar II Disorder</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Jail_Based_Diagnosis_for_DOHMH__c</fullName>
        <label>Jail-Based Diagnosis for DOHMH</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Program_Plan__c</fullName>
        <formula>Client_Name__r.Most_Recent_Program_Plan__c = Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Most Recent Program Plan?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Plan_Completed_On__c</fullName>
        <description>Date Completed By button was pushed</description>
        <label>Program Plan Completed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Plan_Completed_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the person who clicked on the Completed Button</description>
        <label>Program Plan Completed by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Plan_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Program Plan Locked</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/programPlanMethods.cls
public with sharing class programPlanMethods {

    public utilityIds util = new utilityIds();
    
    // Method called to lock the record
    // and redirect to the record

    public PageReference lockRecord() {
        
        String recordId = ApexPages.currentPage().getParameters().get('id');
        
        if(recordId != null) {
            
            list<Program_Plan__c> lstProgramPlans = [Select Id, 
                                                    Client_name__c,
                                                    Program_Plan_locked__c, 
                                                    Program_Plan_Completed_by__c,
                                                    Program_Plan_Completed_On__c, 
                                                    RecordTypeId, //Initial_Objectives__c,
                                                    (select id, Goal__c, Other_Goal__c from Goals__r)
                                                    From Program_Plan__c where Id = :recordId];
            list<Id> lstContactIds = new List<Id>();
            
            for(Program_Plan__c p: lstProgramPlans) {
                
                lstContactIds.add(p.client_name__c);
            }

            
            lockProgramPlan(lstProgramPlans);
            closeAssociatedTask( lstContactIds);
            
            //// reload the page
            PageReference newPage = new PageReference('/' + recordId);
            newPage.setRedirect(true);
            return newPage;
                    
        } else {    
            return null;
        }
    }
    
    public void lockProgramPlan(List<Program_Plan__c> lstProgramPlans) {
        
        // Flip the record type to the locked one
                                               
        for(Program_Plan__c pp: lstProgramPlans) {
            pp.recordTypeId =   util.programPlanLockedRecordType;
            pp.Program_Plan_locked__c = true;
            pp.Program_Plan_Completed_On__c = System.Today();
            pp.Program_Plan_Completed_by__c = UserInfo.getUserId();
            /*pp.Initial_Objectives__c = null;
            for(Goal__c g: pp.Goals__r) {
                
                if(pp.Initial_Objectives__c != null) {
                    
                    pp.Initial_Objectives__c += ', ' + (g.Goal__c == 'Other'?g.Other_Goal__c:g.Goal__c);
                } else {
                    pp.Initial_Objectives__c = (g.Goal__c == 'Other'?g.Other_Goal__c:g.Goal__c);
                }
            }*/
        }                                                 
    
        update lstProgramPlans; 
        
    }
    
    public void closeAssociatedTask(List<Id> lstcontactIds) {
        
        list<Task> lstprogramPlanTasks = [Select    Id,
                                        Status,
                                        ActivityDate,
                                        Closing_Date__c,
                                        Closed_By_System__c,
                                        SkipRestrictions__c
                                        From Task
                                        Where WhoId in :lstcontactIds
                                        AND recordTypeId = :util.initialProgramPlanTask
                                        AND isClosed = false];
                    
        for(Task programPlanTask: lstprogramPlanTasks) {
            
            if(System.Today()  <= programPlanTask.ActivityDate ) {
                
                programPlanTask.Status = 'Done on Time';        
            } else {
                
                programPlanTask.Status = 'Done Late';
            }
            
            programPlanTask.Closing_Date__c = System.Today();
            programPlanTask.Closed_By_System__c = true;
            programPlanTask.SkipRestrictions__c = true; 
        }
                    
        update lstprogramPlanTasks;                         
    
    }
    
    public void setMostRecentProgramPlan(List<Program_Plan__c> lstNewPlans) {
        
        list<Id> lstContactIds = new list<Id>();       
        
        for(Program_Plan__c p: lstNewPlans) {
            
            lstContactIds.add(p.Client_Name__c);
        }
        
        list<Contact> lstContacts = [select Id, Most_Recent_Program_Plan__c,
                                            (select Id, CreatedDate
                                            from Program_Plans__r order by CreatedDate asc) 
                                            from Contact where Id in :lstContactIds];
        
        Program_Plan__c mostRecentPlan = new Program_Plan__c();
                                            
        for(Contact c: lstContacts) {
            
            mostRecentPlan = new Program_Plan__c();
            
            for(Program_Plan__c currentPlan: c.Program_Plans__r) {
                            
                MostRecentPlan = currentPlan;
            }
            
            c.Most_Recent_Program_Plan__c = mostRecentPlan.Id;
        }                                   
        
        update lstContacts;
    }
    
    public void setDOHMHDiagnosisFields(List<Program_Plan__c> lstProgramPlans) {
    
        for(Program_Plan__c pp: lstProgramPlans) {
        
            if(pp.Current_Diagnosis_New__c != null) {
                pp.Current_Diagnosis_for_DOHMH__c 
                    = pp.Current_Diagnosis_New__c.replaceAll('[A-z]|[ ]|[(]|[/]|[-]', '').replace(';','').replace(')',';');
            } else {
                pp.Current_Diagnosis_for_DOHMH__c = null;
            }
            
            if(pp.Jail_Based_Diagnosis_New__c!= null) {
                pp.Jail_Based_Diagnosis_for_DOHMH__c 
                    = pp.Jail_Based_Diagnosis_New__c.replaceAll('[A-z]|[ ]|[(]|[/]|[-]', '').replace(';','').replace(')',';');
            } else {
            
                pp.Jail_Based_Diagnosis_for_DOHMH__c = null;
            }            
        }
    }
}