src/objects/Health_and_Wellbeing_Assessment__c.object
<CustomObject>
    <description>Biospsychosocial and substance abuse assessment form designed by Andrea Yaffee. 12/2017</description>
    <fields>
        <fullName>AssessmentID__c</fullName>
        <description>Link to assessment object</description>
        <label>Assessment ID</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipName>CEP_BPS_Assessments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordType.Name</field>
                <operation>equals</operation>
                <value>CEP Client</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>CEP_BPS_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Health and Wellbeing Assessment</label>
    <nameField>
        <displayFormat>HWB-{0000}</displayFormat>
        <label>HWB ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health and Wellbeing Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Life_Events_Checklist__c.object
<CustomObject>
    <description>Assessment for CHOICES. 
LEC Blake, Weathers, Nagy, Kaloupek, Charney, &amp; Keane, 1995</description>
    <fields>
        <fullName>AssessmentId__c</fullName>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>Life Events Checklists</relationshipLabel>
        <relationshipName>Life_Events_Checklists</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <label>Participant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Life Events Checklists</relationshipLabel>
        <relationshipName>Life_Events_Checklists</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Life Events Checklist</label>
    <nameField>
        <displayFormat>LEC-{0000}</displayFormat>
        <label>LEC RecNum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Life Events Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SR_Intake_Needs_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>AssessmentID__c</fullName>
        <description>Parent ID of this assessment</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>SR Intake Needs Assessments</relationshipLabel>
        <relationshipName>SR_Intake_Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Specific assessments have two master-detail relationships (Assessment and Contact)</description>
        <label>Participant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SR Intake Needs Assessments</relationshipLabel>
        <relationshipName>SR_Intake_Needs_Assessments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SR Intake Needs Assessment</label>
    <nameField>
        <displayFormat>SR-NA{0000}</displayFormat>
        <label>SR Intake Needs Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Intake Needs Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/assessmentDispatchExt.cls
public with sharing class assessmentDispatchExt
{
    public String retURL = ApexPages.currentPage().getParameters().get('retURL');
    private final Assessment__c assessDispatch;
    public PageReference pageRef;


    public assessmentDispatchExt(ApexPages.StandardController stdController) 
    {
        stdController.addFields(new List<String>{'ChildObjectId__c'});        
        this.assessDispatch = (Assessment__c)stdController.getRecord();
        system.debug('ASSESSDISPATCH: ' + assessDispatch);
    }

    public pageReference initialize()
    {
        if(assessDispatch.Id == null)
        {
            String contactId = ApexPages.currentPage().getParameters().get('contactId');
            Id rtype = ApexPages.currentPage().getParameters().get('RecordType');
            String recordTypeName = [Select Name from RecordType where Id=:rtype LIMIT 1][0].Name;
            assessDispatch.Contact__c = contactId;

            assessDispatch.RecordTypeId = rtype;
            insert assessDispatch;
          
            if (recordTypeName == 'SR Intake Needs Assessment')
            {
                SR_Intake_Needs_Assessment__c srNeeds = New SR_Intake_Needs_Assessment__c();
                srNeeds.AssessmentID__c =assessDispatch.Id;
                srNeeds.Participant__c = assessDispatch.Contact__c;
                insert srNeeds;
                assessDispatch.SR_Intake_Needs__c = srNeeds.Id;
                assessDispatch.ChildObjectId__c = srNeeds.Id;
                pageRef= new PageReference('/'+ assessDispatch.SR_Intake_Needs__c + '/e');
                system.debug('pageRefSR: ' + pageRef);
            } else if (recordTypeName == 'Life Events Checklist (LEC)')
                {
                    Life_Events_Checklist__c lec = New Life_Events_Checklist__c();
                    lec.AssessmentID__c =assessDispatch.Id;
                    lec.Participant__c = assessDispatch.Contact__c;
                    insert lec;
                    assessDispatch.ChildObjectId__c = lec.Id;
                    pageRef= new PageReference('/'+ lec.Id + '/e');
                    system.debug('pageRefLEC: ' + pageRef);
                    assessDispatch.ChildObjectId__c = lec.Id;
                } else if (recordTypeName == 'Health and Wellbeing Assessment')
                    {
                        Health_and_Wellbeing_Assessment__c hwb = New Health_and_Wellbeing_Assessment__c();
                        hwb.AssessmentID__c =assessDispatch.Id;
                        hwb.Participant__c = assessDispatch.Contact__c;
                        insert hwb;
                        assessDispatch.ChildObjectId__c = hwb.Id;
                        pageRef= new PageReference('/'+ hwb.Id + '/e');
                        system.debug('pageRefHwb: ' + pageRef);
                        assessDispatch.ChildObjectId__c = hwb.Id;
                    }

            assessDispatch.ChildRecordType__c = recordTypeName;            
            update assessDispatch;
        }
        pageRef= new PageReference('/'+ assessDispatch.ChildObjectId__c + '/e');
        system.debug('pageRef: ' + pageRef);
        pageRef.setRedirect(true);
        return pageRef;
    }

}