src/objects/Incident_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Incident_Report__c</fullName>
        <label>Incident Report</label>
        <referenceTo>Incident_Report__c</referenceTo>
        <relationshipLabel>Incident Participants</relationshipLabel>
        <relationshipName>Incident_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Incident Participant</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Incident Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Incident_Report__c.object
<CustomObject>
    <label>Incident Report</label>
    <nameField>
        <label>Brief Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <fields>
        <fullName>Hashtags__c</fullName>
        <inlineHelpText>This field is for reporting only, it cannot be edited by users. It lists all of the hashtags which were included at the bottom of the note itself.</inlineHelpText>
        <label>Hashtags</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incident_Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Lookup</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This client has not been involved in any Incidents.</errorMessage>
            <filterItems>
                <field>Incident_Participation__c.Program_Plan__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program_Plan__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Incident_Participation__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Incident Report</label>
        <referenceTo>Incident_Report__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Progress_Note__c</fullName>
        <label>Progress Note</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>System_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Generated</label>
        <type>Checkbox</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>P_Note-{0000}</displayFormat>
        <label>Progress Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/progressNoteMethods.cls
public class progressNoteMethods {
    
    //this class added 5/21/13 by MB to move logic out of progressNotesLogic trigger
    
    public utilityMethods clsUtilMethods = new utilityMethods();
    public utilityIds clsUtilIds = new utilityIds();    
    
    public list<Progress_Note__c> lstNotes = new list<Progress_Note__c>();
    public list<Progress_Note__c> lstOldNotes = new list<Progress_Note__c>();
    public Boolean bolInsert = null;
    
    //This method extracts any Hashtag phrases from the Progress Note and puts them into a separate field which can be reported on.
    public void setHashtags() {
    
        integer i = 0;
        String strPN = '';
        String strHash = '';
        integer intEnd = 0;
        integer intNextSpace = 0;
        integer intNextLineBreak = 0;
        
        // 10/21/14 new method for Samantha Koller. Wrapping in try-catch because it has not been thoroughly tested
        // and we don't want saving a progress note to throw an error just on account of this
        try {
    
            for(Progress_Note__c pn: lstNotes) {
            
                strPN = pn.Progress_Note__c;
                strHash = '';
                
                if(bolInsert || strPN!= lstOldNotes[i].Progress_Note__c) {
                
                    
                    for(Integer currHashPos = strPN.indexOf('#'); currHashPos != -1; currHashPos = strPN.indexOf('#',currHashPos+1)) {
                        
                        intNextSpace = strPN.indexOf(' ', currHashPos+2);
                        intNextLineBreak = strPN.indexOf('\n', currHashPos+2);
                        
                        //if no space or line break ahead then take substring till end of the note
                        if( intNextSpace == -1 && intNextLineBreak == -1) {
                        
                            intEnd = strPN.length();
                        } else if(intNextSpace > -1 && intNextLineBreak > -1) {
                        
                            intEnd = math.Min(intNextSpace, intNextLineBreak);
                        } else {//the only other condition is if one character was found. If so, take the position that's >-1
                            intEnd = math.Max(intNextSpace, intNextLineBreak);
                        }
                            
                        //add current hashtag to list   
                        strHash += strPN.subString(currHashPos, intEnd) + ' ';
                    }
                    
                    strHash = strHash.replaceAll('[!]|[.]|[?]|[,]|[;]', '');
                    strHash = strHash.trim();
                    strHash = strHash.replace('\r','');
                    strHash = strHash.replace('# ','#');
                    pn.Hashtags__c = strHash;
                }
                
                i++;
            }
        } catch (Exception e) {
        
        }
    }
    
    public void setIncidentReportField() {
        
        list<Id> lstPartIds = new list<Id>();       

        //get Ids
        for(Progress_Note__c pn : lstNotes) {   
            
            lstPartIds.add(pn.Incident_Participant__c);
        }   
        
        // query Incident Participation records
        map<Id, Incident_Participation__c> mapPPtoReport = new Map<Id, Incident_Participation__c>(
        [select id, Incident_Report__c from Incident_Participation__c where id in :lstPartIds]);

                 
        for(Progress_Note__c pn : lstNotes) {                
            
        // added 5/21/13 MB for Incident Reporting
        // populate the Incident Report field based on the value in the Incident Participant field  
            if(pn.RecordTypeId == clsUtilIds.progressNoteIncidentReport ) {
                
                pn.Incident_Report__c = mapPPtoReport.get(pn.Incident_Participant__c).Incident_Report__c;   
            }
        }                           
        
    }

    public void blockManualGroupNoteCreation() {

        for(Progress_Note__c pn : lstNotes) {                
            
            // Group Note Validation
            system.debug('\n\n***INFO: Inserting/Updating progress note: ' + pn);
            if(pn.RecordTypeId == clsUtilIds.progressNoteGroup && pn.System_Generated__c == false) {
                pn.AddError('Group Notes can only be created through the Course Registration system!');
            }
        }
    }
    
    public void closeTasks() {
        
        
        //////////////////////////////////////////////
        // Determine which PN actions to take
        //////////////////////////////////////////////
        
        Boolean boolPSPNFlag = false;
        Boolean boolCCPNFlag = false;
        Boolean boolCCCRSFlag = false;
        Boolean boolPSCRSFlag = false; 
        Boolean boolIncidentFlag = false; 
        
        for(Progress_Note__c pn : lstNotes) {
            
            if(pn.RecordTypeId == clsUtilIds.progressNoteCCPN) { boolCCPNFlag = true; }
            else if(pn.RecordTypeId == clsUtilIds.progressNoteCCCRS) { boolCCCRSFlag = true; }
            else if(pn.RecordTypeId == clsUtilIds.progressNotePSPN) { boolPSPNFlag = true; }
            else if(pn.RecordTypeId == clsUtilIds.progressNotePSCRS) { boolPSCRSFlag = true; }
            else if(pn.RecordTypeId == clsUtilIds.progressNoteIncidentReport) { boolIncidentFlag = true; }
            
        }
        
        //////////////////////////////////////////////
        // Process CRS Task Notes (Order is important!)
        //////////////////////////////////////////////
        
        if(boolCCCRSFlag) { clsUtilMethods.closeCCCourtReportNoteTask(lstNotes, null, false); }
        if(boolPSCRSFlag) { clsUtilMethods.closePSCRSNoteTask(lstNotes); }
        
        //////////////////////////////////////////////
        // Process PN Task Notes (Order is important!)
        //////////////////////////////////////////////
        
        if(boolCCPNFlag) { clsUtilMethods.closeCCPNNoteTask(lstNotes); }
        if(boolPSPNFlag) { clsUtilMethods.closePSPNNoteTask(lstNotes); }
        
        //////////////////////////////////////////////
        // Incident Notes
        //////////////////////////////////////////////
        
        if(boolIncidentFlag) { clsUtilMethods.closeIncidentNoteTask(lstNotes); }        
    }
}