src/objects/Incident_Participation__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Incident Participants</relationshipLabel>
        <relationshipName>Incident_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident_Date__c</fullName>
        <formula>Incident_Report__r.Incident_Date__c</formula>
        <label>Incident Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incident_Report__c</fullName>
        <label>Incident Report</label>
        <referenceTo>Incident_Report__c</referenceTo>
        <relationshipLabel>Incident Participants</relationshipLabel>
        <relationshipName>Incident_Participants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Program_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Plan</label>
        <referenceTo>Program_Plan__c</referenceTo>
        <relationshipLabel>Incident Reports</relationshipLabel>
        <relationshipName>Incident_Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Incident Participant</label>
    <nameField>
        <displayFormat>IP-{000000}</displayFormat>
        <label>Incident Participation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incident Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Incident_Report__c.object
<CustomObject>
    <fields>
        <fullName>Degree_of_Harm_Caused__c</fullName>
        <inlineHelpText>No harm: no harm
Low harm: minor harm, first aid only
Moderate harm: moderate physical harm
Severe harm: serious physical injury</inlineHelpText>
        <label>Degree of Harm Caused</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moderate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Severe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Harm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Incident_Category__c</fullName>
        <label>Incident Category</label>
        <picklist>
            <picklistValues>
                <fullName>Threat of bodily harm to self or others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harassment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weapons possession</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assault</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victim of assault, harassment or crime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegation of abuse/neglect by parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegation of abuse/neglect by staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Possession of contraband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Theft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior that raises concerns for safety</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Incident_Date__c</fullName>
        <label>Incident Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incident_Description__c</fullName>
        <label>Incident Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Incident_Time__c</fullName>
        <label>Incident Time</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participants_Involved__c</fullName>
        <inlineHelpText>List the CASES clients who were involved in any way (perpetrators, victims, witnesses, provided assistance, etc)</inlineHelpText>
        <label>Participants Involved</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Incident Report</label>
    <nameField>
        <label>Brief Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incident Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Plans</relationshipLabel>
        <relationshipName>Program_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Program_Plan__c</fullName>
        <formula>Client_Name__r.Most_Recent_Program_Plan__c = Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Most Recent Program Plan?</label>
        <type>Checkbox</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <recordTypes>
        <fullName>Program_Plan</fullName>
        <active>true</active>
        <description>Use this for creating new program plans</description>
        <label>CEP Program Plan</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/incidentMethods.cls
public class incidentMethods {

    // this class added 5/21/13 MB. It includes methods for Incident Participants
    utilityIds utilIds = new utilityIds();
    
    public void setProgramPlanField(list<Incident_Participation__c> lstIPs) {
        
        list<Id> lstClientIds = new list<Id>();
        list<Program_Plan__c> lstPPs = new list<Program_Plan__c>();
        map<id, id> mapPPs = new map<id, id>();
        
        //get client ids
        for(Incident_Participation__c ip: lstIPs) {
            
            lstClientIds.add(ip.Client__c);     
        }
        
        //find all program plans
        lstPPs = [select id, client_name__c from Program_Plan__c where client_name__c in :lstClientIds 
                  and Most_Recent_Program_Plan__c = true];
                 
        //create a map
        for(Program_Plan__c pp: lstPPs) {   
            
            mapPPs.put(pp.Client_Name__c, pp.Id);
        }            
        
        //loop and set program_plan field on Incident Participation
        for(Incident_Participation__c ip: lstIps) {
                    
            //set field value
            ip.Program_Plan__c = mapPPs.get(ip.Client__c);      
        }           
        
    }
    
    
    public void sendIncidentReportEmail(list<Incident_Participation__c> lstParticipants) {
        
        //get Incident Reports
        list<Id> lstPartIds = new list<Id>();
        list<Id> lstReportIds = new list<Id>();
        
        for(Incident_Participation__c ip: lstParticipants) {
            
            lstPartIds.add(ip.id);
            lstReportIds.add(ip.Incident_Report__c);
        }
        
        list<Incident_Participation__c> lstReportInfo = [select id, Incident_Report__c,
                                                         Incident_Report__r.Name, 
                                                         Incident_Date__c, 
                                                         Incident_Report__r.Incident_Time__c,
                                                         Incident_Report__r.Degree_of_Harm_Caused__c, 
                                                         Incident_Report__r.Incident_Category__c, 
                                                         Incident_Report__r.Participants_Involved__c, 
                                                         Incident_Report__r.Incident_Description__c,
                                                         Client__r.RecordTypeId
                                                         from Incident_Participation__c where id in :lstPartIds];
        
        //build user list for each program
        
        map<String, List<String>> mapClientTypetoEmails = new map<String, List<String>>();      
        
        //all
        mapClientTypetoEmails.put('all', new list<String>());
        mapClientTypetoEmails.get('all').add(utilIds.cepDirector);
        mapClientTypetoEmails.get('all').add(utilIds.cepDeputyDirector);
        
        //CEP
        mapClientTypetoEmails.put(utilIds.conClient, new list<String>());   
        mapClientTypetoEmails.get(utilIds.conClient).add(utilIds.courtServicesSupervisor);
        
        //CJC/JS
        mapClientTypetoEmails.put(utilIds.conCJC, new list<String>());
        mapClientTypetoEmails.put(utilIds.conJS, new list<String>());
        mapClientTypetoEmails.get(utilIds.conCJC).add(utilIds.cjcJSAdmin);
        mapClientTypetoEmails.get(utilIds.conJS).add(utilIds.cjcJSAdmin);
        
        //QJC
        mapClientTypetoEmails.put(utilIds.conQJC, new list<String>());
        mapClientTypetoEmails.get(utilIds.conQJC).add(utilIds.qjcAdmin);
        
        //get emails
        
        list <User> lstTempUser = new list<User>();
        
        for(String clientType: mapClientTypetoEmails.keySet()) {
            
            lstTempUser = [select id, email from User 
                           where Profile.Id in :mapClientTypetoEmails.get(clientType) and isActive = true];
            mapClientTypetoEmails.put(clientType, new list<String>());
            
            for(User u: lstTempUser) {
                
                mapClientTypetoEmails.get(clientType).add(u.Email);
            }
        }
        
        // get all Incident Participant records for these reports, so we don't send duplicate emails
        list<Incident_Participation__c> lstAllParticipants = [select id, Client__c, Client__r.RecordTypeId, Incident_Report__c 
                                                                from Incident_Participation__c 
                                                                where Incident_Report__c in :lstReportIds];
                                                                                                                
        boolean bolEmailProgram = true;
        boolean bolEmailAll = true;                                                     
        list<String> lstTempToAddresses = new list<String>();   
        boolean bolDisplayTime = true;                                                  
        
        //send out a notification email for each incident report
        for(Incident_Participation__c ip: lstReportInfo) {
            
            //reset variables for each inserted participant record
            lstTempToAddresses = new list<String>();
            bolEmailProgram = true;
            bolEmailAll = true;
            bolDisplayTime = true;
            
            //don't send emails to program-specific staff if a client of the same record type was already added
            // to the report. don't send an email to the "all" staff if any participant was already added to the report
            for(Incident_Participation__c allIP:lstAllParticipants ) {
                
                if(ip.Incident_Report__c == allIP.Incident_Report__c && ip.Id != allIP.id) {
                    
                    //don't email the All folks
                    bolEmailAll = false;
                    
                    if(ip.Client__r.RecordTypeId == allIP.client__r.RecordTypeId
                    || !mapClientTypetoEmails.containsKey(ip.Client__r.RecordTypeId)) {
                        //don't email the program-specific folks
                        bolEmailProgram = false;
                        break;
                    }
                }
            }
            
            if(bolEmailProgram) {
                
                //add emails to TO: list
                if(mapClientTypetoEmails.containsKey(ip.Client__r.RecordTypeId)) {
                    lstTempToAddresses.addAll(mapClientTypetoEmails.get(ip.Client__r.RecordTypeId));
                }
            }
            
            if(bolEmailAll) {
                
                //add emails to TO: list
                lstTempToAddresses.addAll(mapClientTypetoEmails.get('all'));
                lstTempToAddresses.add('dmcclary@cases.org');
            }
            
            if(lstTempToAddresses.size() > 0) {
                
                if(ip.Incident_Report__r.Incident_Time__c == null) {
                    bolDisplayTime = false;
                }
            
                //set email text
                string mailText = 'Incident Date: ' + ip.Incident_Date__c.format();
                if(bolDisplayTime) {
                    mailText = mailText + ' at ' + ip.Incident_Report__r.Incident_Time__c;
                } 

                mailText = mailText + '\nDegree of Harm Caused: ' + ip.Incident_Report__r.Degree_of_Harm_Caused__c
                + '\nIncident Type: ' + ip.Incident_Report__r.Incident_Category__c
                + '\nParticipants Involved: ' + ip.Incident_Report__r.Participants_Involved__c
                + '\nLink to Incident Report in Salesforce: ' 
                +  URL.getSalesforceBaseUrl().toExternalForm() + '/' + ip.Incident_Report__c
                +'\n\nIncident Description: ' + ip.Incident_Report__r.Incident_Description__c;
                
                Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
                mail.setToAddresses(lstTempToAddresses);
                mail.setSubject('New Incident Report: ' + ip.Incident_Report__r.Name);
                mail.setPlainTextBody(mailText);
                mail.saveAsActivity = false;    
                
                //send message
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });                   
            }
        }
    }

}