src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Tier</label>
        <referenceTo>Tier__c</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tier Changes</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Most Recent Tier?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/tierMethods.cls
public class tierMethods {

    public list<Id> lstPCIds = new list<Id>();
    public list<Tier__c> lstTiers = new list<Tier__c>();
    
    public void setMostRecentFlag() {
        
        //get all tiers to loop through
        list<Program_Cycle__c> lstPCs = [select id, Most_Recent_Tier__c,
        (select id, Start_Date__c from Tiers__r order by Start_Date__c asc)
        from Program_Cycle__c
        where id in :lstPCIds];
        
        Tier__c tierMR = new Tier__c();
        
        for(Program_Cycle__c pc: lstPCs) {
        
            tierMR = new Tier__c();
            
            for(Tier__c t: pc.Tiers__r) {
            
                tierMr = t;
            }
            
            pc.Most_Recent_Tier__c = tierMr.Id;
        }
        
        //dml
        update lstPCs;
                                
    }
    
    public void setContact() {
        
        map<Id, Program_Cycle__c> mapPCs = new map<Id, Program_Cycle__c>([select id, Client__c 
                                                                      from Program_Cycle__c
                                                                      where id in :lstPCIDs]);
                                         
        for(Tier__c t: lstTiers) {
            
            t.Contact__c = mapPCs.get(t.Program_Cycle__c).Client__c; 
        }                                
    }

}