src/objects/Program__c.object
<CustomObject>
    <description>Girl Rising, ATD or Supreme Court Boys</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Relationships__c.object
<CustomObject>
    <description>Details relationship between warrant | program | client</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formerly &quot;Program&quot;, Formerly Treatment Agency, changed 9/29/13 for START by MB</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Entities, Treatment Agency, CASES Programs</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Warrant Relationships</relationshipLabel>
        <relationshipName>Program_Relationship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Warrant__c</fullName>
        <description>previously referred to as &quot;PRP Cycle&quot;, changed by MB 9/29/13</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Relationships</relationshipLabel>
        <relationshipName>Program_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Relationships</label>
    <nameField>
        <displayFormat>PR-C{0}</displayFormat>
        <label>Program Relationship</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/programRelationshipsHistoryController.cls
public with sharing class programRelationshipsHistoryController {
      public string portalName{get;set;}  
    public utilityIds utilIds = new utilityIds();
    public String strContact = System.currentPagereference().getParameters().get('contact');  
    public list<Program_Relationships__c> lstPrograms {get;set;}
    public Contact thisContact {get;set;}
    public String strPR = '';
    public Id prRecordTypeId = null;

    ////////////////////////////////
    // Constructor
    ////////////////////////////////
    public programRelationshipsHistoryController() { 
      portalName = ApexPages.currentPage().getParameters().get('portalName');         
      thisContact = [select id, FirstName, LastName, P_C_Id__c
            from Contact where id = :strContact];   
            
        //CIRT or START user?
            Id prRecordTypeId = null;
            if(thisContact.P_C_ID__c.contains('CRT')) {
                
    //            strPR = '/apex/courtPortal';
      strPR = '/apex/allCourtsPage';
                prRecordTypeID = utilIds.progRelProgramHistoryCIRT;
            } else {
                
                strPR = '/apex/searchPortal_new'; 
                prRecordTypeID = utilIds.progRelProgramHistory;             
            }                   
        
        lstPrograms = new list<Program_Relationships__c>{
            new Program_Relationships__c(Warrant__c = thisContact.Id, 
                RecordTypeId = prRecordTypeID), 
            new Program_Relationships__c(Warrant__c = thisContact.Id, 
                RecordTypeId = prRecordTypeID),
            new Program_Relationships__c(Warrant__c = thisContact.Id, 
                RecordTypeId = prRecordTypeID), 
            new Program_Relationships__c(Warrant__c = thisContact.Id, 
                RecordTypeId = prRecordTypeID), 
            new Program_Relationships__c(Warrant__c = thisContact.Id, 
                RecordTypeId = prRecordTypeID)};                            
    }
    
    ////////////////////////////////
    // Action Methods
    ////////////////////////////////
    public void doNothing() { }   
    
    public pageReference goPortal() {
        pageReference prRef;
        if (portalName != null)
           prRef = new PageReference('/apex/allCourtsPage');
        else
             prRef = new pageReference(strPR);
             prRef.setRedirect(true);
        return prRef;       
    }        
    
    public void savePRS() {  
                       
        try {
            
            list<Program_Relationships__c> lstPRstoInsert = new list<Program_Relationships__c>();
            
            //add cases
            for(Program_Relationships__c pr: lstPrograms) {
            
                //add other cases
                if(pr.Program__c != null) {
                                    
                    lstPRstoInsert.add(pr);
                }           
            }
            
            //cases DML
            if(lstPRstoInsert.size() > 0) {
                
                insert lstPRstoInsert;
                lstPrograms = new list<Program_Relationships__c>{
                    new Program_Relationships__c(Warrant__c = thisContact.Id, 
                        RecordTypeId = prRecordTypeID), 
                    new Program_Relationships__c(Warrant__c = thisContact.Id, 
                        RecordTypeId = prRecordTypeID),
                    new Program_Relationships__c(Warrant__c = thisContact.Id, 
                        RecordTypeId = prRecordTypeID), 
                    new Program_Relationships__c(Warrant__c = thisContact.Id, 
                        RecordTypeId = prRecordTypeID), 
                    new Program_Relationships__c(Warrant__c = thisContact.Id, 
                        RecordTypeId = prRecordTypeID)};
            }
                        
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'There was an error creating the new Client.  Please contact your system administrator and provide this information:  \r\r' + string.valueOf(e)));
        }         
        
    }
    


}