src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Today__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Today</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Today__c</fullName>
        <label>Today</label>
        <type>Date</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/jobUpdateTodayFields.cls
global class jobUpdateTodayFields 
{
    
    global void setToday() {
  //all tiers and cycles modified today, after the nightly run of this job (otherwise all records
        // get updated every night). Also active clients
        List<Tier__c> lstTiers = new List <Tier__c>();
        List<Program_Cycle__c>lstCycles = new List <Program_Cycle__c>();
        if(!Test.IsRunningTest())
            {lstTiers = [select id, Today__c from Tier__c
                                    where Program_Cycle__r.Client__r.Client_Status__c = 'Active'
                                    or LastModifiedDate >= :system.now().addHours(-20)];
            lstCycles = [select id, Today__c from Program_Cycle__c
                                                where Client__r.Client_Status__c = 'Active'
                                                or LastModifiedDate >= :system.now().addHours(-20)];
        }else{
            lstTiers = [select id, Today__c from Tier__c
                                    where Program_Cycle__r.Client__r.Client_Status__c = 'Active'
                                    or LastModifiedDate >= :system.now().addHours(-20)LIMIT 10];        
            lstCycles = [select id, Today__c from Program_Cycle__c
                                     where Client__r.Client_Status__c = 'Active'
                                     or LastModifiedDate >= :system.now().addHours(-20) LIMIT 10];
        }                                        

        for(Tier__c t: lstTiers) {
            
            t.Today__c = system.today();
        }   
        
        for(Program_Cycle__c p: lstCycles) {
            
            p.Today__c = system.today();
        }   
        
        //DML
        if(lstTiers.size() > 0) {
            update lstTiers;
        }
        
        if(lstCycles.size() > 0) {
            update lstCycles;           
        }
    }

}