src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cycle_Type__c</fullName>
        <label>Cycle Type</label>
        <picklist>
            <picklistValues>
                <fullName>Intake</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reinstatement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Track Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transferred In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Tier</label>
        <referenceTo>Tier__c</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/programCycleMethods.cls
public class programCycleMethods {
    
    public list<Program_Cycle__c> lstNewPcs = new list<Program_Cycle__c>();
    public list<Id> lstContactIds = new list<Id>();
    public list<Contact> lstContacts = new list<Contact>();
    
    public void getContacts() {
        
        for(Program_Cycle__c pc: lstNewPcs) {
            
            lstContactIds.add(pc.Client__c);
        }
    
        
        //get all program cycles to loop through
        //get contacts and most recent cycles in scope 
        lstContacts = [select id, Most_Recent_Program_Cycle__c, Most_Recent_Mandated_Cycle__c,
            //subquery
            (select id, Cycle_Type__c
            from Program_Cycles__r order by Start_Date__c asc)
        from Contact where id in :lstContactIds];       
        
    }
    
    public void setMostRecentFlag() {
        
        Program_Cycle__c MostRecentCycle = new Program_Cycle__c();
        Program_Cycle__c MostRecentMandatedCycle = new Program_Cycle__c();
        
        for(Contact c : lstContacts) {
            
            //reset values
            MostRecentCycle = null;
            MostRecentMandatedCycle = null;
        
        	if(c.Program_Cycles__r.size() > 0) {
	            //loop through list by ascending start date, and overwrite past cycles
	            for(Program_Cycle__c pc: c.Program_Cycles__r) {
	            	
	            	system.debug(pc);
	                
	                MostRecentCycle = pc;
	                if(pc.Cycle_Type__c != 'Voluntary') {
	                    
	                    MostRecentMandatedCycle = pc;
	                }
	            }
	            
	            c.Most_Recent_Program_Cycle__c = MostRecentCycle.id;
	            
	            //this case should not occur in general use, only when cycles are being mass uploaded
	            //when they may be in the wrong order
	            if(MostRecentMandatedCycle == null) {
	            	
	            	c.Most_Recent_Mandated_Cycle__c = null;
	            } else {
	            
	            	c.Most_Recent_Mandated_Cycle__c = MostRecentMandatedCycle.id;
	            }
        	} else {
        		
	            c.Most_Recent_Program_Cycle__c = null;
	            c.Most_Recent_Mandated_Cycle__c = null;
        	}
        }
        
        
        //dml
        update lstContacts;
        
    }
    
    public void deleteChildTiers(set<Id> lstDelIDs) {
        
        list<Tier__c> lstTierstoDelete = [select id from Tier__c where Program_Cycle__c in :lstDelIDs];
        
        delete lstTierstoDelete;
        
    }   

}