src/objects/Program_Plan__c.object
<CustomObject>
    <description>CEP Program Plan Object</description>
    <fields>
        <fullName>Client_Name__c</fullName>
        <label>Client Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Plans</relationshipLabel>
        <relationshipName>Program_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Program_Plan__c</fullName>
        <formula>Client_Name__r.Most_Recent_Program_Plan__c = Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Most Recent Program Plan?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>P_C_ID__c</fullName>
        <description>get P/C ID from contact</description>
        <formula>Client_Name__r.P_C_ID__c</formula>
        <label>P/C ID</label>
        <type>Text</type>
    </fields>
    <label>Program Plan</label>
    <nameField>
        <displayFormat>PP-{000000}</displayFormat>
        <label>Program Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Progress_Note__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <picklist>
            <picklistValues>
                <fullName>Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Escort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis Intervention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Empowerment and Self Help</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Entitlements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Life and Social Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare Coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare Linkage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Homes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Support Facilitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Judicial and Civic Accountability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal/Recidivism Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Linkage To Services (Other)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical ER Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medication Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health Treatment Linkage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Client_Name__c</fullName>
        <formula>Program_Plan__r.Client_Name__r.FirstName &amp; &apos; &apos; &amp; Program_Plan__r.Client_Name__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <description>Date w/ default date created. Read-only except for System Administrators</description>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Program_Plan__c</fullName>
        <label>Program Plan</label>
        <referenceTo>Program_Plan__c</referenceTo>
        <relationshipLabel>Progress Notes</relationshipLabel>
        <relationshipName>Progress_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Progress_Note__c</fullName>
        <label>Progress Note</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Progress Note</label>
    <nameField>
        <displayFormat>P_Note-{0000}</displayFormat>
        <label>Progress Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Progress Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/setCIRTClientNotEligibleController.cls
public with sharing class setCIRTClientNotEligibleController {
    
    public utilityIds utilIds = new utilityIds();
    public String strContact = System.currentPagereference().getParameters().get('contact');  

    public Contact thisContact {get;set;}
    public Program_Plan__c thisPP {get;set;}
    public Progress_Note__c thisPN {get;set;}
    public Task tskDummy {get;set;}
    public String strRejectReason {get;set;}
    public Boolean bolSaveSuccessful {get;set;}

    ////////////////////////////////
    // Constructor
    ////////////////////////////////
    public setCIRTClientNotEligibleController() { 
        
        thisContact = [select id, FirstName, LastName, P_C_ID__c, Client_Status__c, Intake_Case__c
            from Contact where id = :strContact];           
            
        thisPP = [select id from Program_Plan__c where Most_Recent_Program_Plan__c = true
            and Client_Name__c = :strContact];  
            
        thisPN = new Progress_Note__c(Program_Plan__c = thisPP.id, 
            recordTypeId = utilIds.progressNoteCIRT, Area__c = 'Judicial and Civic Accountability');
            
        tskDummy = new Task(ActivityDate = system.today()); 
            
    }
    
    ////////////////////////////////
    // Action Methods
    ////////////////////////////////
    public void doNothing() { }
    
    public List<SelectOption> getLstReasons() {
        
        List<SelectOption> lstTemp = new List<SelectOption>();
        
        lstTemp.add(new SelectOption('', ''));
        lstTemp.add(new SelectOption('Accepted Other ATI-Program-Offer', 'Accepted Other ATI-Program-Offer'));        
        lstTemp.add(new SelectOption('Already involved in another program', 'Already involved in another program'));
        lstTemp.add(new SelectOption('Discharged from DOC', 'Discharged from DOC'));
        lstTemp.add(new SelectOption('Excluded Charge', 'Excluded Charge'));
 //       lstTemp.add(new SelectOption('Attorney not consented', 'Attorney not consented'));  
        lstTemp.add(new SelectOption('Ineligible', 'Ineligible'));
        lstTemp.add(new SelectOption('Rejected by Attorney', 'Rejected by Attorney'));
        lstTemp.add(new SelectOption('Rejected by ADA', 'Rejected by ADA'));          
        lstTemp.add(new SelectOption('Rejected by Inmate-Client', 'Rejected by Inmate-Client'));
        lstTemp.add(new SelectOption('Rejected by Judge', 'Rejected by Judge'));
        lstTemp.add(new SelectOption('Sentenced-Plead at CIRT referral', 'Sentenced-Plead at CIRT referral'));  
        lstTemp.add(new SelectOption('730 Ordered', '730 Ordered'));
        lstTemp.add(new SelectOption('Unfit', 'Unfit'));
        lstTemp.add(new SelectOption('Other', 'Other'));
 
  
        return lstTemp;
        
    }      
      
    
    public void updateClient() {
        
        string strTempOutcome = '';
        
        try {
            
            //old code for multipicklist
            /*
            for(string s: strRejectReasons.split(';', 0)) {
                
                strTempOutcome += s;
                strTempOutcome += ', ';
            }
            
            strTempOutcome = strTempOutcome.substring(1, strTempOutcome.length()-3);
            thisCase.Final_Outcome__c = strTempOutcome;*/
        
                
            thisContact.Client_Status__c = 'Never Enrolled';                
            thisContact.CIRT_Final_Outcome__c = strRejectReason; 
            thisContact.CIRT_Final_Outcome_Date__c = tskDummy.ActivityDate;
            thisContact.Final_Outcome_Modified_Date__c = system.today();
                        
            update thisContact;
            
            if(thisPN.Progress_Note__c != null) {
                
                thisPN.Date__c = tskDummy.ActivityDate;
                insert thisPN;
            }
            
            bolSaveSuccessful = true;
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'There was an error creating the new Client.  Please contact your system administrator and provide this information:  \r\r' + string.valueOf(e)));
            bolSaveSuccessful = false;
        }
        
    }
    


}