src/objects/Program_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Program_Cycle_Formula__c</fullName>
        <formula>Client__r.Most_Recent_Program_Cycle__c = Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Most Recent Program Cycle?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Most Recent Tier</label>
        <referenceTo>Tier__c</referenceTo>
        <relationshipLabel>Program Cycles</relationshipLabel>
        <relationshipName>Program_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Cycle</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Program Cycle Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tier__c.object
<CustomObject>
    <fields>
        <fullName>Most_Recent_Tier__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Most Recent Tier?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Cycle__c</fullName>
        <label>Program Cycle</label>
        <referenceTo>Program_Cycle__c</referenceTo>
        <relationshipLabel>Tiers</relationshipLabel>
        <relationshipName>Tiers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Supervision Level</description>
        <inlineHelpText>for SRP this is called Supervision Level</inlineHelpText>
        <label>Tier</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tier</label>
    <nameField>
        <displayFormat>TR-{00000}</displayFormat>
        <label>Tier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/srpSupervisionLevelExt.cls
/*
 * Block comments with details of changes
 */
public class srpSupervisionLevelExt
{
    public String contactID {get; set;}
    public String contactName {get; set;}
    private final Contact srpCon;
    
    public srpSupervisionLevelExt(ApexPages.StandardController stdController  )
    {
        this.srpCon = (Contact)stdController.getRecord();
        contactName = srpCon.Name ;
        contactId = srpCon.Id;        
    }
    
    public PageReference save()
    {   
        List<Program_Cycle__c> progCycleList = new List<Program_Cycle__c>();
        progCycleList = [SELECT Id, Most_Recent_Tier__c FROM Program_Cycle__c 
                         WHERE Client__c = :srpCon.Id AND Most_Recent_Program_Cycle_Formula__c = TRUE LIMIT 1];
        if (progCycleList.size() > 0) 
        {
            Tier__c tier = null;
            try
            {
                tier = [SELECT Id, Tier__c FROM Tier__c WHERE Id = :progCycleList[0].Most_Recent_Tier__c];
            } catch (System.QueryException qe)
                {
                    system.debug (' *** No tier record found! *** ');
                }
            if (tier != null)
            {
                tier.Tier__c = srpCon.Supervision_Level__c;
                update Tier;
            }
        } else { system.debug (' *** No program cycle record found! *** ');}
        
        upsert srpCon;

        
        PageReference pref = new PageReference('/'+ srpCon.Id);
        pref.setRedirect(true);
        return pref;
    }

    public PageReference cancel()
    {
        PageReference pageRef = new PageReference('/'+ srpCon.Id);
        pageRef.setRedirect(true);
        return pageRef;    
    }
}