src/objects/SR_Intake_Needs_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>AssessmentID__c</fullName>
        <description>Parent ID of this assessment</description>
        <label>Assessment</label>
        <referenceTo>Assessment__c</referenceTo>
        <relationshipLabel>SR Intake Needs Assessments</relationshipLabel>
        <relationshipName>SR_Intake_Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>Specific assessments have two master-detail relationships (Assessment and Contact)</description>
        <label>Participant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>SR Intake Needs Assessments</relationshipLabel>
        <relationshipName>SR_Intake_Needs_Assessments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>SR Intake Needs Assessment</label>
    <nameField>
        <displayFormat>SR-NA{0000}</displayFormat>
        <label>SR Intake Needs Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SR Intake Needs Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/srpNeedsMasterExt.cls
public with sharing class srpNeedsMasterExt 
{
    //public SR_Intake_Needs_Assessment__c srNeeds {get; set;}
    public String retURL = ApexPages.currentPage().getParameters().get('retURL');
    private final Assessment__c srpMaster;

    public srpNeedsMasterExt(ApexPages.StandardController stdController) 
    {
        this.srpMaster = (Assessment__c)stdController.getRecord();
    }

    public pageReference initialize()
    {
        if(srpMaster.Id == null)
        {
            String contactId = ApexPages.currentPage().getParameters().get('contactId');
            srpMaster.Contact__c = contactId;
            srpMaster.RecordTypeId = Schema.SObjectType.Assessment__c.getRecordTypeInfosByName().get('SR Intake Needs Assessment').getRecordTypeId();
            insert srpMaster;
            SR_Intake_Needs_Assessment__c srNeeds = New SR_Intake_Needs_Assessment__c();
            srNeeds.AssessmentID__c = srpMaster.Id;
            srNeeds.Participant__c = srpMaster.Contact__c;
            insert srNeeds;
            srpMaster.SR_Intake_Needs__c = srNeeds.Id;
            update srpMaster;
        }

        PageReference pageRef= new PageReference('/'+ srpMaster.SR_Intake_Needs__c + '/e');
        pageRef.setRedirect(true);
        return pageRef;
    }

}